### PR TITLE
Only use SDL wakelock on Linux

### LINKED ISSUE #10674: Yuzu shows up as "My SDL application" under DBus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

master

### Description of Issue

On Linux, Yuzu, using SDL, currently shows up as "My SDL application" under DBus. This can be seen when Yuzu is, for example, blocking sleep and screen locking, and the desktop environment reports a message such as "My SDL application is currently blocking sleep and screen locking."

Offending source code is in SDL itself: https://github.com/libsdl-org/SDL/blob/4c0758a234658a0f48a56d2263c744aaa9cee898/src/core/linux/SDL_dbus.c#L471

Screenshot from KDE:
image

Side info: Factorio used to have a similar issue, they resolved it by simply static linking and patching that line in SDL source: https://forums.factorio.com/viewtopic.php?t=77451

### Expected Behavior

Yuzu shows up as "Yuzu".

### Reproduction Steps

Run Yuzu on KDE Plasma, open Power Management in taskbar.

### Log File

Irrelevant.

### System Configuration

OS: Artix Linux, KDE Plasma.

### PR DESCRIPTION
**Pull request by zeltermann**
Closes #10674.

SDL has internally fixed shenanigans related to wakelocking through DBus from inside sandboxes from around August 2022, so we can now remove the workaround we used since 2021.

### CODE REVIEW

File: src/yuzu/main.cpp [hunk 1]
```diff
@@ -444,6 +444,13 @@ GMainWindow::GMainWindow(std::unique_ptr<Config> config_, bool has_broken_vulkan
 
 #if defined(HAVE_SDL2) && !defined(_WIN32)
     SDL_InitSubSystem(SDL_INIT_VIDEO);
+
+    //: TRANSLATORS: This string is shown to the user to explain why yuzu needs to prevent the
+    //: computer from sleeping
+    QByteArray reason = QCoreApplication::translate("GMainWindow", "Running a game")
+                            .toLatin1();
+    SDL_SetHint(SDL_HINT_SCREENSAVER_INHIBIT_ACTIVITY_NAME, reason.data());
+
```
Comment (zeltermann) [inline src/yuzu/main.cpp:453]: This pull request changes this translated string from `yuzu is running a game` to `Running a game`. Is there anything else I need to worry about, apart from keeping the `: TRANSLATORS:` comment?

File: src/yuzu/main.cpp [hunk 2]
```diff
@@ -444,6 +444,15 @@ GMainWindow::GMainWindow(std::unique_ptr<Config> config_, bool has_broken_vulkan
 
 #if defined(HAVE_SDL2) && !defined(_WIN32)
     SDL_InitSubSystem(SDL_INIT_VIDEO);
+
+    // Set a screensaver inhibition reason string. Currently passed to DBus by SDL and visible to
+    // the user through their desktop environment.
+    //: TRANSLATORS: This string is shown to the user to explain why yuzu needs to prevent the
+    //: computer from sleeping
+    QByteArray reason = QCoreApplication::translate("GMainWindow", "Running a game")
+                            .toLatin1();
```
Comment (zeltermann) [inline src/yuzu/main.cpp:453]: This pull request changes this translated string from `yuzu is running a game` to `Running a game`. Is there anything else I need to worry about, apart from keeping the `: TRANSLATORS:` comment?

**Comment by zeltermann** [comment]
Just in case it's not obvious, this is the results with this PR applied:

image

File: src/yuzu/main.cpp (hunk 2 above)
Comment (liamwhite) [reply src/yuzu/main.cpp:453]: This works, though it's a bit weird to not be using `tr()` for this.

**Comment by amayra** [comment]
does yuzu in Linux use the SDL package from the distro repo ?

The last time I checked the windows package yuzu didn't use the last version of SDL

**Comment by german77** [comment]
Soon to be updated here https://github.com/yuzu-emu/yuzu/pull/10389 just fermenting for a bit before merging to mainline

**Comment by zeltermann** [comment]
Previous two commits should also fix CI complaining about formatting.

**Comment by v1993** [comment]
> does yuzu in Linux use the SDL package from the distro repo ?
> 
> The last time I checked the windows package yuzu didn't use the last version of SDL

Official builds/manual builds with default settings do not due to relying on specific configuration of SDL (namely, having HIDAPI drivers enabled) as well as appimage bundling vast majority of libraries utilized by yuzu. It's possible to use distro's SDL if you want to even without rebuilding via [dynapi](https://wiki.libsdl.org/SDL2/README/dynapi) mechanism provided by SDL - all you need to do is set an env variable. Be aware that this WILL worsen support for a few controllers, although not for joycons thanks to yuzu using its own driver for them (there's also experimental procon driver that can be enabled in settings).

**Comment by zeltermann** [comment]
Sorry for the spam for anyone actively watching, I just squashed all the commits into one for the sake of it.

**Review by liamwhite — APPROVED** [review]
