### PR TITLE
main: Enable High DPI fixes for Qt >= 5.14

### LINKED ISSUE #4904: The controller settings panel UI is messed up with Scale and Layout set to 200% on Window 10
The controller settings panel UI is messed up with Scale and Layout set to 200% on Window 10 

Yuzu 429
Windows10 20H2

image

### LINKED ISSUE #7383: Problems in control config?
I have no idea what's going on but this is what i see.
Screenshot 2021-11-19 195133

Yuzu EA 2223

Windows 11 
Nvidia 2060 RTX
4K monitor at  3840 x 2160

### LINKED ISSUE #8051: Controls panels is unreadable on 4K screen
the inputs overflow the texts making them unreadable. I suppose this is because of HIDPI.
(15" screen)

### PR DESCRIPTION
**Pull request by Morph1984**
This uses Qt's new high DPI application attributes for scaling the current window.
However, these aren't perfect as scaling with non integer scales will cause artifacts in UI, icons and other elements.
Therefore, we use a heuristic to select an appropriate integer scale value depending on the current screen resolution and applies this to the application.

Fixes #4904
Fixes #7383
Fixes #8051

### CODE REVIEW

File: src/yuzu/main.cpp [hunk 1]
```diff
@@ -2957,8 +2958,42 @@ int main(int argc, char* argv[]) {
     chdir(bin_path.c_str());
 #endif
 
+    // Create a temporary QApplication as a workaround to get the current screen geometry.
```
Comment (lioncash) [inline src/yuzu/main.cpp:2961]: This block of added code should definitely be in its own function

File: src/yuzu/main.cpp [hunk 2]
```diff
@@ -2940,6 +2941,41 @@ void GMainWindow::SetDiscordEnabled([[maybe_unused]] bool state) {
 #undef main
 #endif
 
+void SetHighDPIAttributes(int argc, char* argv[]) {
```
Comment (lioncash) [inline src/yuzu/main.cpp:2944]:
```suggestion
static void SetHighDPIAttributes(int argc, char* argv[]) {
```

**Comment by Tatsh** [comment]
I run with scale 150% on Linux and do not have this issue. Is this really only a Windows issue?

**Comment by tastyratz** [comment]
> I run with scale 150% on Linux and do not have this issue. Is this really only a Windows issue?

Windows and windows applications historically do a really poor job handling high DPI displays. Unix and MAC devices have been using them for much longer and are better suited. I can't speak to how yuzu looks on other operating systems but I can say on a 4k tv it's not been legible.  
image

**Comment by Tatsh** [comment]
I tested this change and it does not break anything on Linux.

File: src/yuzu/main.cpp [hunk 3]
```diff
@@ -3753,6 +3754,41 @@ void GMainWindow::SetDiscordEnabled([[maybe_unused]] bool state) {
 #undef main
 #endif
 
+static void SetHighDPIAttributes(int argc, char* argv[]) {
+    // Create a temporary QApplication as a workaround to get the current screen geometry.
+    QApplication* temp_app = new QApplication(argc, argv);
```
Comment (lioncash) [inline src/yuzu/main.cpp:3759]: Aren't you able to use the static member function `QGuiApplication::primaryScreen()` to get this without the need for a temporary application to be created?

Comment (Tatsh) [reply src/yuzu/main.cpp]: Getting a segfault since this change. It seems `QGuiApplication::primaryScreen()` can return null in some cases. Seems likely to be OS-specific. In this case Linux. Maybe we should add `#ifdef Q_OS_LINUX` and use the other way on Linux?

```
#0  QScreen::geometry() const (this=this@entry=0x0)
    at /var/tmp/portage/dev-qt/qtgui-5.15.3/work/qtbase-everywhere-src-5.15.3/src/gui/kernel/qscreen.cpp:413
#1  0x00005555556c3373 in SetHighDPIAttributes (argc=<optimized out>, argv=0x7fffffffcdb8)
    at /var/tmp/portage/games-emulation/yuzu-0.1010/work/yuzu-mainline-mainline-0-1010/src/yuzu/main.cpp:3940
#2  main(int, char**) (argc=<optimized out>, argv=0x7fffffffcdb8)
    at /var/tmp/portage/games-emulation/yuzu-0.1010/work/yuzu-mainline-mainline-0-1010/src/yuzu/main.cpp:4000
```

Comment (Tatsh) [reply src/yuzu/main.cpp]: I tried the old way and it crashes too.

```
Thread 1 "yuzu" received signal SIGSEGV, Segmentation fault.
QObject::property (this=0x41, name=name@entry=0x7fffedff6860 <scaleFactorProperty> "_q_scaleFactor") at /var/tmp/portage/dev-qt/qtcore-5.15.3/work/qtbase-everywhere-src-5.15.3/include/QtCore/../../src/corelib/tools/qscopedpointer.h:116
116     /var/tmp/portage/dev-qt/qtcore-5.15.3/work/qtbase-everywhere-src-5.15.3/include/QtCore/../../src/corelib/tools/qscopedpointer.h: No such file or directory.
(ins)(gdb) bt
#0  QObject::property(char const*) const
    (this=0x41, name=name@entry=0x7fffedff6860 <scaleFactorProperty> "_q_scaleFactor")
    at /var/tmp/portage/dev-qt/qtcore-5.15.3/work/qtbase-everywhere-src-5.15.3/include/QtCore/../../src/corelib/tools/qscopedpointer.h:116
#1  0x00007fffedc19bc5 in QHighDpiScaling::screenSubfactor(QPlatformScreen const*)
    (screen=0x7fffed256ce0 <main_arena+96>)
    at /var/tmp/portage/dev-qt/qtgui-5.15.3/work/qtbase-everywhere-src-5.15.3/src/gui/kernel/qhighdpiscaling.cpp:662
#2  0x00007fffedc1ab0d in QHighDpiScaling::logicalDpi(QScreen const*) (screen=0x555556c04ca0)
    at /var/tmp/portage/dev-qt/qtgui-5.15.3/work/qtbase-everywhere-src-5.15.3/src/gui/kernel/qhighdpiscaling.cpp:687
#3  0x00007fffedc0a539 in QScreen::logicalDotsPerInch() const (this=this@entry=0x555556c04ca0)
    at /var/tmp/portage/dev-qt/qtgui-5.15.3/work/qtbase-everywhere-src-5.15.3/src/gui/kernel/qscreen.cpp:352
#4  0x00005555556c33e4 in SetHighDPIAttributes (argv=0x7fffffffcd88, argc=<optimized out>)
    at /var/tmp/portage/games-emulation/yuzu-0.1010-r1/work/yuzu-mainline-mainline-0-1010/src/yuzu/main.cpp:3947
#5  main(int, char**) (argc=<optimized out>, argv=0x7fffffffcd88)
    at /var/tmp/portage/games-emulation/yuzu-0.1010-r1/work/yuzu-mainline-mainline-0-1010/src/yuzu/main.cpp:4004
```

I think Qt has changed the behaviour of these methods. I think at least one window must be created before these can be called.

Comment (lioncash) [reply src/yuzu/main.cpp]: In Qt 6 only the `QGuiApplication::primaryScreen()` function is available, since all other deprecated members are removed, so this will code will likely need to be modified wholesale if that's the case (and adding yet another linux edge case on the pile)

Comment (Tatsh) [reply src/yuzu/main.cpp]: There's a number of interesting bugs regarding this method.

https://bugreports.qt.io/secure/QuickSearch.jspa?searchString=primaryScreen+crash

and in particular: https://bugreports.qt.io/browse/QTBUG-73166 https://bugreports.qt.io/browse/QTBUG-71034

Apparently, `primaryScreen()`'s return value should be checked. But in my case, I still don't know why both my Linux machines give no value for `QGuiApplication::primaryScreen()` in this function. I am using Qt 5.15.3.

File: src/yuzu/main.cpp [hunk 4]
```diff
@@ -3753,6 +3754,37 @@ void GMainWindow::SetDiscordEnabled([[maybe_unused]] bool state) {
 #undef main
 #endif
 
+static void SetHighDPIAttributes(int argc, char* argv[]) {
```
[the remark this answers is not in the document]
Comment (Morph1984) [reply src/yuzu/main.cpp]: Resolved

File: src/yuzu/main.cpp [hunk 5]
```diff
@@ -3753,6 +3754,37 @@ void GMainWindow::SetDiscordEnabled([[maybe_unused]] bool state) {
 #undef main
 #endif
 
+static void SetHighDPIAttributes() {
+    // Get the current screen geometry.
+    const QScreen* primary_screen = QGuiApplication::primaryScreen();
```
Comment (Tatsh) [inline src/yuzu/main.cpp:3759]: Let's check this value for `nullptr`. If `nullptr` is returned just return immediately. There are bugs regarding `primaryScreen()`.

https://bugreports.qt.io/secure/QuickSearch.jspa?searchString=primaryScreen+crash

and in particular: https://bugreports.qt.io/browse/QTBUG-73166 https://bugreports.qt.io/browse/QTBUG-71034

**Comment by liamwhite** [comment]
What's the status on this? Still not mergeable?

**Comment by Morph1984** [comment]
After 2 years, this is probably ready for testing, lol

**Review by liamwhite — APPROVED** [review]

**Review by Tatsh — APPROVED** [review]
