### PR TITLE
vfs: expand support for NCA reading

### LINKED ISSUE #7371: NSPs with FS entry offsets outside of the total NCA length cannot be decrypted
Ruined King: A League of Legends Story cannot boot due to the emulator unable to decrypt the file.
This also applies to Last Stop, Lost in Random, No More Heroes 3 (eShop dump), and Hextech Mayhem: A League of Legends Story.

Narr confirmed with me that this is a known issue and is being looked into but for archival purposes and to keep track of it I open this issue.

Mainline 815
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7568203/yuzu_log.txt)

### LINKED ISSUE #7905: Yuzu freezing over when trying to dump romFS on certain games
I was trying to dump the romFS of **Gunvolt Chronicles: Luminous Avenger iX 2** or **Yo-kai Watch 1 for Nintendo Switch** and Yuzu would become irresponsible before ever prompting the options window. At the same time, the entire system would slow down until the app is force-quit.

### LINKED ISSUE #8836: [Coursed to Golf] Doesn't boot
Yuzu mainline 1150 and EA 2924

Game : Coursed to Golf
Version :Base game

System details :
 CPU : R9 3900X
 GPU : NVIDIA RTX 3080
 RAM : 16GB
 OS : W11 

full log : 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9457875/yuzu_log.txt)

### LINKED ISSUE #9384: [Bug Report] Front Mission won't boot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1261

### Description of Issue

Front Mission won't get past the boot sequence
image

### Expected Behavior

Game booting

### Reproduction Steps

Open the game and wait

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10155431/yuzu_log.txt.old.txt)

### System Configuration

CPU: R5 5600x
GPU/Driver: 3060ti/527.37
RAM: 16gb
OS: win10

### LINKED ISSUE #10021: Sports Story v1.0.5 stuck on launching
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3492

### Description of Issue

When trying to launch Sports Story v1.0.5 (I've tried every update to the same effect), it endlessly shows "Launching". I've tried changing every setting under the sun in every different configuration I could possibly think of, without any luck. 

### Expected Behavior

Game expected to launch without being stuck on 'Launching" screen.

### Reproduction Steps

1. Open Yuzu
2. Launch Sports Story

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11129587/yuzu_log.txt)

### System Configuration

CPU: Core i7-6700HQ
GPU/Driver: GTX 960m
RAM: 32GB
OS: Windows 10 x64

### LINKED ISSUE #10045: Atelier Ryza 3 Alchemist of the End & the Secret Key (NSP)(US) - stuck at launching
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1400

### Description of Issue

Stuck at launching. Log shows crashing after romfs patching. error thrown:
```
[  13.265403] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:69: (STUBBED) called
[  13.285869] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:419: Patching RomFS for title_id=010095E018944000, type=01
[  13.286649] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[  13.290646] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:419: Patching RomFS for title_id=010095E018944000, type=01
[  13.291242] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[  13.296185] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1551: (STUBBED) called, result=0x00217202
[  13.296530] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:51: Userspace PANIC! info1=0x000000100B803578, info2=0x0000000000000004
[  13.296532] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:operator ():32: debug_buffer_err_code=217202
[  13.296539] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:101: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100B803578, info2=0x0000000000000004
[  13.296540] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:82: Backtrace, sp=000000100B8033C0, pc=000000000A966B44
[  13.296542] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:84: Module Name         Address             Original Address    Offset              Symbol
[  13.296542] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:85: 
[  13.378195] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 0000007100158B44    000000000A966B44    0000000000158B44    
[  13.378202] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 000000710008F108    000000000A89D108    000000000008F108    nn::diag::detail::Abort(nn::Result const*)
[  13.378203] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 000000710008D8B8    000000000A89B8B8    000000000008D8B8    
[  13.378205] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 000000710008D97C    000000000A89B97C    000000000008D97C    
[  13.378207] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 00000071000D652C    000000000A8E452C    00000000000D652C    nn::fs::MountRom(char const*, void*, unsigned long)
[  13.378208] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                00000071009A3B08    00000000089A7B08    00000000009A3B08    
[  13.378210] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                00000071009A3194    00000000089A7194    00000000009A3194    
[  13.378211] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                0000007100974620    0000000008978620    0000000000974620    
[  13.378211] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                00000071009747BC    00000000089787BC    00000000009747BC    
[  13.378212] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                0000007100C91144    0000000008C95144    0000000000C91144    
[  13.378213] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                0000007100C92C40    0000000008C96C40    0000000000C92C40    nnMain
[  13.378215] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 00000071000FA414    000000000A908414    00000000000FA414    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
[  13.378216] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: rtld                00000071000000D4    00000000080000D4    00000000000000D4    

```

### Expected Behavior

Game launches into menu screen.

### Reproduction Steps

Launch game from yuzu home screen.

### Log File

[yuzu_log_atelier-crash.txt](https://github.com/yuzu-emu/yuzu/files/11202530/yuzu_log_atelier-crash.txt)

### System Configuration

CPU: AMD Ryzen 7 3800X 8-Core Processor                3.90 GHz
GPU/Driver: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL_VERSION: 4.6.0 NVIDIA 531.18
RAM: 32GB
OS: Windows 10 Version 21H2 (Build 19044.2728)

### LINKED ISSUE #10157: MLB® The Show™ 23 does not boot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1420

### Description of Issue

MLB® The Show™ 23 does not boot. 

`Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:51: Userspace PANIC! info1=0x000000100DD03908, info2=0x0000000000000004`
`Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:operator ():32: debug_buffer_err_code=217202`
`Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:101: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100DD03908, info2=0x0000000000000004`

This game will probably hit a file system error after this kernel error going off its predecessor #7911

### Expected Behavior

Game boots

### Reproduction Steps

Launch the game

### Log File

[yuzu_log MLB 23.txt](https://github.com/yuzu-emu/yuzu/files/11400578/yuzu_log.MLB.23.txt)

### System Configuration

CPU: R7 3700X
GPU/Driver: RTX 4070 531.79
RAM: 16 GB
OS: Windows 10 22H2

### LINKED ISSUE #10687: "Hatsune Miku - The Planet Of Wonder And Fragments Of Wishes" Fails to start, Dump RomFS causes yuzu freeze.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

master-4d395b3b7 / mainline 1463

### Description of Issue

A recently released switch game, "Hatsune Miku - The Planet Of Wonder And Fragments Of Wishes" for the Americas region failed to start. Will not go beyond switch splash screen but can be stopped gracefully. Also trying to run any "Dump RomFS" command will cause Yuzu to freeze and need for it to be killed. It does not output any logs for the RomFS dump but does contain a log output when booting the game. 

I only have this issue with this new game (that came out on June 7th 2023 and just purchased on launch day). All my other Yuzu games start just fine. It's likely a CPU or file system issue
I did also attach the game specific settings window to show that metadata was accessible..
Screenshot_20230609_172911

### Expected Behavior

When on Yuzu menu the icon and basic metadata will appear just fine.

For starting the game, it will not progress past the switch start screen. Before any early game logos (Like Publisher or Age Rating) logos appear. Will just hang there indefinitely until it is shutdown.

I also tried to use the "Dump RomFS" option and will cause a Yuzu stall quickly. Yuzu will not do anything unless it is killed in system monitor.

### Reproduction Steps

Using Yuzu mainline AppImage on Kubuntu 23.04 (as well as building from source on same system) will cause this issue with "Hatsune Miku - The Planet Of Wonder And Fragments Of Wishes" no matter the GPU, CPU settings. It can also happen when being the first game to open upon starting Yuzu, or opening another game first, closing the first game and then starting "Hatsune Miku - The Planet Of Wonder And Fragments Of Wishes".

### Log File

[   0.093750] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.094634] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.307716] Input <Info> input_common/drivers/joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.390833] Frontend <Info> yuzu/main.cpp:GMainWindow:360: yuzu Version: yuzu 1463
[   0.390838] Frontend <Info> yuzu/main.cpp:LogRuntimes:248: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.390840] Frontend <Info> yuzu/main.cpp:GMainWindow:376: Host CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | AVX512 | FMA
[   0.390868] Frontend <Info> yuzu/main.cpp:GMainWindow:378: Host CPU Cores: 4
[   0.390870] Frontend <Info> yuzu/main.cpp:GMainWindow:381: Host CPU Threads: 8
[   0.390886] Frontend <Info> yuzu/main.cpp:GMainWindow:382: Host OS: Ubuntu 23.04
[   0.390901] Frontend <Info> yuzu/main.cpp:GMainWindow:383: Host RAM: 31.04 GiB
[   0.390903] Frontend <Info> yuzu/main.cpp:GMainWindow:385: Host Swap: 0.00 GiB
[   0.559038] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.561056] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.561543] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.562898] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.563342] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.563854] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.564365] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.15.0) applied successfully
[   0.565251] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.565700] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.567449] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.568743] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.13.0) applied successfully
[   0.569212] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.573821] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.575924] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.583566] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.585887] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.588793] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.591935] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.15.0) applied successfully
[   0.598253] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.601455] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.613244] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.620423] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.13.0) applied successfully
[   0.639581] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.9.0) applied successfully
[   0.642989] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.646456] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.3.0) applied successfully
[   0.649814] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.656589] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.659914] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.40.0) applied successfully
[   0.666796] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.9.0) applied successfully
[   0.670309] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.673786] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.6.0) applied successfully
[   0.677268] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully
[   0.680820] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.684804] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.6.0) applied successfully
[   0.688710] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.27.0) applied successfully
[   0.695898] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.3.0) applied successfully
[   0.699375] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.3.0) applied successfully
[   0.702908] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.706345] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.709894] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.717697] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.724610] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.731719] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.735291] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.738808] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.742401] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully
[   0.749382] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.752589] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.9.0) applied successfully
[   0.756073] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.759886] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.3.0) applied successfully
[   0.764376] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.772424] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.774651] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.40.0) applied successfully
[   0.782563] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.9.0) applied successfully
[   0.786817] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.790384] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.6.0) applied successfully
[   0.794138] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully
[   0.798643] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.801894] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.6.0) applied successfully
[   0.805387] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.27.0) applied successfully
[   0.811175] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.3.0) applied successfully
[   0.813361] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.3.0) applied successfully
[   0.816610] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.818763] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.821058] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.827710] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.833238] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.838242] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.2.0) applied successfully
[   0.841009] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.843291] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.5.0) applied successfully
[   0.845552] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully
[   0.850861] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[  84.616001] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[  84.616007] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[  84.616008] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[  84.616008] Config <Info> common/settings.cpp:operator():33: System_DeviceName: Yuzu
[  84.616010] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 0
[  84.616010] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[  84.616010] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[  84.616011] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[  84.616011] Config <Info> common/settings.cpp:operator():33: System_UnsafeMemoryLayout: true
[  84.616011] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[  84.616012] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[  84.616013] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 2
[  84.616013] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 5
[  84.616028] Config <Info> common/settings.cpp:operator():33: Renderer_FSRSlider: 25
[  84.616029] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 0
[  84.616029] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[  84.616030] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[  84.616031] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[  84.616032] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 0
[  84.616032] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[  84.616033] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 1
[  84.616034] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[  84.616034] Config <Info> common/settings.cpp:operator():33: Renderer_AsyncASTC: false
[  84.616035] Config <Info> common/settings.cpp:operator():33: Renderer_AstcRecompression: 0
[  84.616036] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: 2
[  84.616037] Config <Info> common/settings.cpp:operator():33: Renderer_UseReactiveFlushing: true
[  84.616039] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 0
[  84.616040] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: false
[  84.616042] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 1
[  84.616042] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: cubeb
[  84.616043] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[  84.616043] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[  84.616045] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[  84.616046] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/emperor_penguin_of_japan/.cache/yuzu
[  84.616046] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/emperor_penguin_of_japan/.config/yuzu
[  84.616047] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/emperor_penguin_of_japan/.local/share/yuzu/load
[  84.616048] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/emperor_penguin_of_japan/.local/share/yuzu/nand
[  84.616048] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/emperor_penguin_of_japan/.local/share/yuzu/sdmc
[  84.616050] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs: 
[  84.616051] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[  84.616053] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[  84.616055] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[  84.616055] Config <Info> common/settings.cpp:operator():33: Input_EnableTouch: true
[  84.616057] Config <Info> common/settings.cpp:operator():33: Input_EnableMouse: false
[  84.616057] Config <Info> common/settings.cpp:operator():33: Input_EnableKeyboard: false
[  84.616059] Config <Info> common/settings.cpp:operator():33: Input_EnableRingController: true
[  84.616060] Config <Info> common/settings.cpp:operator():33: Input_EnableIrSensor: false
[  84.616061] Config <Info> common/settings.cpp:operator():33: Input_EnableCustomJoycon: true
[  84.616062] Config <Info> common/settings.cpp:operator():33: Input_EnableCustomProController: false
[  84.616063] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false
[  85.929555] Frontend <Info> yuzu/main.cpp:BootGame:1849: yuzu starting...
[  85.944014] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[  85.944018] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[  85.944019] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[  85.944019] Config <Info> common/settings.cpp:operator():33: System_DeviceName: Yuzu
[  85.944020] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 0
[  85.944020] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[  85.944020] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[  85.944021] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[  85.944021] Config <Info> common/settings.cpp:operator():33: System_UnsafeMemoryLayout: true
[  85.944022] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[  85.944023] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[  85.944023] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 2
[  85.944024] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 5
[  85.944024] Config <Info> common/settings.cpp:operator():33: Renderer_FSRSlider: 25
[  85.944025] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 0
[  85.944025] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[  85.944025] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[  85.944026] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[  85.944026] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 0
[  85.944026] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[  85.944027] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 1
[  85.944027] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[  85.944028] Config <Info> common/settings.cpp:operator():33: Renderer_AsyncASTC: false
[  85.944028] Config <Info> common/settings.cpp:operator():33: Renderer_AstcRecompression: 0
[  85.944029] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: 2
[  85.944029] Config <Info> common/settings.cpp:operator():33: Renderer_UseReactiveFlushing: true
[  85.944029] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 0
[  85.944030] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: false
[  85.944030] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 1
[  85.944030] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: cubeb
[  85.944031] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[  85.944031] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[  85.944033] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[  85.944034] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/emperor_penguin_of_japan/.cache/yuzu
[  85.944035] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/emperor_penguin_of_japan/.config/yuzu
[  85.944035] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/emperor_penguin_of_japan/.local/share/yuzu/load
[  85.944036] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/emperor_penguin_of_japan/.local/share/yuzu/nand
[  85.944037] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/emperor_penguin_of_japan/.local/share/yuzu/sdmc
[  85.944037] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs: 
[  85.944037] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[  85.944038] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[  85.944038] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[  85.944038] Config <Info> common/settings.cpp:operator():33: Input_EnableTouch: true
[  85.944039] Config <Info> common/settings.cpp:operator():33: Input_EnableMouse: false
[  85.944039] Config <Info> common/settings.cpp:operator():33: Input_EnableKeyboard: false
[  85.944039] Config <Info> common/settings.cpp:operator():33: Input_EnableRingController: true
[  85.944039] Config <Info> common/settings.cpp:operator():33: Input_EnableIrSensor: false
[  85.944040] Config <Info> common/settings.cpp:operator():33: Input_EnableCustomJoycon: true
[  85.944040] Config <Info> common/settings.cpp:operator():33: Input_EnableCustomProController: false
[  85.944040] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false
[  86.113309] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:464: NVIDIA Drivers >= 510 do not support MSAA image blits
[  86.293369] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:157: Driver: NVIDIA 530.41.3.0
[  86.293372] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:158: Device: NVIDIA GeForce MX450
[  86.293373] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:159: Vulkan: 1.3.236
[  86.293378] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:160: Available VRAM: 1.07 GiB
[  86.303026] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:131: Patching ExeFS for title_id=010030301ABC2000
[  86.303105] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:178:     ExeFS: LayeredExeFS patches applied successfully
[  86.499404] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A
[  86.632267] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=CA00C73A820801BC9A31BFA926A0E199
[  86.669592] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=368F01D5CB42F06CD125DC739D036719700CB459
[  86.698903] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=8618895246B420329B77746B960A66ABCBEDE992
[  86.797775] Frontend <Info> yuzu/main.cpp:BootGame:1967: Booting game: 010030301ABC2000 | Hatsune Miku - The Planet Of Wonder And Fragments Of Wishes (64-bit) | 1.0.0
[  86.803321] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadVulkanPipelineCache:820: Loaded Vulkan driver pipeline cache: 
[  86.804259] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadDiskResources:517: Total Pipeline Count: 0
[  86.804324] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:763: Vulkan driver pipelines cached at: /home/emperor_penguin_of_japan/.local/share/yuzu/shader/010030301abc2000/vulkan_pipelines.bin
[  86.963669] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  86.973148] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  86.981124] Service.AM <Warning> core/hle/service/am/am.cpp:SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled:867: (STUBBED) called
[  86.982738] Service.AM <Warning> core/hle/service/am/am.cpp:GetGpuErrorDetectedSystemEvent:1825: (STUBBED) called
[  86.989225] Service.AM <Warning> core/hle/service/am/am.cpp:AcquireForegroundRights:93: (STUBBED) called
[  86.989595] Service.AM <Warning> core/hle/service/am/am.cpp:SetFocusHandlingMode:435: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[  86.989970] Service.AM <Warning> core/hle/service/am/am.cpp:SetOutOfFocusSuspendingEnabled:455: (STUBBED) called enabled=false
[  86.991921] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  86.995003] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  86.996363] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  86.998770] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  86.998859] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  87.216933] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  87.221671] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  87.257580] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:Initialize:153: (STUBBED) called
[  87.260242] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:SetAruid:193: (STUBBED) called, pid=0x87
[  87.261186] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:201: (STUBBED) called
[  87.265867] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetManagerDisplayService:460: (STUBBED) called
[  87.266649] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetSystemDisplayService:452: (STUBBED) called
[  87.269835] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetRelayService:444: (STUBBED) called
[  87.275288] Service.AM <Warning> core/hle/service/am/am.cpp:SetRestartMessageEnabled:443: (STUBBED) called
[  87.275408] Service.AM <Warning> core/hle/service/am/am.cpp:SetPerformanceModeChangedNotification:417: (STUBBED) called flag=true
[  87.275534] Service.AM <Warning> core/hle/service/am/am.cpp:SetOperationModeChangedNotification:407: (STUBBED) called flag=true
[  87.296275] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:422: Patching RomFS for title_id=010030301ABC2000, type=01
[  87.303024] Service.AM <Warning> core/hle/service/am/am.cpp:SetTerminateResult:1552: (STUBBED) called, result=0x00217202
[  87.303133] Debug.Emulated <Critical> core/hle/kernel/svc/svc_exception.cpp:Break:50: Userspace PANIC! info1=0x000000100D103A38, info2=0x0000000000000004
[  87.303136] Debug.Emulated <Critical> core/hle/kernel/svc/svc_exception.cpp:operator():32: debug_buffer_err_code=217202
[  87.303138] Debug.Emulated <Critical> core/hle/kernel/svc/svc_exception.cpp:Break:98: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100D103A38, info2=0x0000000000000004
[  87.303140] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:82: Backtrace, sp=000000100D103860, pc=000000000C302498
[  87.303142] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:83: Module Name         Address             Original Address    Offset              Symbol
[  87.303143] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:85: 
[  87.355408] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 0000007100158498    000000000C302498    0000000000158498    
[  87.355413] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 0000007100091718    000000000C23B718    0000000000091718    nn::diag::detail::Abort(nn::Result const*)
[  87.355414] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 000000710008FD80    000000000C239D80    000000000008FD80    
[  87.355415] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 000000710008FE48    000000000C239E48    000000000008FE48    
[  87.355416] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 000000710008FF28    000000000C239F28    000000000008FF28    
[  87.355417] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 00000071000D2D14    000000000C27CD14    00000000000D2D14    nn::fs::MountRom(char const*, void*, unsigned long)
[  87.355418] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: main                000000710067E264    0000000008682264    000000000067E264    nnMain
[  87.355419] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: sdk                 00000071000FA0B4    000000000C2A40B4    00000000000FA0B4    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
[  87.355420] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:89: rtld                00000071000000D4    00000000080000D4    00000000000000D4    

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | AVX512 | FMA | Threads: 8 | Cores: 4
GPU/Driver: NVIDIA GeForce MX450 | NVIDIA 530.41.3.0 | Vulkan: 1.3.236
RAM: 31.04 GiB
VRAM: 1.07 GiB
OS: Ubuntu 23.04 [x86_64, Kernel 6.2.0-20-generic, KDE Plasma 5.27.4]

### LINKED ISSUE #10906: Everdream valley doesn't boot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Android

### Description of Issue

Game doesn't boot. I tried all latest drivers and latest key

### Expected Behavior

It should boot tho

### Reproduction Steps

-

### Log File

[   0.005736] Frontend <Info> main/jni/native.cpp:RunEmulation:508: starting
[   0.006066] Config <Info> main/jni/config.cpp:LoadINI:46: Successfully loaded /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config/config.ini
[   0.006188] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:58: initializing
[   0.006303] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.006313] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.006685] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.006841] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.006962] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007080] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007200] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007330] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007751] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007875] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007996] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008124] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.348027] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:444:     RomFS: Update (v0.1.0) applied successfully
[   0.399661] Render.Vulkan <Error> video_core/vulkan_common/vulkan_instance.cpp:operator():121: Layer VK_LAYER_KHRONOS_validation not available, removing it
[   0.403170] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:802: Device doesn't support extension VK_EXT_conservative_rasterization
[   0.403184] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:802: Device doesn't support extension VK_EXT_depth_range_unrestricted
[   0.403187] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:802: Device doesn't support extension VK_NV_geometry_shader_passthrough
[   0.403189] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:802: Device doesn't support extension VK_NV_viewport_array2
[   0.403190] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:802: Device doesn't support extension VK_NV_viewport_swizzle
[   0.403196] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:864: Device doesn't support feature shaderInt8
[   0.403197] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Missing required feature uniformAndStorageBuffer16BitAccess
[   0.403198] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Missing required feature storageBuffer8BitAccess
[   0.403198] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Missing required feature uniformAndStorageBuffer8BitAccess
[   0.403199] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Missing required feature wideLines
[   0.403207] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:350: Unsuitable driver, continuing anyway
[   0.403312] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:397: Qualcomm and Turnip drivers have broken VK_EXT_custom_border_color
[   0.703779] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_debug_callback.cpp:DebugUtilCallback:57: SPIR-V offset 36: SPIR-V WARNING:
    Unsupported SPIR-V capability: SpvCapabilityUniformAndStorageBuffer8BitAccess (4449)
    36 bytes into the SPIR-V binary
[   0.718162] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:173: Driver: turnip Mesa driver 23.0.99
[   0.718183] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:174: Device: Turnip Adreno (TM) 650
[   0.718184] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:175: Vulkan: 1.3.241
[   0.718195] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:176: Available VRAM: 4.00 GiB
[   0.718310] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[   0.718704] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[   0.743510] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:131: Patching ExeFS for title_id=0100B9801AA3C000
[   0.744083] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:147:     ExeFS: Update (v0.1.0) applied successfully
[   0.744205] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:178:     ExeFS: LayeredExeFS patches applied successfully
[   1.098784] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=E485424C432E44A86938AABF35D8277EBD208CB
[   1.346073] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=AA83CABA2EEEE04E0C220D26FA20053D
[   1.404156] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=75C83C09E25F9A4E60BD960815722E8663C3CB26
[   1.450832] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence for build_id=2587A39AC2547A780EC0E4B77E22AFAB5C30C3AD
[   1.628595] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadVulkanPipelineCache:824: Loaded Vulkan driver pipeline cache: 
[   1.628887] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadDiskResources:520: Total Pipeline Count: 0
[   1.630118] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:767: Vulkan driver pipelines cached at: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/shader/0100b9801aa3c000/vulkan_pipelines.bin
[   1.963855] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   1.980199] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   1.998599] Service.AM <Warning> core/hle/service/am/am.cpp:SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled:867: (STUBBED) called
[   2.002685] Service.AM <Warning> core/hle/service/am/am.cpp:GetGpuErrorDetectedSystemEvent:1825: (STUBBED) called
[   2.016541] Service.AM <Warning> core/hle/service/am/am.cpp:AcquireForegroundRights:93: (STUBBED) called
[   2.017809] Service.AM <Warning> core/hle/service/am/am.cpp:SetFocusHandlingMode:436: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[   2.019068] Service.AM <Warning> core/hle/service/am/am.cpp:SetOutOfFocusSuspendingEnabled:455: (STUBBED) called enabled=false
[   2.023020] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.030441] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.034087] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.039032] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.039552] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.442497] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.453628] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   2.496017] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:Initialize:153: (STUBBED) called
[   2.501038] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:SetAruid:193: (STUBBED) called, pid=0x87
[   2.502905] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:201: (STUBBED) called
[   2.511418] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetManagerDisplayService:460: (STUBBED) called
[   2.512828] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetSystemDisplayService:452: (STUBBED) called
[   2.513867] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetRelayService:444: (STUBBED) called
[   2.525925] Service.AM <Warning> core/hle/service/am/am.cpp:SetRestartMessageEnabled:443: (STUBBED) called
[   2.526699] Service.AM <Warning> core/hle/service/am/am.cpp:SetPerformanceModeChangedNotification:417: (STUBBED) called flag=true
[   2.527187] Service.AM <Warning> core/hle/service/am/am.cpp:SetOperationModeChangedNotification:407: (STUBBED) called flag=true
[   2.552505] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:422: Patching RomFS for title_id=0100B9801AA3C000, type=01
[   2.553775] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:444:     RomFS: Update (v0.1.0) applied successfully
[   2.572268] Service.AM <Warning> core/hle/service/am/am.cpp:SetTerminateResult:1552: (STUBBED) called, result=0x00217202
[   2.572632] Debug.Emulated <Critical> core/hle/kernel/svc/svc_exception.cpp:Break:51: Userspace PANIC! info1=0x000000100E103A28, info2=0x0000000000000004
[   2.572642] Debug.Emulated <Critical> core/hle/kernel/svc/svc_exception.cpp:operator():32: debug_buffer_err_code=217202
[   2.572647] Debug.Emulated <Critical> core/hle/kernel/svc/svc_exception.cpp:Break:101: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100E103A28, info2=0x0000000000000004
[   2.572650] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:137: Backtrace, sp=000000100E103870, pc=000000000D330B64
[   2.572656] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:139: Module Name         Address             Original Address    Offset              Symbol
[   2.572657] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:140: 
[   2.687852] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: sdk                 0000007100158B64    000000000D330B64    0000000000158B64    
[   2.687871] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: sdk                 000000710008F108    000000000D267108    000000000008F108    nn::diag::detail::Abort(nn::Result const*)
[   2.687873] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: sdk                 000000710008D8B8    000000000D2658B8    000000000008D8B8    
[   2.687875] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: sdk                 000000710008D97C    000000000D26597C    000000000008D97C    
[   2.687877] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: sdk                 00000071000D652C    000000000D2AE52C    00000000000D652C    nn::fs::MountRom(char const*, void*, unsigned long)
[   2.687879] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: main                0000007100369B7C    000000000836DB7C    0000000000369B7C    nnMain
[   2.687881] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: sdk                 00000071000FA414    000000000D2D2414    00000000000FA414    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
[   2.687883] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:144: rtld                00000071000000D4    00000000080000D4    00000000000000D4    
[ 154.592265] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:767: Vulkan driver pipelines cached at: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/shader/0100b9801aa3c000/vulkan_pipelines.bin
[ 155.950998] Debug <Critical> common/host_memory.cpp:operator():580: Assertion Failed!
[ 155.951030] Debug <Critical> common/host_memory.cpp:operator():465: Assertion Failed!
mmap failed: Out of memory

### System Configuration

GPU/Driver: Adreno 650
RAM: 8
OS: SD 870

### LINKED ISSUE #11139: Attempting to load an encrypted ROM without installed keys results in incorrect NCA2 header error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1504

### Description of Issue

For some users, if they don't follow the quickstart guide carefully enough, can wind up getting an error that implies that they somehow have an invalid rom, instead of just not being able to decrypt it.

image

The error indicated a header type that was not implemented in yuzu because it was a pre-switch-release NCA format, and isn't supported on released switches.

This error seems to be subject to a race condition. Building yuzu locally and running it, even without a debugger attached results in the expected error (as seen in the Expected Behavior section.)

### Expected Behavior

image

This error should be produced instead. For some people, under different conditions, this is the error they get when trying to reproduce the problem. When building locally, and running without a debugger attached, I get this. Using the mainline 1504 build off of the yuzu website, I get the NCA2 error instead.

### Reproduction Steps

- Get a build of yuzu off of the yuzu website.
- unzip it somewhere.
- Create a user folder inside it.
- Start yuzu. 
- Click through the missing keys and telemetry dialog boxes
- Use File->Load File to load a base game NSP.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12140136/yuzu_log.txt)

### System Configuration

CPU: i7-12700k
GPU/Driver: 3070ti, 31.0.15.3667 (7-12-2023)
RAM: 32GB
OS: Win11 22H2

### LINKED ISSUE #11166: Skullgirls update and Dlc won't load
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1507 / Early Accès 3780

### Description of Issue

The game launch normally but the update and Dlc not

### Expected Behavior

Tried on a single Xci file and tried with the update and the dlc installed in the nand and the vanilla game in nsp. Latest keys and firmware installed. The same files working well on my switch and on Ryujinx emulator.

### Reproduction Steps

Launch Skullgirls with latest update (1.0.6) and all the dlc installed in the nand. Only vanilla game launching

### Log File

/

### System Configuration

CPU: intel I5 9400F
GPU/Driver: Nvidia Gtx1650
RAM: 8go
OS: Windows 11

### LINKED ISSUE #11176: Oneshot World Machine Edition
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest Build

### Description of Issue

Previous versions of Yuzu Oneshot would appear in the GUI and hang upon attempting to load. In more recent versions the game no longer appears in the GUI and attempting to load the file will give a error about having improper keys.

### Expected Behavior

image
image
image
image

Upon loading the yuzu file the game will give a key error when proper keys are present. I own the game, I have run the game, I have dumped the keys myself. A similar issue by user Little_mac on the discord server has the exact same issue on Linux and has also dumped key's themself.

I would like to state, I am aware that the game is unable to run on yuzu and the developers have discussed that the emulator is not there yet. I am simply reporting this as an issue to GitHub as no one has done before, and pointing out unexpected behavior by the emulator.

### Reproduction Steps

1. Dump world machine edition
2. Run world machine edition with the latest keys dumped
3. Get an error

### Log File

https://cdn.discordapp.com/attachments/400106910231035904/1134572741517918208/yuzu_log.zip

### System Configuration

CPU: AMD Ryzen 7 3700X 8-Core
GPU/Driver: Nvidia RTX 3060
RAM: 32 gigs
OS: Windows 10 Pro

### LINKED ISSUE #11200: Double Dragon Gaiden: Rise of The Dragons Support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1513

### Description of Issue

The game file was added the correct way, but it does not show up.

### Expected Behavior

The game shows up and  runs well.

### Reproduction Steps

Add game file and open yuzu.Check if game shows up.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12226960/yuzu_log.txt)

### System Configuration

CPU:Intel i7 8700
GPU/Driver:AMD Vega 64 / 23.7.2
RAM:16GB
OS:Windows 11 22621.2070

### PR DESCRIPTION
**Pull request by liamwhite**
With the help of @FearlessTobi, this adds support for a bunch of previously-unimplemented NCA features (without being a complete replacement of the FS implementation). Most notably, it adds support for sparse and compressed NCAs, which have been steadily increasing in popularity over the past few years.

Fixes #11200
Fixes #11176
Fixes #11166
Fixes #11139
Fixes #10906
Fixes #10804
Fixes #10687
Fixes #10157
Fixes #10045
Fixes #10021
Fixes #9384
Fixes #8836
Fixes #7905
Fixes #7371

Note: this is not a replacement for the FS rewrite, which I still consider necessary due to the current state of the fs service emulation, and the difficulty in working with the frontend code. I expect everything here to be entirely superseded by the rewrite.

### CODE REVIEW

File: src/common/lz4_compression.cpp [hunk 1]
```diff
@@ -71,4 +71,10 @@ std::vector<u8> DecompressDataLZ4(std::span<const u8> compressed, std::size_t un
     return uncompressed;
 }
 
+int DecompressLZ4(void* dst, size_t dst_size, const void* src, size_t src_size) {
```
Comment (FearlessTobi) [inline src/common/lz4_compression.cpp:74]: maybe we should just fix whatever is wrong with our other Lz4 wrapper....

File: src/common/lz4_compression.h [hunk 2]
```diff
@@ -56,4 +56,6 @@ namespace Common::Compression {
 [[nodiscard]] std::vector<u8> DecompressDataLZ4(std::span<const u8> compressed,
                                                 std::size_t uncompressed_size);
 
+int DecompressLZ4(void* dst, size_t dst_size, const void* src, size_t src_size);
```
Comment (FearlessTobi) [inline src/common/lz4_compression.h:59]:
```suggestion
[[nodiscard]] int DecompressDataLZ4(void* dst, size_t dst_size, const void* src, size_t src_size);
```

File: src/core/file_sys/content_archive.cpp [hunk 3]
```diff
@@ -12,545 +12,110 @@
...
-                exefs = dirs.back();
-            else if (IsDirectoryLogoPartition(dirs.back()))
-                logo = dirs.back();
-        } else {
-            if (has_rights_id)
-                status = Loader::ResultStatus::ErrorIncorrectTitlekeyOrTitlekek;
-            else
-                status = Loader::ResultStatus::ErrorIncorrectKeyAreaKey;
-            return false;
+        // TODO: Is this correct??
```
Comment (FearlessTobi) [inline src/core/file_sys/content_archive.cpp:105]: i think we should actually verify this and remove the todo lol

File: src/core/file_sys/content_archive.cpp [hunk 4]
```diff
@@ -579,21 +144,26 @@ VirtualDir NCA::GetParentDirectory() const {
 }
 
 NCAContentType NCA::GetType() const {
-    return header.content_type;
+    u8 type = static_cast<u8>(reader->GetContentType());
+    return static_cast<NCAContentType>(type);
```
Comment (FearlessTobi) [inline src/core/file_sys/content_archive.cpp:148]: This doesn't seem like the ideal way to handle this

File: src/core/file_sys/content_archive.cpp [hunk 5]
```diff
@@ -579,21 +144,26 @@ VirtualDir NCA::GetParentDirectory() const {
...
 }
 
 u64 NCA::GetTitleId() const {
-    if (is_update || status == Loader::ResultStatus::ErrorMissingBKTRBaseRomFS)
-        return header.title_id | 0x800;
-    return header.title_id;
+    if (is_update) {
+        return reader->GetProgramId() | 0x800;
+    } else {
```
Comment (FearlessTobi) [inline src/core/file_sys/content_archive.cpp:154]: you can omit the else block here

File: src/common/lz4_compression.cpp (hunk 1 above)
Comment (liamwhite) [reply src/common/lz4_compression.cpp:74]: This is better, because it's not passing around an extra buffer for no reason.

File: src/core/file_sys/content_archive.cpp (hunk 3 above)
Comment (liamwhite) [reply src/core/file_sys/content_archive.cpp:105]: I checked and this is identical to the old implementation. The actual data we need is not part of the program NCA (it's part of the cmnt), so there is no point trying to check _here_ specificallyif it is an update.

File: src/common/alignment.h [hunk 6]
```diff
@@ -3,14 +3,15 @@
...
+#include <bit>
 #include <cstddef>
 #include <new>
 #include <type_traits>
 
 namespace Common {
 
 template <typename T>
-    requires std::is_unsigned_v<T>
+    requires std::is_integral_v<T>
```
Comment (liamwhite) [inline src/common/alignment.h:14]: These are not correct for signed integers and need to be fixed

**Comment by RUANRUI1995** [comment]
Nice

**Comment by StevensND** [comment]
Alternatively you can use [YANU](https://github.com/nozwock/yanu/releases/tag/0.10.1)  to fix this problem.

**Comment by liamwhite** [comment]
There is no reason to use yanu to do this anymore because this implements the code for all NCA types.

**Comment by StevensND** [comment]
Alternatively you can use [YANU](https://github.com/nozwock/yanu/releases/tag/0.10.1)  to fix this problem.

> There is no reason to use yanu to do this anymore because this implements the code for all NCA types.

I'm just adding information in case for some game this doesn't fix it or in case you make changes in the future. 

I know this problem has been around since May.

**Comment by MarcoEstevez** [comment]
Thanks for the fix!

Looking great, missing games are shown in the game list again

image

**Comment by MarcoEstevez** [comment]
But latest update on "The witcher 3" give me that error

image

**Comment by gidoly** [comment]
Witcher 3 update install correctly on my system

**Review by FernandoS27 — APPROVED** [review]

**Comment by FireBurn** [comment]
Hi I'm seeing issues loading TOTK on Android since this commit:

```
2d930e8203114332b04a5c49a780b06 is the first bad commit
commit 86f6b6b7b2d930e8203114332b04a5c49a780b06
Author: Liam <byteslice@airmail.cc>
Date:   Thu Aug 10 21:34:43 2023 -0400

    vfs: expand support for NCA reading
```

Full details at https://github.com/yuzu-emu/yuzu/issues/11351
