### PR TITLE
patch_manager: Adds check for disabled cheats to prevent them from being enabled

### LINKED ISSUE #3176: Unchecking cheats in the properties menu, not working.
When removing a cheat from the properties menu in yuzu the cheat will still get executed. 

image

### PR DESCRIPTION
**Pull request by Morph1984**
A check for disabled cheats was missing from patch_manager, this PR adds the check.

Fixes #3176

### CODE REVIEW

File: src/core/file_sys/patch_manager.cpp [hunk 1]
```diff
@@ -284,12 +284,16 @@ std::vector<Memory::CheatEntry> PatchManager::CreateCheatList(
...
     }
 
+    const auto& disabled = Settings::values.disabled_addons[title_id];
     auto patch_dirs = load_dir->GetSubdirectories();
     std::sort(patch_dirs.begin(), patch_dirs.end(),
               [](const VirtualDir& l, const VirtualDir& r) { return l->GetName() < r->GetName(); });
 
     std::vector<Memory::CheatEntry> out;
     for (const auto& subdir : patch_dirs) {
+        if (std::find(disabled.begin(), disabled.end(), subdir->GetName()) != disabled.end())
```
Comment (lioncash) [inline src/core/file_sys/patch_manager.cpp]:
```suggestion
        if (std::find(disabled.cbegin(), disabled.cend(), subdir->GetName()) != disabled.cend())
```

This should also be braced
