### PR TITLE
Manually robust on Maxwell and earlier

### LINKED ISSUE #8215: Crash Team Racing - graphical glitches when using Vulkan
When playing CTR nitro fueled under vulkan api, most characters and kart becomes glitched (characters and karts becomes huge and all over the place), doesn't happen in ogl, but ogl seems to have  a memory leak issue.

Tested on latest early acces version.

### PR DESCRIPTION
**Pull request by Kelebek1**
Unfortunately it seems like Maxwell and Pascal cards have broken robust support, or something else strange is happening in Yuzu preventing it from working correctly. Crash Team Racing Nitro Fueled uses wildly invalid buffer indexes (values like 0x3D00001C), and they should just return 0 with robust enabled on the device, but Maxwell seems to instead just % the index with the buffer size, or & it with at least 0x10000 or something, and is returning "valid" results even with large indexes. 0x3D00001C returns the same value as 0x1C. No bits above bit 16 affect the returned result, so 0x20000 and above.

This PR also changes the arithmetic shifts to logical, since we don't want negative indexes, which also affects CTR.

I feel like there's something else strange going on in our shaders or their setup, or in how we enable robust or something which is causing it to fail. Ryujinx doesn't seem to suffer this issue, and the load does return 0, though that may be coincidence or something to do with our 16k buffer size their 4k, not sure. If anyone wants to investigate further, please do.

This should close #8215 and #6731.

### CODE REVIEW

File: src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp [hunk 1]
```diff
@@ -111,16 +111,30 @@ Id GetCbuf(EmitContext& ctx, Id result_type, Id UniformDefinitions::*member_ptr,
...
+        return val;
+    }
+    std::array<Id, 4> const_vec{
+        ctx.Const(0.0f),
+        ctx.Const(0.0f),
+        ctx.Const(0.0f),
+        ctx.Const(0.0f),
+    };
+    const Id cond = ctx.OpULessThanEqual(ctx.TypeBool(), buffer_offset, ctx.Const(0xFFFFu));
+    const Id zero = ctx.OpCompositeConstruct(result_type, std::span(const_vec));
```
Comment (liamwhite) [inline src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp:136]: This will always construct a 4-element composite, but the pointer type may not be a 4-element composite, which will give a shader validation error.

Comment (Kelebek1) [reply src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp:136]: > This will always construct a 4-element composite, but the pointer type may not be a 4-element composite, which will give a shader validation error.

In the shaders it always made a uvec2, which is the result type. How else do I do it?

Comment (liamwhite) [reply src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp:136]: It made a uvec2 in the spirv asm? Are you sure?

Comment (Kelebek1) [reply src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp:136]: > It made a uvec2 in the spirv asm? Are you sure?

Seems to
>         %917 = OpULessThan %u1 %914 %u32_65535
        %918 = OpCompositeConstruct %u32x2 %f32_0 %f32_0 %f32_0 %f32_0
        %919 = OpSelect %u32x2 %917 %916 %918

Comment (liamwhite) [reply src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp:136]: It used the correct type but provided too many arguments, which won't pass spirv-val

**Review by liamwhite — APPROVED** [review]

**Comment by cjunisl** [comment]
Yuzu EA 3940 - GTX 1050

ctr ea 3940

**Comment by wesmoen** [comment]
Had some luck by opening the game without configuration. Looks like the issue is fixed on a GTX970. 

image

image

**Comment by liamwhite** [comment]
@Kelebek1 this check should be done on pascal as well, I believe

**Comment by cjunisl** [comment]
yuzu 1597
GTX 1050

Unfortunately, it doesn't seem to have been fixed on Pascal. 
 
image

There is also an audio bug as reported in #10026
