### PR TITLE
submission_package: Fix updates integrated into cartridge images.

### LINKED ISSUE #4693: [EA 971+] Mario Kart 8 Deluxe - update/version 1.7.1 not recognized anymore [xci file]
I ran some tests on different EA and mainline builds and came across the mentioned issue.

- using base game and update combined in a xci file
- the issue does not occur with mainline 384 build
- the issue started to occur in EA 971
- tested a few other games like Mario Tennis Aces, Super Mario Odyssey, Animal Crossing NH, Panzer Dragoon Remake and Mario & Sonic at the Olympic Games Tokyo 2020, which all have updates and base game inside xci files. None of the games suffered from that issue

### PR DESCRIPTION
**Pull request by Morph1984**
Fixes #4693

The previous PR #4675 had a flaw which did not account for updates integrated into cartridge images (XCIs). This PR aims to solve this by adding explicit checks for multi-content / multi-program data.

### CODE REVIEW

File: src/core/file_sys/submission_package.cpp [hunk 1]
```diff
@@ -286,12 +286,31 @@ void NSP::ReadNCAs(const std::vector<VirtualFile>& files) {
...
-                     (next_nca->GetTitleId() & 0x800) != 0)) {
+
+                if (next_nca->GetStatus() != Loader::ResultStatus::Success &&
+                    next_nca->GetStatus() != Loader::ResultStatus::ErrorMissingBKTRBaseRomFS) {
+                    continue;
+                }
+
+                // If the last 3 hexadecimal digits of the CNMT TitleID is 0x800 or is missing the
+                // BKTRBaseRomFS, this is an update NCA. Otherwise, this is a base NCA.
+                if ((cnmt.GetTitleID() & 0x800) == 0x800 ||
```
Comment (lioncash) [inline src/core/file_sys/submission_package.cpp:301]:
```suggestion
                if ((cnmt.GetTitleID() & 0x800) != 0 ||
```

Is a more idiomatic way to perform a bit test

File: src/core/file_sys/submission_package.cpp [hunk 2]
```diff
@@ -286,12 +286,31 @@ void NSP::ReadNCAs(const std::vector<VirtualFile>& files) {
...
+                    next_nca->GetStatus() == Loader::ResultStatus::ErrorMissingBKTRBaseRomFS) {
+                    // If the last 3 hexadecimal digits of the NCA's TitleID is between 0x1 and
+                    // 0x7FF, this is a multi-program update NCA. Otherwise, this is a regular
+                    // update NCA.
+                    if ((next_nca->GetTitleId() & 0x7FF) != 0 &&
+                        (next_nca->GetTitleId() & 0x800) != 0x800) {
```
Comment (lioncash) [inline src/core/file_sys/submission_package.cpp:307]: Ditto here as well

**Review by bunnei — APPROVED** [review]
