### PR TITLE
Project Eleuthia - On-Screen Keyboard and Error Applet Overlays

### LINKED ISSUE #5813: Monster Hunter XXGU does not pop up the name input box
This game requires the player to enter a name for the character when creating a character, but Yuzu did not have any prompts, which caused the game to be unable to continue and stuck in a place. When a text box named for the character should pop up, I went as fast Pause the simulator and back up the Log file
Since it is not a graphic problem, I don’t think there is a need for screenshots?
[yuzu_log - Monster Hunter XX GU.zip](https://github.com/yuzu-emu/yuzu/files/5862904/yuzu_log.-.Monster.Hunter.XX.GU.zip)

### LINKED ISSUE #5958: UNIMPLEMENTED_MSG triggered by SoftwareKeyboard in Super Mario 3D World, after selecting character
After trying to play SM3DW on the latest release and failing to do so I've build Yuzu from the master branch and tried again. 

In both cases the game exits without a message after selecting SM3DW, pressing A, selecting a character and press A again. 

After this I did a debug run which hit a breakpoint showing the code that failed:

```cpp
software_keyboard.cpp at line 134 
// actually I believe it is the lambda UNIMPLEMENTED_MSG called on this line that calls exit
```

I just commented the line above to see what would happen and it actually fixed the problem. 

Not sure what is supposed to happen, but my system just silently quits Yuzu and it would be nice IMO if it showed an alert and allowed me to continue.

### LINKED ISSUE #6032: Unhandled keyboard requests in Gnosia
**Yuzu Version:** EA 1486, HEAD-0ad2ee45e
**Graphics API:** OpenGL
**Game:** GNOSIA 1.0.1 (01008EF013A7C000)

**Reproduction Steps:**
1. Select New Game
2. Select save slot and confirm
3. Navigate to character name input box and press confirmation button
4. Game waits for keyboard input but no keyboard is displayed; unable to back out

01008ef013a7c000_2021-03-04_13-32-00-067

**Log:**
`[ 534.229321] Service.AM <Warning> core\hle\service\am\am.cpp:GetLibraryAppletLaunchableEvent:375: (STUBBED) called
[ 534.231631] Service.AM <Warning> core\hle\service\am\am.cpp:GetIndirectLayerConsumerHandle:1007: (STUBBED) called
[ 534.260569] Debug <Critical> core\hle\service\am\applets\software_keyboard.cpp:ExecuteInteractive:134: Assertion Failed! Request D is not implemented
[ 534.261171] Debug <Critical> core\hle\service\am\applets\software_keyboard.cpp:ExecuteInteractive:134: Assertion Failed! Request E is not implemented
[ 534.281802] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlClearEventWait:191: cleared event wait on, event_id: 0
[ 534.283364] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlClearEventWait:191: cleared event wait on, event_id: 0
[ 534.284968] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlClearEventWait:191: cleared event wait on, event_id: 0
[ 534.321721] Service.AM <Error> core\hle\service\am\am.cpp:PopInteractiveOutData:979: storage is a nullptr. There is no data in the current interactive channel`

**Comment:**
Not sure what's special in this game as the keyboard overlay looks pretty standard on my actual Switch console but I can see in the code for software_keyboard.cpp that these request types are indeed not implemented yet.

### LINKED ISSUE #6117: MONSTER HUNTER XX (JPN version) can't name new character.
I tried to get start a new save in the old monster hunter game I only got the japanese copy. You can't name the character however thus blocking progress. The screen just shows the limitations for the name but you can't enter anything, no yuzu textbox shows up. I have update 1.5.1 installed as an NSP. 
image

I disabled the patch and tried again and for a split second the UI changes but then it reverts back to the above screen and no name can be inserted either.
image

this is the Yuzu build I'm using.
image

### PR DESCRIPTION
**Pull request by Morph1984**
## Project Eleuthia - On-Screen Keyboard and Error Applet Overlays

I and @Its-Rei are back to collaborate on yet another project focused on improving the various emulated applets within yuzu.

What is Project Eleuthia you ask? It aims to introduce the very first overlay applets within yuzu - the On-Screen Keyboard (OSK) and Error Display.

### Why overlays?

Have you ever needed to enter a name within games such as Pokemon or Super Smash Bros. Ultimate and find that you can't use a controller to enter a name?
In our quest to emulate the various features of the Nintendo Switch, the software keyboard was the perfect feature to implement a controller-friendly overlay.

### What was wrong with the previous software keyboard?

In addition to it not supporting controller input, its base implementation does not properly support newer revisions of the software keyboard and the inline software keyboard - which is used by games such as Monster Hunter Generations Ultimate, Dark Souls Remastered, Daemon X Machina, et. al.

Collaborating with Rei, we managed to completely rewrite and revamp the software keyboard implementation to not only support new versions of the software keyboard, but also implement the inline software keyboard used by the aforementioned games along with the long requested controller input support. We achieved this by mimicking the Nintendo Switch's UI for the software keyboard with matching colors for the 3 themes we provide.

### Super Smash Bros. Ultimate - Line OSK

osk_ssbu_line_white

### Super Mario Maker 2 - Box OSK

osk_smm2_box_dark

### Pokemon Sword and Shield - Numeric Pad OSK

osk_swsh_num_midnight

### Text Check Error Dialog overlaid on top of the OSK

osk_ssbu_error_dark

### Here's the software keyboard in action in Pokemon Sword and Shield with controller input

https://user-images.githubusercontent.com/39850852/113447128-3ad8e500-93c7-11eb-97f2-d99f4aba597a.mp4

### Fully functional inline software keyboard in Monster Hunter Generations Ultimate - saves no longer needed

https://user-images.githubusercontent.com/39850852/113447306-93a87d80-93c7-11eb-8846-db9596ef190b.mp4

## Error Display Applet

In developing the OSK we quickly found another use for the overlays - the Error Applet. This also accepts controller input.

This applet may show when games have errors on unimplemented features, such as Pokemon Sword/Shield's Y-comm feature or Super Smash Bros. Ultimate's camera mode when taking a screenshot. This is what it looks like

### Pokemon Sword/Shield Y-comm Error

image

## Borderless Fullscreen mode

In addition to these overlays, we have added support for borderless fullscreen, which not only fixes presentation issues with the above overlays, but also lowers latency and greatly reduces screen tearing. This has been made the default setting.

If you encounter issues with this mode, you can swap to the previous exclusive fullscreen mode under `Configure > Graphics > Fullscreen Mode`

image

## There's more to come 👀 

This is the first of the overlays to be implemented in yuzu, expect more to come soon™

## Special Thanks/Mentions
I'd really like to thank @Its-Rei for his amazing work on replicating the UI

Fixes #5813, fixes #5958, fixes #6032, fixes #6117

### CODE REVIEW

File: src/core/hle/kernel/hle_ipc.h [hunk 1]
```diff
@@ -210,6 +210,14 @@ class HLERequestContext {
     /// Helper function to test whether the output buffer at buffer_index can be written
     bool CanWriteBuffer(std::size_t buffer_index = 0) const;
 
+    Handle GetCopyHandle(std::size_t index) {
```
Comment (lioncash) [inline src/core/hle/kernel/hle_ipc.h:213]: This and the function below can be const member functions

File: src/core/hle/service/am/applets/software_keyboard.cpp [hunk 2]
```diff
@@ -1,200 +1,1076 @@
...
+                    submitted_text.size() * sizeof(char16_t));
+    }
+
+    broker.PushNormalDataFromApplet(std::make_shared<IStorage>(system, std::move(out_data)));
+
+    ExitKeyboard();
+}
+
+void SoftwareKeyboard::SubmitForTextCheck(std::u16string submitted_text) {
+    current_text = submitted_text;
```
Comment (lioncash) [inline src/core/hle/service/am/applets/software_keyboard.cpp:369]: Shouldn't `current_text` be std::moved into and be used elsewhere in this function, given this function is taking `submitted_text` by value?

File: src/core/hle/service/am/applets/software_keyboard.cpp [hunk 3]
```diff
@@ -1,200 +1,1076 @@
...
+
+void SoftwareKeyboard::RequestSetMovedCursorV2Flag(const std::vector<u8>& request_data) {
+    LOG_DEBUG(Service_AM, "Processing Request: SetMovedCursorV2Flag");
+
+    ASSERT(request_data.size() == sizeof(SwkbdRequestCommand) + 1);
+
+    std::memcpy(&use_moved_cursor_v2, request_data.data() + sizeof(SwkbdRequestCommand), 1);
+}
+
+/// Inline Software Keyboard Replies
```
Comment (lioncash) [inline src/core/hle/service/am/applets/software_keyboard.cpp:761]:
```suggestion
// Inline Software Keyboard Replies
```

Otherwise this is a doxygen comment

File: src/core/hle/service/am/applets/software_keyboard.h [hunk 4]
```diff
@@ -70,17 +29,139 @@ class SoftwareKeyboard final : public Applet {
...
+    /// Signals the frontend to hide the inline software keyboard.
+    void HideInlineKeyboard();
+
+    /// Signals the frontend that the current inline keyboard text has changed.
+    void InlineTextChanged();
+
+    /// Signals both the frontend and application that the software keyboard is exiting.
+    void ExitKeyboard();
+
+    /// Inline Software Keyboard Requests
```
Comment (lioncash) [inline src/core/hle/service/am/applets/software_keyboard.h:108]:
```suggestion
    // Inline Software Keyboard Requests
```

File: src/core/hle/service/am/applets/software_keyboard.h [hunk 5]
```diff
@@ -70,17 +29,139 @@ class SoftwareKeyboard final : public Applet {
...
+    void RequestFinalize(const std::vector<u8>& request_data);
+    void RequestSetUserWordInfo(const std::vector<u8>& request_data);
+    void RequestSetCustomizeDic(const std::vector<u8>& request_data);
+    void RequestCalc(const std::vector<u8>& request_data);
+    void RequestSetCustomizedDictionaries(const std::vector<u8>& request_data);
+    void RequestUnsetCustomizedDictionaries(const std::vector<u8>& request_data);
+    void RequestSetChangedStringV2Flag(const std::vector<u8>& request_data);
+    void RequestSetMovedCursorV2Flag(const std::vector<u8>& request_data);
+
+    /// Inline Software Keyboard Replies
```
Comment (lioncash) [inline src/core/hle/service/am/applets/software_keyboard.h:119]:
```suggestion
    // Inline Software Keyboard Replies
```

File: src/core/hle/service/am/applets/software_keyboard_types.h [hunk 6]
```diff
@@ -0,0 +1,295 @@
...
+#include <array>
+
+#include "common/bit_field.h"
+#include "common/common_funcs.h"
+#include "common/common_types.h"
+#include "common/swap.h"
+
+namespace Service::AM::Applets {
+
+static constexpr std::size_t MAX_OK_TEXT_LENGTH = 8;
```
Comment (lioncash) [inline src/core/hle/service/am/applets/software_keyboard_types.h:16]: Static isn't necessary on these constants

**Comment by v1993** [comment]
Testing on Linux: works really well in windowed mode and with exclusive fullscreen (see #6135 for troubles with borderless). Blocking compositioning breaks transparency in error window as expected but it remains fully functional otherwise.

**Review by bunnei — APPROVED** [review]
