### PR TITLE
renderer_vulkan: add format fallbacks for R16G16B16_SFLOAT, R16G16B16_SSCALED, R8G8B8_SSCALED

### LINKED ISSUE #8653: Mario 3D All-Stars crashes for both Sunshine + Galaxy on Steam Deck via Yuzu
Title describes the problem. Essentially Sunshine and Galaxy both crash on the steam deck (in both desktop mode and gaming mode). Mario64 runs, although not very well. First concern is priority.

### Operating System info:
```
NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck
BUILD_ID=20220718.1
VERSION_ID=3.2
```

### Yuzu Version: 
[scm_rev](https://github.com/yuzu-emu/yuzu-mainline/commit/scm_rev) 

### Yuzu configuration:
Graphics API: Vulkan
resolution: 720p/1080p
CPU: Auto
AA: no AA

### Logs:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9193792/yuzu_log.txt)

Any help on figuring this out would be very much appreciated. From what I understand this game had already been crashing before but thanks to the hard work of the Yuzu team 3D All-Stars was functioning before. I've also seen videos of it working on the deck in other contexts so I'm not really sure what's happening. Thanks a whole bunch!

### LINKED ISSUE #8662: Xenoblade Chronicles 3 crashing on startup with Vulkan renderer
Happens shortly after boot. You are able to see first loading screen and hear some sounds but game crashes without reaching main screen. On subsequent launches game crashes during shader cache loading unless you delete it.

Build: Yuzu EA 2867

System Specs:
NVIDIA RTX 2080 Driver 516.79
AMD Ryzen 3700X
32GB RAM
Windows 11 Version 21H2

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9214812/yuzu_log.txt)

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #8662 (XC3 startup crash for AMD Windows users)
Fixes #8653

### CODE REVIEW

File: src/video_core/renderer_vulkan/maxwell_to_vk.cpp [hunk 1]
```diff
@@ -317,195 +317,274 @@ VkPrimitiveTopology PrimitiveTopology([[maybe_unused]] const Device& device,
     }
 }
 
-VkFormat VertexFormat(Maxwell::VertexAttribute::Type type, Maxwell::VertexAttribute::Size size) {
+VkFormat VertexFormat(const Device& device, Maxwell::VertexAttribute::Type type,
+                      Maxwell::VertexAttribute::Size size) {
+    auto format = VK_FORMAT_UNDEFINED;
+
```
Comment (Morph1984) [inline src/video_core/renderer_vulkan/maxwell_to_vk.cpp:323]: perhaps a lambda and have the default case return VK_FORMAT_UNDEFINED

**Review by Morph1984 — APPROVED** [review]

**Review by bunnei — APPROVED** [review]
