### PR TITLE
vulkan_device: fix missing format in ANV

### LINKED ISSUE #6958: [Iris Xe][Mesa][ANV][Vulkan] Bowsers Fury - Crash after selecting Bowsers Fury
Game:Bowsers Fury - Crash after selecting Bowsers Fury
Yuzu Version : EA 2031
CPU : i7 1165G7
RAM : 16GB
GPU : Iris Xe
GPU Driver : Mesa 21.2.1
OS: Debian 11
Kernel : 5.13.13-xanmod1

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7103156/yuzu_log.txt)

### PR DESCRIPTION
**Pull request by voidanix**
Currently Mesa's ANV driver [does not support VK_FORMAT_B5G6R5_UNORM_PACK16](https://gitlab.freedesktop.org/mesa/mesa/-/blob/21.3/src/intel/vulkan/anv_formats.c#L152) which results in a crash; implement an alternative for it.

Fixes #6958 and part of #7023

### CODE REVIEW

**Comment by FernandoS27** [comment]
hmn, it's a good solution even though I would have preffered that ANV got that format back n track as the official driver supports.

Considering the alternative format is not hard to emulate. This is good enough.

**Review by FernandoS27 — APPROVED** [review]

**Comment by voidanix** [comment]
There seems to be more than one format working, currently testing and will add them soon

File: src/video_core/vulkan_common/vulkan_device.cpp [hunk 1]
```diff
@@ -39,6 +39,14 @@ constexpr std::array DEPTH16_UNORM_STENCIL8_UINT{
     VK_FORMAT_D32_SFLOAT_S8_UINT,
     VK_FORMAT_UNDEFINED,
 };
+
+constexpr std::array B5G6R5_UNORM_PACK16{
+    VK_FORMAT_R5G6B5_UNORM_PACK16,
+    VK_FORMAT_R5G5B5A1_UNORM_PACK16,
+    VK_FORMAT_A1R5G5B5_UNORM_PACK16,
+    VK_FORMAT_R4G4B4A4_UNORM_PACK16,
```
Comment (FernandoS27) [inline src/video_core/vulkan_common/vulkan_device.cpp:47]: this 3 are not good alternatives

**Comment by voidanix** [comment]
Thanks for the link :)

btw thanks to MK8 Deluxe making it obvious, swizzling **is** required.

> this 3 are not good alternatives

yup, fixed by reverting to what it was like before.

It now seems to work correctly both on ANV and RADV, although sometimes swapBlueRed gets applied when it shouldn't for some reason.

File: src/video_core/renderer_vulkan/vk_texture_cache.cpp [hunk 2]
```diff
@@ -554,10 +554,16 @@ void CopyBufferToImage(vk::CommandBuffer cmdbuf, VkBuffer src_buffer, VkImage im
...
+[[nodiscard]] bool IsFormatFlipped(PixelFormat format, bool emulate_bgr) {
     switch (format) {
     case PixelFormat::A1B5G5R5_UNORM:
         return true;
+    case PixelFormat::B5G6R5_UNORM:
+        if (emulate_bgr) {
+            return true;
+        } else {
+            return false;
+        }
```
Comment (ameerj) [inline src/video_core/renderer_vulkan/vk_texture_cache.cpp:566]:
```suggestion
        return emulate_bgr;
```

**Review by ameerj — COMMENTED** [review]
I would also suggest renaming the instances of "emulate BGR" to "emulate BGR565" since the logic applies to that specific format only. Otherwise it could be misconstrued to apply to 32-bit BGR formats as well i.e. `B8G8R8A8`

**Comment by FernandoS27** [comment]
just that last snip and it's good to go.

**Review by bunnei — APPROVED** [review]
