### PR TITLE
[audout] Implement GetAudioOutPlayedSampleCount

### LINKED ISSUE #6503: Unimplemented Function - GetAudioOutPlayedSampleCount - Ninja Gaiden Sigma
All three Ninja Gaiden games seem to require this function. Sigma freezes after its 2nd splash screen due to missing this. It can be skipped, but there are several unskippable video scenes in gameplay which can also trigger this issue

Full Error:
Debug <Critical> core\hle\service\service.cpp:operator ():161: Assertion Failed!
Unknown / unimplemented function 'GetAudioOutPlayedSampleCount': port='IAudioOut' cmd_buf={[0]=0x6, [1]=0x8, [2]=0x0, [3]=0x0, [4]=0x49434653, [5]=0x1, [6]=0xA, [7]=0x0, [8]=0x49434653}

Log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6687735/yuzu_log.txt)

Tested on Early Access 1798/Mainline 665

### PR DESCRIPTION
**Pull request by Kelebek1**
Closes #6503.

### CODE REVIEW

File: src/audio_core/stream.h [hunk 1]
```diff
@@ -108,6 +113,7 @@ class Stream {
     u32 sample_rate;                  ///< Sample rate of the stream
     Format format;                    ///< Format of the stream
     float game_volume = 1.0f;         ///< The volume the game currently has set
+    u64 played_samples;               ///< The current played sample count
```
Comment (Morph1984) [inline src/audio_core/stream.h:116]: This should likely be moved below `sample_rate`

File: src/core/hle/service/audio/audout_u.cpp [hunk 2]
```diff
@@ -186,6 +186,14 @@ class IAudioOut final : public ServiceFramework<IAudioOut> {
         rb.Push(static_cast<u32>(stream->GetQueueSize()));
     }
 
+    void GetAudioOutPlayedSampleCount(Kernel::HLERequestContext& ctx) {
+        LOG_DEBUG(Service_Audio, "called");
+
+        IPC::ResponseBuilder rb{ctx, 4};
+        rb.Push(ResultSuccess);
+        rb.Push<u64>(stream->GetPlayedSampleCount());
```
Comment (Morph1984) [inline src/core/hle/service/audio/audout_u.cpp:194]: The <u64> template parameter here can be omitted (there are template specializations for base types + ResultCode)

File: src/audio_core/stream.h [hunk 3]
```diff
@@ -106,6 +111,7 @@ class Stream {
     [[nodiscard]] std::chrono::nanoseconds GetBufferReleaseNS(const Buffer& buffer) const;
 
     u32 sample_rate;                  ///< Sample rate of the stream
+    u64 played_samples;               ///< The current played sample count
```
Comment (lioncash) [inline src/audio_core/stream.h:114]:
```suggestion
    u64 played_samples{};               ///< The current played sample count
```

Otherwise uninitialized reads can (and do) take place inside of `PlayNextBuffer()`. It introduces a potential uninitialized read vector through the accessor function.

**Comment by lioncash** [comment]
The commit message description should also include a game that requires it, so the information is stored in the git repository, to make looking up required games easier, if a service function ever needs to be retested in the future.
