### PR TITLE
core: implement GetGaiStringErrorRequest, IContextRegistrar

### LINKED ISSUE #11131: Splatoon 3 | Endless loading screen | Service <Error> core\hle\service\sockets\bsd.cpp:PollImpl:562: File descriptor handle=0 is not allocated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3772

### Description of Issue

When I enable internet in Yuzu settings, Splatoon 3 always stucks at the first loading screen and there's a lot of error spamming in log (Service <Error> core\hle\service\sockets\bsd.cpp:PollImpl:562: File descriptor handle=0 is not allocated). That also turns log file size to >100MB after two minutes of waiting.

### Expected Behavior

I think when it gets fixed the game will be able to load a network interface with no problems just like Splatoon 2, where we can get Local Multiplayer working on Yuzu.

### Reproduction Steps

Just enable the network interface in Yuzu System Settings and you'll get that game stuck and error spamming too.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12136451/yuzu_log.txt)
After 110 seconds of waiting the log file turned 100 megabytes (!) because of the crazy continuous spamming of the "Service <Error> core\hle\service\sockets\bsd.cpp:PollImpl:562: File descriptor handle=0 is not allocated" line, so I removed most of that from log so I can easily send this.

### System Configuration

Vulkan
CPU: i5-12400F
GPU/Driver: GTX 1650 SUPER, 536.40
RAM: 2x16GB DDR4 3200
OS: Windows 11 Pro 22H2 (22621.1778)

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #11131

### CODE REVIEW

**Review by bunnei — APPROVED** [review]

File: src/core/hle/service/sockets/sockets_translate.cpp [hunk 1]
```diff
@@ -81,6 +81,44 @@ GetAddrInfoError Translate(Network::GetAddrInfoError error) {
     }
 }
 
+const char* Translate(GetAddrInfoError error) {
```
Comment (Tachi107) [inline src/core/hle/service/sockets/sockets_translate.cpp:84]: Can't [`gai_strerror()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/gai_strerror.html) be used instead? It is supported pretty much everywhere

Comment (liamwhite) [reply src/core/hle/service/sockets/sockets_translate.cpp:84]: The exact constants (as defined in bionic) and these exact strings should be used, is that guaranteed?

Comment (Tachi107) [reply src/core/hle/service/sockets/sockets_translate.cpp:84]: No, I believe it's not. I wasn't aware of the fact that these functions must match bionic, thanks for the info :)
