### PR TITLE
video_core: Fine tune maxwell drawing trigger mechanism

### LINKED ISSUE #9275: The Legend of Zelda: Breath of the Wild - Flickering of distant objects on update 1.0.0
Ever since Mainline 1211 there is an issue of distant objects flickering on the base game of The Legend of Zelda: Breath of the Wild (1.0.0). 

Broken (Mainline 1211 or newer)

https://user-images.githubusercontent.com/30736337/202873372-7237ab7e-35eb-4df6-abf1-835b83f93b34.mp4

Working (Mainline 1210 or older)

https://user-images.githubusercontent.com/30736337/202873383-723a321e-2ca3-4600-b9f0-491a134f7a02.mp4

This occurs on both Vulkan and OpenGL.
This issue has been reproduced on Ampere (RTX 3070) and Ada Lovelace (RTX 4090) testing on different architectures and vendors would be appreciated.
[Save file for quick reproduction](https://github.com/yuzu-emu/yuzu/files/10048042/01007EF00011E000.zip)

### PR DESCRIPTION
**Pull request by vonchenplus**
The order of the drawing commands is sometimes always a surprise and a more conservative strategy is currently used to optimise.

Fix #9275

### CODE REVIEW

File: src/video_core/engines/maxwell_3d.h [hunk 1]
```diff
@@ -3178,6 +3180,7 @@ class Maxwell3D final : public EngineInterface {
 
     std::array<bool, Regs::NUM_REGS> draw_command{};
     std::vector<u32> deferred_draw_method;
+    enum class DrawMode { General = 0, Instance, InlineIndex } draw_mode{};
```
Comment (lioncash) [inline src/video_core/engines/maxwell_3d.h:3183]: Generally we try to keep the definition of an enum separate from variable declarations

File: src/video_core/engines/maxwell_3d.cpp [hunk 2]
```diff
@@ -288,31 +289,58 @@ void Maxwell3D::CallMethod(u32 method, u32 method_argument, bool is_last_call) {
...
-            u32_to_u8(regs.inline_index_2x16.odd);
-        } else if (MAXWELL3D_REG_INDEX(inline_index_4x8.index0) == method) {
-            u32_to_u8(regs.inline_index_4x8.index0);
-            u32_to_u8(regs.inline_index_4x8.index1);
-            u32_to_u8(regs.inline_index_4x8.index2);
-            u32_to_u8(regs.inline_index_4x8.index3);
+        switch (method) {
+        case MAXWELL3D_REG_INDEX(draw.end):
+            switch (draw_mode) {
+            case DrawMode::General:
```
Comment (FernandoS27) [inline src/video_core/engines/maxwell_3d.cpp:308]: [[likely]]

File: src/video_core/engines/maxwell_3d.cpp [hunk 3]
```diff
@@ -288,31 +289,58 @@ void Maxwell3D::CallMethod(u32 method, u32 method_argument, bool is_last_call) {
...
-        } else if (MAXWELL3D_REG_INDEX(inline_index_2x16.even) == method) {
-            u32_to_u8(regs.inline_index_2x16.even);
-            u32_to_u8(regs.inline_index_2x16.odd);
-        } else if (MAXWELL3D_REG_INDEX(inline_index_4x8.index0) == method) {
-            u32_to_u8(regs.inline_index_4x8.index0);
-            u32_to_u8(regs.inline_index_4x8.index1);
-            u32_to_u8(regs.inline_index_4x8.index2);
-            u32_to_u8(regs.inline_index_4x8.index3);
+        switch (method) {
+        case MAXWELL3D_REG_INDEX(draw.end):
```
Comment (FernandoS27) [inline src/video_core/engines/maxwell_3d.cpp:306]: [[likely]]

**Review by liamwhite — APPROVED** [review]
