### PR TITLE
shaders: Fix warp instructions on 64-thread warp devices

### LINKED ISSUE #6911: [WINDOWS][AMD][VULKAN] Fire Emblem : Three Houses - Lighting graphical glitches - Yuzu 724
Hi, 

In Fire Emblem Three houses lighting produces square artifacts in Vulkan.
Choosing OpenGL doesn't not produce those glitches but lighting seems totally absent.
I use Yuzu 724 released today.

My hardware : 
Ryzen 5900x
AMD Radeon 6800 XT - AMD software 21.6.1 Recent fresh install
Ram 32 Gb
Windows 10 Pro 21H1

Original Switch screenshot : 

Cap_FETH_Switch

Vulkan screenshot : 

Cap_FETH_Vulkan

OpenGL screenshot : 

Cap_FETH_OpenGL

Vulkan Log : 

[yuzu_Vulkan_log.txt](https://github.com/yuzu-emu/yuzu/files/7027675/yuzu_Vulkan_log.txt)

Do not hesitate if you need more info.
Thanks for all the work.

### PR DESCRIPTION
**Pull request by ameerj**
AMD devices dispatch 64-thread warps, making emulating the Tegra warp instructions a bit of a challenge due the guest device using a 32-thread warp size. This requires us to divide a 64-thread warp to behave as two 32-thread warps, and forbids us from using the standard warp intrinsics in the high level API's which operate on the entire warp group.

Prior to #6585, most warp instructions simply ignored the upper 32 threads in a 64-thread warp. This obviously posed some accuracy issues. The shader decompiler rewrite aimed to better support these kinds of devices, but fell short. 

This PR aims to fix the warp instructions on 64-thread warp devices. Using the thread's invocation ID, it becomes clear if they are part of the lower or upper 32-thread group, and change the warp instruction to behave as two 32-thread group warps to emulate the guest behavior.

This most notably fixes shading in `Fire Emblem: Three Houses` on AMD devices.

### Pre Decompiler Rewrite 

feth_pre_hades

### Decompiler Rewrite 

010055d009f78000_2021-08-31_13-13-13-536 

### Fixed

010055d009f78000_2021-08-31_13-15-49-208

Fixes  #6911

### CODE REVIEW

File: src/video_core/renderer_vulkan/vk_pipeline_cache.cpp [hunk 1]
```diff
@@ -311,7 +311,8 @@ PipelineCache::PipelineCache(RasterizerVulkan& rasterizer_, Tegra::Engines::Maxw
         .support_derivative_control = true,
         .support_geometry_shader_passthrough = device.IsNvGeometryShaderPassthroughSupported(),
 
-        .warp_size_potentially_larger_than_guest = device.IsWarpSizePotentiallyBiggerThanGuest(),
+        .warp_size_potentially_larger_than_guest = device.IsWarpSizePotentiallyBiggerThanGuest() &&
+                                                   !device.IsExtSubgroupSizeControlSupported(),
```
Comment (FernandoS27) [inline src/video_core/renderer_vulkan/vk_pipeline_cache.cpp:315]: RDNA2 has this extension but does not allow forcing the subgroup to anasy size.

**Review by Morph1984 — APPROVED** [review]

**Comment by danilaml** [comment]
Doesn't the RDNA+ use/support 32-thread wavefront?

**Comment by ameerj** [comment]
@danilaml According to @FernandoS27 who owns an RDNA2 system, the Vulkan extension that allows the configuration of the workgroup size does not allow setting the workgroup size to 32 for any shader stages on RDNA2. It might only be supported on OpenCL, which doesn't help us.
