### PR TITLE
romfs: fix extraction of single-directory root

### LINKED ISSUE #8905: MONSTER HUNTER GENERATIONS ULTIMATE Using mod will cause you to be unable to enter the game
The mod file is not modified in any way, the source file is used directly. Drag into the mod loading folder, open the game and display the request to exit, select no, it will always be loaded

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9565599/yuzu_log.txt)

dump

load

exit

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #8905. I've also gone ahead and removed the RomFSExtractionType enum as it would have only ever been used in error...

### CODE REVIEW

File: src/core/file_sys/romfs.cpp [hunk 1]
```diff
@@ -113,27 +109,17 @@ VirtualDir ExtractRomFS(VirtualFile file, RomFSExtractionType type) {
...
-    if (type == RomFSExtractionType::SingleDiscard)
-        return out->GetSubdirectories().front();
+    ProcessDirectory(file, dir_offset, file_offset, header.data_offset, 0, root_container);
 
-    while (out->GetSubdirectories().size() == 1 && out->GetFiles().empty()) {
-        if (Common::ToLower(out->GetSubdirectories().front()->GetName()) == "data" &&
-            type == RomFSExtractionType::Truncated)
-            break;
-        out = out->GetSubdirectories().front();
+    if (auto root = root_container->GetSubdirectory(""); root) {
```
Comment (FearlessTobi) [inline src/core/file_sys/romfs.cpp:118]: Maybe we should add a method to just get the current directory?

**Review by FearlessTobi — APPROVED** [review]

File: src/core/file_sys/romfs.cpp (hunk 1 above)
Comment (liamwhite) [reply src/core/file_sys/romfs.cpp:118]: It's kind of a weird abstraction but the root directory of a romfs is not handled separately; its name is the empty string.
