### PR TITLE
Project Mjölnir: Part 3 - Controller Profiles and Vibration Rework

### LINKED ISSUE #3743: Unable to set Analog sticks properly using GC Adapter w/ controller.
When trying to play Smash Bros. Ultimate with a GC Adapter and a GC controller I have a problem trying to use the "Set Analog Sticks" option. For some reason after setting it up by moving the left joystick from horizontal to vertical and trying it in game, horizontal (left & right) moves on the menu up and down and i'm unable to move left and right.

I went head to training mode using a PS4 controller and with no surprise it worked perfectly. With the PS4 controller i could do precise movemnet like walking and dashing whenever i want, then i switched to the GC controller, only thing i could do was walking and i couldn't crouch or use the Tap Jump option.

The same things happens with the right stick.

Gamecube Controller layout after setting analog sticks:
image

PS4 controller layout after setting analog sticks:
image

Video using a PS4 controller, i can dash, walk and move precisly:
https://youtu.be/p6Ez5o7E06Y

Video with GC Controller/Adapter, notice how i sometimes fail to set the analog settings correctly because it's setting completly diffrent axis for no reason, can happen with the right stick too:
https://youtu.be/dfDNhzDKIy8

In the GC Controller video, you can notice sometimes i don't move at all, that's me trying to move the joysticks but it does nothing even though it shows the sticks are set.

GoldenX86 did tell me to try and use X360ce and set binds there and then try to set the analog sticks using that but i tried everything i could and it just made everything worse on my end.

I know it isn't an issue with the adapter nor my controller since Smash Wii U works perfectly on Cemu and dolphin works perfectly with the same set up. 
 
Hope this is something that can be fixed with ease, thanks for all your efforts!

### LINKED ISSUE #4738: Games where rumble does not work
This is a list to keep track of all know games where rumble does not work.

- **1-2 Switch**: Has multiple vibration at the same time

- **Fast RMX**: No rumble signals, uses ActivateVibrationDevice.
- **Xenoblade Definitive Edition**: No rumble signals.
- **Xenoblade 2**: No rumble signals.

- **Fire Emblem Three Houses**: Sends rumble signals with 0 strength for 1 player.
- **Pinball FX3**: Sends rumble signals with 0 strength for 8 players.
- **Star Wars Pinball**: Sends rumble signals with 0 strength for 8 players.

- **Streets of Rage 4**
- **Hollow Knight**

### LINKED ISSUE #4800: Important stutter caused by vibration fonction
Hi,

I suffer heavy stuttering since a few versions of Yuzu, it doesn't happen before...but now it's very annoying.

Latest working version for me are Yuzu 393:

https://www.youtube.com/watch?v=VtZiN2AG1Go

Since 394 stutter happen:

https://www.youtube.com/watch?v=KlXyhlVN3oo
-> The sound on video are wrong, but it work when playing (it's from shadowplay recording).

->Just checked rev.411 and it's worst :( 

Windows 10 x64 Pro[19041.572]
I78700k@4.7Ghz
32Gb DDR4 Gskill Trident Z RGB 3466Mhz@XMP3200Mhz
Gigabyte 2070 RTX 8G OC[456.71]
LOG:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5395756/yuzu_log.txt)

EDIT:
A user on discord solved my issue:
Must disable all vibration function on the controller tab, i unchecked motion too.

### LINKED ISSUE #4818: All rumble is directed to controller 0
Hi I'm on the latest EA build of Yuzu with a very nice new gui for setting up the controllers.
I'm using 4 xbox 360 controllers and they were mapped to 4 Pro Controllers by just selecting Xinput 0-3 for each tab.

Now they all 4 of them work correctly for each player.. but the rumbling from all 4 controllers are directed to the first one.
So player 1 gets the rumble effects from itself and the other 3 as well.

I'm running it on Windows 10 btw.

### LINKED ISSUE #4928: Yuzu not saving input devices
Whenever I choose an input device in the controls settings (doesn't matter if it's KBM or a controller) it always resets to the "Any" options, effectively making it impossible to bind controls and to use the emulator at all.

Video of the problem: https://i.imgur.com/AoMy7Pr.mp4

image

Specs:
GTX 1070
i7 7700K @ 5.1 GHz
16GB RAM
Windows 10 Pro x64

### PR DESCRIPTION
**Pull request by Morph1984**
# Project Mjölnir: Part 3 - Controller Profiles and Vibration Rework

This is the final part of a multipart rewrite to yuzu's HID (Human Interface Device) frontend and backend implementations.

Wrapping this up, we bring you the final part of Project Mjölnir with 2 big features - Controller Profiles and Vibration Rework, both requiring many other miscellaneous improvements to all aspects of HID in the frontend and backend.

## Controller Profiles

The placeholder since Part 1 of the input rewrite is no more! Controller Profiles are finally here!

profile

Due to the way input is handled in yuzu, we had to create a profile system that adapts the existing system to ensure maximum compatibility. As a result, controller profiles are formatted similarly to the `[Controls]` section of the `qt-config.ini` file.

Controller Profiles currently save the following data:

- Emulated Controller (Only Left and Right Joycons)
- Real Input Device used (engine/guid/port)
- All buttons
- All axes
- All vibration devices (auto-generated by yuzu)
- All motion devices (via the Motion 0 and 1 buttons)

Everything else, such as the docked/undocked state, vibration and motion enabled, per player vibration (enabled and strength modifier), player connection status are **NOT** saved the input profile.

Controller profiles are saved under `config/input` in the yuzu AppData directory or user directory for portable installations.

Profiles are loaded by clicking on the dropdown/combobox and selecting the desired profile as shown below.

load_profile

## Vibration Rework

After the [initial work on rumble done by german77](https://github.com/yuzu-emu/yuzu/pull/4291), there were a few games where rumble didn't work, and the implementation was incomplete, not supporting vibrations beyond the first connected player.

The Nintendo Switch has the capability to 1. Distinguish between left and right vibration devices or motors and 2. Vibrate them independently of one another. This poses a challenge for libraries like SDL, which do not expose these capabilities. Furthermore, sending these vibrations in quick succession would result into performance issues for some controllers, as evidenced by the various reports using the Xbox controllers.

In order to solve these issues, we had to look into how HID encodes the vibration device handle - a unique handle used to distinguish between different controllers.

After decoding the device handle, it consists of the following:

A u8 npad_type, a u8 npad_id, and finally, a u8 device_index

These are all the information needed to vibrate a vibration device/motor at the correct location.

Armed with this knowledge, we can implement more vibration related HID commands such as `InitializeVibrationDevice`, `GetVibrationDeviceInfo` and `IsVibrationDeviceMounted`, and properly implement commands such as `SendVibrationValue`, `SendVibrationValues` and `GetVibrationValue`.

By implementing these commands, we have fixed all the games that previously had issues with rumble or exhibit no rumble at all, such as Hollow Knight, Fire Emblem Three Houses, 1-2 Switch, Xenoblade Chronicles and many more.

This has also allowed us to implement per player vibrations - allowing for vibrations to be separated per player and per vibration device. This means that if you have single joycons connected via programs such as BetterJoy, you can select the "Any" input device, map both joycons to the left and right buttons/analogs/motions respectively, and both joycons will be able to vibrate! The process of "mapping" a vibration device is done automatically so there is no setup required!

We have also allowed for enabling/disabling vibrations per player, and controlling the vibration strengths for each, allowing for fine tuning of rumble to meet your needs.

Performance issues are also resolved by adding a few heuristics to reduce vibration state changes, and a toggle to enable/disable accurate vibrations, This toggle reduces the effective vibration rate - the rate at which vibrations are sent. By default this is set to disabled.

configure_vibration

Controllers that do not support vibration are automatically detected and will have their rumble capabilities disabled in the backend. Resulting in no vibrations sent to SDL/GCAdapter.

Keep in mind that all these changes to vibration required a significant overhaul to the rumble system. In order for vibrations to work, you must open the `Configure` window and click on `Ok` once to allow the vibration devices to be "mapped" properly.

## Misc. changes

There are many other improvements that streamlines the user experience, some of which are detailed below:

- Cleaned up many UI element sizes between all three themes - now button/combobox/spinbox sizes and spacing are more consistent
- The controller applet now auto-accepts a valid **singleplayer** configuration. Multiplayer configurations will still have to be manually accepted.
- Mouse clicks now register (only if touch is disabled under `Controls -> Advanced`)
- The Player 1 controller is automatically connected on boot if none are connected
- Testing period for motion is reduced to 5 seconds from 8
- Input devices no longer revert to "Any" and selecting an input device would properly block inputs from other input devices
- The "Defaults" button now restores the automapped bindings for the selected input device
- Rewrite and correct all input parameters in all HID service commands
- Per game configs are moved to `config/custom`
- Return of "Map Analog Stick" for manual mapping - fixes analog stick mapping for controllers without SDL_GameController bindings
- The input config in the controller applet is replaced by a button to create input profiles - this will be used in a future PR

This fixes #3743, fixes #4738, fixes #4800, fixes #4818 and fixes #4928

### CODE REVIEW

**Comment by v1993** [comment]
Looks great!

Quick testing reveals an issue: saving profile using "New", entering name and pressing Ok causes a crash with "Aborted" error. However, profile gets saved and can be used.

**Comment by Morph1984** [comment]
> Looks great!
> 
> Quick testing reveals an issue: saving profile using "New", entering name and pressing Ok causes a crash with "Aborted" error. However, profile gets saved and can be used.
> 
> Edit: another issue: In Kirby Fighters 2, select settings and select Rumble ON. After a short pulse (as expected), controller keeps vibrating slightly until closing Yuzu.

Is there a stack trace? I'd assume this is on linux right?

**Comment by v1993** [comment]
I'll make a debug build for a stack trace now. FYI, I'm using build with both EA and mainline patches applied.

Yet another issue: "enable accurate vibration" checkbox doesn't save (or load?) between launches.

**Comment by Morph1984** [comment]
> Yet another issue: "enable accurate vibration" checkbox doesn't save (or load?) between launches.

Oops, looks like I completely missed this one lol, I'll be addressing this one shortly

**Comment by v1993** [comment]
Here's a backtrace of crash above:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4af7859 in __GI_abort () at abort.c:79
#2  0x00007ffff4ece951 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff4eda47c in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff4eda4e7 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff4eda799 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff4ece562 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055555563eb7c in __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) (this=0x7fffffffb280, __n=93825054186481) at /usr/include/c++/10/ext/new_allocator.h:115
#8  0x000055555563e089 in std::allocator<char>::allocate(unsigned long) (__n=93825054186481, this=0x7fffffffb280) at /usr/include/c++/10/bits/allocator.h:173
#9  std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) (__a=..., __n=93825054186481) at /usr/include/c++/10/bits/alloc_traits.h:460
#10 0x000055555563dab3 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) (this=0x7fffffffb280, __capacity=@0x7fffffffb170: 93825054186480, __old_capacity=0)
    at /usr/include/c++/10/bits/basic_string.tcc:153
#11 0x000055555563e42a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag)
    (this=0x7fffffffb280, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0x555559069c31 "") at /usr/include/c++/10/bits/basic_string.tcc:219
#12 0x000055555563dd7a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*>(char*, char*, std::__false_type)
    (this=0x7fffffffb280, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0x555559069c31 "") at /usr/include/c++/10/bits/basic_string.h:247
#13 0x000055555563d5ef in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*)
    (this=0x7fffffffb280, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0x555559069c31 "") at /usr/include/c++/10/bits/basic_string.h:266
#14 0x000055555563cbd2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x7fffffffb280, __str="") at /usr/include/c++/10/bits/basic_string.h:451
#15 0x0000555555678aa2 in InputProfiles::GetInputProfileNames[abi:cxx11]() (this=0x555557b0dc80) at ../src/yuzu/configuration/input_profiles.cpp:35
#16 0x0000555555706af9 in ConfigureInputPlayer::UpdateInputProfiles() (this=0x55555873e230) at ../src/yuzu/configuration/configure_input_player.cpp:1202
#17 0x00005555556de985 in ConfigureInput::UpdateAllInputProfiles(unsigned long) (this=0x555557a90130, player_index=0) at ../src/yuzu/configuration/configure_input.cpp:270
#18 0x00005555556e67f1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<unsigned long>, void, void (ConfigureInput::*)(unsigned long)>::call(void (ConfigureInput::*)(unsigned long), ConfigureInput*, void**) (f=
    (void (ConfigureInput::*)(class ConfigureInput * const, unsigned long)) 0x5555556de922 <ConfigureInput::UpdateAllInputProfiles(unsigned long)>, o=0x555557a90130, arg=0x7fffffffb550)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#19 0x00005555556e6630 in QtPrivate::FunctionPointer<void (ConfigureInput::*)(unsigned long)>::call<QtPrivate::List<unsigned long>, void>(void (ConfigureInput::*)(unsigned long), ConfigureInput*, void**) (f=
    (void (ConfigureInput::*)(class ConfigureInput * const, unsigned long)) 0x5555556de922 <ConfigureInput::UpdateAllInputProfiles(unsigned long)>, o=0x555557a90130, arg=0x7fffffffb550)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#20 0x00005555556e640b in QtPrivate::QSlotObject<void (ConfigureInput::*)(unsigned long), QtPrivate::List<unsigned long>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x5555586f8830, r=0x555557a90130, a=0x7fffffffb550, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#21 0x00007ffff52c3458 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00005555556366de in ConfigureInputPlayer::RefreshInputProfiles(unsigned long) (this=0x5555586d18d0, _t1=0) at src/yuzu/yuzu_autogen/MTVOZBWLY6/moc_configure_input_player.cpp:191
#23 0x0000555555706130 in ConfigureInputPlayer::CreateProfile() (this=0x5555586d18d0) at ../src/yuzu/configuration/configure_input_player.cpp:1134
#24 0x0000555555723acf in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ConfigureInputPlayer::*)()>::call(void (ConfigureInputPlayer::*)(), ConfigureInputPlayer*, void**)
    (f=(void (ConfigureInputPlayer::*)(class ConfigureInputPlayer * const)) 0x555555705e44 <ConfigureInputPlayer::CreateProfile()>, o=0x5555586d18d0, arg=0x7fffffffb7d0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#25 0x00005555557225e3 in QtPrivate::FunctionPointer<void (ConfigureInputPlayer::*)()>::call<QtPrivate::List<>, void>(void (ConfigureInputPlayer::*)(), ConfigureInputPlayer*, void**)
    (f=(void (ConfigureInputPlayer::*)(class ConfigureInputPlayer * const)) 0x555555705e44 <ConfigureInputPlayer::CreateProfile()>, o=0x5555586d18d0, arg=0x7fffffffb7d0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#26 0x00005555557210a7 in QtPrivate::QSlotObject<void (ConfigureInputPlayer::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x555558739d70, r=0x5555586d18d0, a=0x7fffffffb7d0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#27 0x00007ffff52c3458 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff7b4f806 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff7b4fa2e in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff7b50e73 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff7b51035 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff7a9d2b6 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff7a5aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff7a64343 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff529793a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff7a63457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff7ab935d in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff7abc1ec in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff7a5aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007ffff7a640f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff529793a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff56807d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#43 0x00007ffff568210b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007ffff565c35b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#45 0x00007fffead4232e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#46 0x00007ffff39b2fbd in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff39b3240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff39b32e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff52ef565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007ffff52964db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007ffff7c5ec6d in QDialog::exec() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#52 0x00005555557cfe74 in GMainWindow::OnConfigure() (this=0x7fffffffd840) at ../src/yuzu/main.cpp:2248
#53 0x00005555556676d1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (GMainWindow::*)()>::call(void (GMainWindow::*)(), GMainWindow*, void**)
    (f=(void (GMainWindow::*)(class GMainWindow * const)) 0x5555557cfd76 <GMainWindow::OnConfigure()>, o=0x7fffffffd840, arg=0x7fffffffc850) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
--Type <RET> for more, q to quit, c to continue without paging--
#54 0x0000555555667073 in QtPrivate::FunctionPointer<void (GMainWindow::*)()>::call<QtPrivate::List<>, void>(void (GMainWindow::*)(), GMainWindow*, void**)
    (f=(void (GMainWindow::*)(class GMainWindow * const)) 0x5555557cfd76 <GMainWindow::OnConfigure()>, o=0x7fffffffd840, arg=0x7fffffffc850) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#55 0x0000555555666575 in QtPrivate::QSlotObject<void (GMainWindow::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x5555579d66d0, r=0x7fffffffd840, a=0x7fffffffc850, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#56 0x00007ffff52c3458 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007ffff7a543e6 in QAction::triggered(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007ffff7a56aa2 in QAction::activate(QAction::ActionEvent) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007ffff7bdcd12 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007ffff7be44ae in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007ffff7be54d2 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007ffff7a9d2b6 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007ffff7be7adb in QMenu::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007ffff7a5aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#65 0x00007ffff7a64343 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#66 0x00007ffff529793a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#67 0x00007ffff7a63457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#68 0x00007ffff7ab9ce4 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#69 0x00007ffff7abc1ec in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#70 0x00007ffff7a5aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#71 0x00007ffff7a640f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#72 0x00007ffff529793a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#73 0x00007ffff56807d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#74 0x00007ffff568210b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#75 0x00007ffff565c35b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#76 0x00007fffead4232e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#77 0x00007ffff39b2fbd in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#78 0x00007ffff39b3240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#79 0x00007ffff39b32e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#80 0x00007ffff52ef565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#81 0x00007ffff52964db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#82 0x00007ffff529e246 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#83 0x00005555557d664d in main(int, char**) (argc=1, argv=0x7fffffffdc78) at ../src/yuzu/main.cpp:2971
```

**Comment by Kewlan** [comment]
Very minor preferance:

`config/input` -> `config/input_profiles`
`config/custom` -> `config/custom_game_config` or something else that makes it clear what's custom

**Comment by Morph1984** [comment]
@v1993 Can you try building again? I pushed a potential fix

**Comment by german77** [comment]
It will be nice to sort the device profiles by name

**Comment by german77** [comment]
Turning off all controllers while playing on cave story will result in a crash.
```KernelBase.dll!00007ff869b01a52()
yuzu.exe!assert_noinline_call<`Service::AM::Applets::Controller::Initialize'::`44'::<lambda_9>>(const Service::AM::Applets::Controller::Initialize::__l44::<lambda_9> & fn) Line 28
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\common\assert.h(28)
yuzu.exe!Service::AM::Applets::Controller::Initialize() Line 107
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\hle\service\am\applets\controller.cpp(107)
yuzu.exe!Service::AM::ILibraryAppletAccessor::Start(Kernel::HLERequestContext & ctx) Line 906
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\hle\service\am\am.cpp(906)
[Inline Frame] yuzu.exe!Service::ServiceFrameworkBase::InvokeRequest(Kernel::HLERequestContext &) Line 161
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\hle\service\service.cpp(161)
yuzu.exe!Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::HLERequestContext & context) Line 185
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\hle\service\service.cpp(185)
yuzu.exe!Kernel::ServerSession::HandleDomainSyncRequest(Kernel::HLERequestContext & context) Line 137
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\hle\kernel\server_session.cpp(137)
yuzu.exe!Kernel::ServerSession::CompleteSyncRequest() Line 159
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\hle\kernel\server_session.cpp(159)
[External Code]
[Inline Frame] yuzu.exe!std::_Func_class<void,unsigned __int64,std::chrono::duration<__int64,std::ratio<1,1000000000>>>::operator()(unsigned __int64 <_Args_0>, std::chrono::duration<__int64,std::ratio<1,1000000000>> <_Args_1>) Line 951
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\functional(951)
yuzu.exe!Core::Timing::CoreTiming::Advance() Line 199
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\core_timing.cpp(199)
yuzu.exe!Core::Timing::CoreTiming::ThreadLoop() Line 221
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\core_timing.cpp(221)
yuzu.exe!Core::Timing::CoreTiming::ThreadEntry(Core::Timing::CoreTiming & instance) Line 52
	at C:\Users\fabian\Desktop\yuzu development\fork\morph\src\core\core_timing.cpp(52)
[External Code]
```

**Comment by v1993** [comment]
Crash when saving profile no longer happens. Thanks!

File: src/yuzu/configuration/input_profiles.cpp [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+            continue;
+        }
+
+        profile_names.push_back(profile_name);
+    }
+
+    return profile_names;
+}
+
+bool InputProfiles::IsProfileNameValid(std::string profile_name) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:46]:
```suggestion
bool InputProfiles::IsProfileNameValid(std::string_view profile_name) {
```

This function can also be static, since it doesn't depend on instance state.

File: src/yuzu/configuration/input_profiles.cpp [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+bool InputProfiles::SaveProfile(std::string profile_name, std::size_t player_index) {
+    if (!ProfileExistsInMap(profile_name)) {
+        return false;
+    }
+
+    map_profiles[profile_name]->SaveControlPlayerValue(player_index);
+    return true;
+}
+
+bool InputProfiles::ProfileExistsInMap(std::string profile_name) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:97]:
```suggestion
bool InputProfiles::ProfileExistsInMap(const std::string& profile_name) const {
```

File: src/yuzu/configuration/input_profiles.cpp [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+    const std::size_t index = filename.rfind('.');
+
+    if (index == std::string::npos) {
+        return false;
+    }
+
+    return filename.substr(index) == ".ini";
+}
+
+std::string InputProfiles::GetNameWithoutExtension(std::string filename) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:116]:
```suggestion
std::string InputProfiles::GetNameWithoutExtension(const std::string& filename) {
```

This can likely be a static function fully contained in the cpp file, given this doesn't depend on class state in any way.

File: src/yuzu/configuration/input_profiles.cpp [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+bool InputProfiles::ProfileExistsInMap(std::string profile_name) {
+    return map_profiles.find(profile_name) != map_profiles.end();
+}
+
+bool InputProfiles::ProfileExistsInFilesystem(std::string profile_name) {
+    return FS::Exists(fmt::format("{}input" DIR_SEP "{}.ini",
+                                  FS::GetUserPath(FS::UserPath::ConfigDir), profile_name));
+}
+
+bool InputProfiles::IsINI(std::string filename) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:106]:
```suggestion
bool InputProfiles::IsINI(std::string_view filename) {
```

This too can likely also be entirely contained within the cpp file since it doesn't depend on class state.

File: src/yuzu/configuration/input_profiles.cpp [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+
+    map_profiles[profile_name]->SaveControlPlayerValue(player_index);
+    return true;
+}
+
+bool InputProfiles::ProfileExistsInMap(std::string profile_name) {
+    return map_profiles.find(profile_name) != map_profiles.end();
+}
+
+bool InputProfiles::ProfileExistsInFilesystem(std::string profile_name) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:101]:
```suggestion
bool InputProfiles::ProfileExistsInFilesystem(std::string_view profile_name) {
```

This too can likely also be entirely contained within the cpp file since it doesn't depend on class state.

File: src/yuzu/configuration/input_profiles.cpp [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+    if (!ProfileExistsInFilesystem(profile_name)) {
+        map_profiles.erase(profile_name);
+        return false;
+    }
+
+    map_profiles[profile_name]->ReadControlPlayerValue(player_index);
+    return true;
+}
+
+bool InputProfiles::SaveProfile(std::string profile_name, std::size_t player_index) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:88]:
```suggestion
bool InputProfiles::SaveProfile(const std::string& profile_name, std::size_t player_index) {
```

File: src/yuzu/configuration/input_profiles.cpp [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+
+    if (!ProfileExistsInFilesystem(profile_name) ||
+        FS::Delete(map_profiles[profile_name]->GetConfigFilePath())) {
+        map_profiles.erase(profile_name);
+    }
+
+    return !ProfileExistsInMap(profile_name) && !ProfileExistsInFilesystem(profile_name);
+}
+
+bool InputProfiles::LoadProfile(std::string profile_name, std::size_t player_index) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:74]:
```suggestion
bool InputProfiles::LoadProfile(const std::string& profile_name, std::size_t player_index) {
```

File: src/yuzu/configuration/input_profiles.cpp [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+        return false;
+    }
+
+    map_profiles.insert_or_assign(
+        profile_name, std::make_unique<Config>(profile_name, Config::ConfigType::InputProfile));
+
+    return SaveProfile(profile_name, player_index);
+}
+
+bool InputProfiles::DeleteProfile(std::string profile_name) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:61]:
```suggestion
bool InputProfiles::DeleteProfile(const std::string& profile_name) {
```

File: src/yuzu/configuration/input_profiles.cpp [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+    }
+
+    return profile_names;
+}
+
+bool InputProfiles::IsProfileNameValid(std::string profile_name) {
+    return profile_name.find_first_of("<>:;\"/\\|,.!?*") == std::string::npos;
+}
+
+bool InputProfiles::CreateProfile(std::string profile_name, std::size_t player_index) {
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.cpp:50]:
```suggestion
bool InputProfiles::CreateProfile(const std::string& profile_name, std::size_t player_index) {
```

File: src/yuzu/configuration/input_profiles.h [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+#include <string>
+#include <unordered_map>
+
+#include "yuzu/configuration/config.h"
+
+class InputProfiles {
+
+public:
+    explicit InputProfiles();
+    ~InputProfiles() = default;
```
Comment (lioncash) [inline src/yuzu/configuration/input_profiles.h:16]: This should be defaulted in the cpp file.

The `#include "yuzu/configuration/config.h"` include can then be replaced with a forward declaration and be moved to the cpp file.

**Comment by FearlessTobi** [comment]
You should consider adding an option to rename a controller profile.

**Comment by shukenmg** [comment]
Does this include HD rumble or is that implemented in #4411 ?

**Comment by v1993** [comment]
@shukenmg What do you mean by HD rumble? On Switch side of things, everything is HD Rumble. As for outputting it, there is no standard way to do so on SDL (and underlying APIs it uses) so far, so #4411 works that around for some devices.

**Comment by Morph1984** [comment]
SDL is limited in that we can't vibrate individual motors, and we can't change the frequency of the vibrations.
Switch controllers make use of a Linear Resonant Actuator (LRA) where you can change both it's vibration frequency and amplitude

**Comment by shukenmg** [comment]
@v1993 Thanks, yeah, I meant about outputting HD rumble.
So if I understand correctly currently YUZU correctly outputs HD rumble to Switch controllers (JoyCons, Pro Controller) but does not output HD rumble to other types of controllers? Is that correct?

**Comment by v1993** [comment]
@shukenmg Not yet as for now, since only SDL (universal) and GC-controller specific backends are used. PR you linked would allow this once finished and merged, however.

@Morph1984 Wait, can't SDL vibrate two motors (well, actuators nowadays) separately? I'm pretty sure this can be done: https://wiki.libsdl.org/SDL_HapticLeftRight. Also, I think Linux driver for procon/joycons changes frequency as well as amplitude for vibrations.

**Comment by german77** [comment]
@v1993 The SDL function used actually vibrates the two motors separately. That's why we pass the low and high amplitude to the function https://rust-sdl2.github.io/rust-sdl2/sdl2_sys/fn.SDL_JoystickRumble.html

**Comment by v1993** [comment]
On topic of "Enable accurate vibrations":

* As I mentioned before, this setting is not saved between launches
* With it disabled, vibration doesn't simply feel inaccurate, it is actually possible to feel gaps in it
* I can't really observe any slowdown associated with this option (with SDL2 2.0.12, compiled manually)
* It seems like it gets applied once Ok is clicked in "Configure vibrations" window, as opposed to general settings window. Is this intended? I'm not fully sure that this is a good idea.

**Comment by shukenmg** [comment]
There seems to be a significant regression in the rumble during the AOC intro cutscene.
"Enable accurate vibrations" does not change anything regarding this issue.

**Comment by Morph1984** [comment]
> On topic of "Enable accurate vibrations":
> 
> * As I mentioned before, this setting is not saved between launches
> * With it disabled, vibration doesn't simply feel inaccurate, it is actually possible to feel gaps in it
> * I can't really observe any slowdown associated with this option (with SDL2 2.0.12, compiled manually)
> * It seems like it gets applied once Ok is clicked in "Configure vibrations" window, as opposed to general settings window. Is this intended? I'm not fully sure that this is a good idea.

- What enabling accurate vibrations simply does is remove the limit at which vibrations are sent, so instead of enforcing a 10ms delay between vibrations they are sent all the time. I suppose these are the gaps you describe (if you can feel a 10ms gap)
- The slowdown occurs on select controllers, like the xbox controller, so I had to introduce the setting,
- And on the last point, yes, they are applied once Ok is clicked in the window since they are a separate dialog window

**Comment by Morph1984** [comment]
@shukenmg Can you describe the regression?

**Comment by Morph1984** [comment]
I think I must clarify what I mean by individual motors.
Nintendo switch hardware has the LRAs that are not traditional vibration motors
These actuators are able to vibrate at a wide range of frequencies and amplitudes unlike traditional rotating mass vibrators found on other controllers.

Therefore, they are able to incorporate low and high amplitude rumble into 1 motor instead of requiring 2.

Since traditional controllers have separate low and high amplitude motors, we can't really replicate the experience of HD rumble with them
However, with switch controllers, the left and right actuators are identical, so this is what I meant by vibrating the actuators independently

**Comment by shukenmg** [comment]
@Morph1984 
Prior to this change (YUZU 422), the rumble during the intro cutscene was matching the video on screen with rumble at the right places and correct length.
After this change, the rumble would be intermittent not matching the cutscene and would rumble in spurts.

**Comment by Morph1984** [comment]
@shukenmg What controller are you using, I can't replicate your issue

**Comment by shukenmg** [comment]
@Morph1984 Switch Pro Controller

**Comment by shukenmg** [comment]
@Morph1984 
Even the rumble during the First tower rising cutscene is not playing.

**Comment by Morph1984** [comment]
@shukenmg Can you test this and upload the log file?
[mjolnirp3_debug.zip](https://github.com/yuzu-emu/yuzu/files/5472723/mjolnirp3_debug.zip)

**Comment by shukenmg** [comment]
@Morph1984 Sure!

**Comment by shukenmg** [comment]
@Morph1984 Here they are.
[yuzu_logAccurateOn.txt](https://github.com/yuzu-emu/yuzu/files/5472824/yuzu_logAccurateOn.txt)
[yuzu_log-AccurateOff.txt](https://github.com/yuzu-emu/yuzu/files/5472825/yuzu_log-AccurateOff.txt)

**Comment by Morph1984** [comment]
@shukenmg The logs show vibrations are being sent properly to SDL and that the vibrations are processed successfully. What program are you using for connecting the Pro Controller?

**Comment by shukenmg** [comment]
@Morph1984 I am using betterjoy.

**Comment by Morph1984** [comment]
Specifically, which version of betterjoy?

**Comment by shukenmg** [comment]
@Morph1984 I am using a custom build based on version 6.4b
Here it is:
[BetterJoy.zip](https://github.com/yuzu-emu/yuzu/files/5473340/BetterJoy.zip)

**Comment by Morph1984** [comment]
The way I have rumble set up is that rumble will only stop if it receives a 0 amplitude vibration. I've found out that betterjoy has a Rumble Period, so that may be the cause

**Comment by shukenmg** [comment]
@Morph1984 Ohhh, that would make sense.

**Comment by shukenmg** [comment]
@Morph1984 Well setting the Rumble period to 0 makes the rumble better, but now there's no variation in the rumble, it just rumbles at the same strength.

**Comment by Morph1984** [comment]
@shukenmg If they all rumble at the same strength, this would be an issue with betterjoy, and not my PR

**Comment by shukenmg** [comment]
@Morph1984 Ok, ill do some testing, thanks for your work.

By the way, what method do you use to connect your controllers to yuzu?

**Comment by shukenmg** [comment]
@Morph1984 
https://github.com/Davidobot/BetterJoy/pull/591#issue-514104363
This will fix the issue, it was BetterJoy's fault all along XD

**Comment by bunnei** [comment]
@Morph1984 untagging because this breaks a lot of things, apparently

**Comment by shukenmg** [comment]
@bunnei 
What stuff does this break?
The rumble?

**Comment by v1993** [comment]
@shukenmg Please note that it was tagged again since then

**Comment by shukenmg** [comment]
@v1993 Oh yeah, it was hidden, thanks.

**Comment by Banz99** [comment]
Would it be possible to connect the second (or more) controllers (using the already set default profile) via the controller applet and then closing it using only the first controller maybe using a specific button combo? Sometimes I play Hyrule Warriors via remote play on steam and needing the mouse just to press the few same buttons is pretty inconvenient.

**Review by bunnei — APPROVED** [review]
