### PR TITLE
pl_u: Fix read out of bounds

### LINKED ISSUE #5291: Crash when opening Web Applet
On linux (Fedora 33), after #5042 yuzu crashes when trying to open the Action Guide in SMO, or How To Play in SMBU.
Happens both when compiling with and without YUZU_USE_QT_WEB_ENGINE.
Reverting the merge commit stops the crash:
 - If compiling with YUZU_USE_QT_WEB_ENGINE the browser opens and works (I have no issues with inputs)
 - If compiling without, it immediatly gets back to the game (though i thought it was supposed to show a warning dialog, it doesn't)

### PR DESCRIPTION
**Pull request by aleasto**
Closes #5291 #5825 

Few things to note:
* Please verify that behaviour is unchanged on windows. On linux the web applet currently doesn't work anyways.
* I removed `transformed_font[1] = Common::swap32(transformed_font[1]) ^ KEY; // "re-encrypt" the size` cause I can only assume it was a wrong copy-paste from above.

* ~~Weirdly enough removing that line (or any transformed_font[x] = y line) makes the compiler warn with~~

  >   [1/5] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ns/pl_u.cpp.o
  >   ../src/core/hle/service/ns/pl_u.cpp: In function ‘void Service::NS::DecryptSharedFontToTTF(const std::vector&, std::vector&)’:
  >   ../src/core/hle/service/ns/pl_u.cpp:73:16: warning: ‘void* memcpy(void*, const void*, size_t)’ specified bound 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
 
  ~~False positive?~~

### CODE REVIEW

**Comment by aleasto** [comment]
@Morph1984 Hi, please review this patch

**Comment by ogniK5377** [comment]
Re-encrypting the key is correct behavior, the OOB issue seems to be the input size is too small, which should be investigated instead

**Comment by german77** [comment]
What do you think it will happen if transformed_font.size() is less than 2? Just a hint size() is an unsigned int

**Comment by aleasto** [comment]
> Re-encrypting the key is correct behavior, the OOB issue seems to be the input size is too small, which should be investigated instead

The first 2 ints were not copied back to the output array, so changing the second int doesn't matter. This is exporting to TTF which is probably why the author of this change skipped the first 2 bytes in the memcpy. Thus the line can be removed.
And no, the issue is not that input size is too small, the oob is on the input array (its transformed, rather, which shares the size)

> What do you think it will happen if transformed_font.size() is less than 2? Just a hint size() is an unsigned int
The memcpy already copies from transformed_font.data() + 2.
Great tone btw :+1:

**Comment by german77** [comment]
-2 in unsigned int can be 18446744073709551608 or 4294967294 depends if the system is 64 or 32 bits. I din't mean to sound rude. Just wanted to explain the compiler warning.

**Comment by aleasto** [comment]
> -2 in unsigned int can be 18446744073709551608 or 4294967294 depends if the system is 64 or 32 bits. I din't mean to sound rude. Just wanted to explain the compiler warning.

Ack.
I added size checks, could be turned into asserts at will but it's not technically fatal

File: src/core/hle/service/ns/pl_u.cpp [hunk 1]
```diff
@@ -65,13 +65,16 @@ static void DecryptSharedFont(const std::vector<u32>& input, Kernel::PhysicalMem
 void DecryptSharedFontToTTF(const std::vector<u32>& input, std::vector<u8>& output) {
     ASSERT_MSG(input[0] == EXPECTED_MAGIC, "Failed to derive key, unexpected magic number");
 
+    if (input.size() < 2)
```
Comment (lioncash) [inline src/core/hle/service/ns/pl_u.cpp:68]: We brace if statements, even if there's only one line that constitutes the "body" of it for consistency.

File: src/core/hle/service/ns/pl_u.cpp [hunk 2]
```diff
@@ -65,13 +65,17 @@ static void DecryptSharedFont(const std::vector<u32>& input, Kernel::PhysicalMem
 void DecryptSharedFontToTTF(const std::vector<u32>& input, std::vector<u8>& output) {
     ASSERT_MSG(input[0] == EXPECTED_MAGIC, "Failed to derive key, unexpected magic number");
 
+    if (input.size() < 2) {
+        return;
```
Comment (ogniK5377) [inline src/core/hle/service/ns/pl_u.cpp:69]: Add a LOG_ERROR print to indicate when this fails

**Comment by Morph1984** [comment]
@aleasto Thanks for the patch! I was about to verify the generated files but forgot to lol, will get to it soon

File: src/core/hle/service/ns/pl_u.cpp [hunk 3]
```diff
@@ -65,13 +65,18 @@ static void DecryptSharedFont(const std::vector<u32>& input, Kernel::PhysicalMem
 void DecryptSharedFontToTTF(const std::vector<u32>& input, std::vector<u8>& output) {
     ASSERT_MSG(input[0] == EXPECTED_MAGIC, "Failed to derive key, unexpected magic number");
 
+    if (input.size() < 2) {
+        LOG_ERROR(Common, "Input font is empty");
```
Comment (Morph1984) [inline src/core/hle/service/ns/pl_u.cpp:69]:
```suggestion
        LOG_ERROR(Service_NS, "Input font is empty");
```

**Review by Morph1984 — APPROVED** [review]
Generated fonts are verified to be correct, thank you!
