### PR TITLE
fsp-srv: add GetFileSystemAttribute

### LINKED ISSUE #11589: Tiny Thor - Freeze - unimplemented function '16': port='IFileSystem
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 2921a2426

### Description of Issue

Freezes at "GAMEFORGE" logo

### Expected Behavior

Continue

### Reproduction Steps

Start the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12718238/yuzu_log.txt)

### System Configuration

CPU: Tensor Core G2
GPU/Driver:
RAM: 12GB
OS: Android 14

### PR DESCRIPTION
**Pull request by liamwhite**
Likely fixes #11589

### CODE REVIEW

File: src/core/hle/service/filesystem/fsp_srv.cpp [hunk 1]
```diff
@@ -521,6 +522,43 @@ class IFileSystem final : public ServiceFramework<IFileSystem> {
...
+            s32 file_path_name_length_max;
+            INSERT_PADDING_WORDS_NOINIT(0x5);
+            s32 utf16_dir_entry_name_length_max;
+            s32 utf16_file_entry_name_length_max;
+            s32 utf16_dir_path_name_length_max;
+            s32 utf16_file_path_name_length_max;
+            INSERT_PADDING_WORDS_NOINIT(0x18);
+            INSERT_PADDING_WORDS_NOINIT(0x1);
+        };
+        static_assert(sizeof(FileSystemAttribute) == 0xc0);
```
Comment (FearlessTobi) [inline src/core/hle/service/filesystem/fsp_srv.cpp:549]: should have a message like "xyz has inccoret size"

File: src/core/hle/service/filesystem/fsp_srv.cpp [hunk 2]
```diff
@@ -521,6 +522,43 @@ class IFileSystem final : public ServiceFramework<IFileSystem> {
         rb.PushRaw(vfs_timestamp);
     }
 
+    void GetFileSystemAttribute(HLERequestContext& ctx) {
```
Comment (FearlessTobi) [inline src/core/hle/service/filesystem/fsp_srv.cpp:525]: missing a debug or warning log

**Review by FearlessTobi — APPROVED** [review]
