### PR TITLE
nvflinger: Remove superfluous buffer format check.

### LINKED ISSUE #233: Double Buffering not working
So I have been trying to work on a homebrew game for the nintendo switch, however I came across a problem. Whenever I try to flip or use double buffering on the graphics, it never works. However, when I open **singlebuffering.nro** in the examples the emulator seems to work just fine.

So there are a few ways to fix this:
1. Is double buffering enabled
2. How do i single buffer, since the source code isn't in the examples, its just **singlebuffering.nro**

### PR DESCRIPTION
**Pull request by bunnei**
Fixes #233

### CODE REVIEW

File: src/core/hle/service/nvflinger/buffer_queue.cpp [hunk 1]
```diff
@@ -36,9 +36,7 @@ u32 BufferQueue::DequeueBuffer(u32 pixel_format, u32 width, u32 height) {
             return false;
 
         // Make sure that the parameters match.
-        auto& igbp_buffer = buffer.igbp_buffer;
-        return igbp_buffer.format == pixel_format && igbp_buffer.width == width &&
-               igbp_buffer.height == height;
+        return buffer.igbp_buffer.width == width && buffer.igbp_buffer.height == height;
     });
     if (itr == queue.end()) {
         LOG_CRITICAL(Service_NVDRV, "no free buffers for pixel_format=%d, width=%d, height=%d",
```
Comment (Subv) [inline src/core/hle/service/nvflinger/buffer_queue.cpp]: Please remove this horrible hack while you're at it.

Comment (bunnei) [reply src/core/hle/service/nvflinger/buffer_queue.cpp]: Will fix next, tracking with bug #240
