### PR TITLE
Check all swizzle components for red, not just [0]

### LINKED ISSUE #9805: Story of seasons wonderful life visual glitch
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1154

### Description of Issue

There are there lines that appear everywhere at certain times of day in game. Its a universal glitch everyone who trys to run the game on yuzu experiences.

### Expected Behavior

4b4916c5e7a47384a5afbd7abc285b4c68dce928

### Reproduction Steps

it happens on title screen and when loading any part of the game. its worse indoors

### Log File

dont know how to get log file

### System Configuration

CPU:
GPU/Driver:nvidia 2070
RAM:8gigs
OS:windows

### PR DESCRIPTION
**Pull request by Kelebek1**
Third time's the charm? Thanks to @bylaws for helping out with this one.

Instead of only checking component[0] for red, check all components. Red and green usage here should be exclusive (as per ByLaws), swizzles should only contain either red or green and not both. If no red is found it's assumed green, but if there's no green either and all the components are either zero or one, then that should also be fine, since they'll return constants anyway it doesn't matter if it tries to pull from depth or stencil.

Closes #9805. Hopefully for the last time.

### CODE REVIEW

File: src/video_core/renderer_opengl/gl_texture_cache.cpp [hunk 1]
```diff
@@ -112,13 +112,17 @@ GLenum ImageTarget(Shader::TextureType type, int num_samples = 1) {
     return GL_NONE;
 }
 
-GLenum TextureMode(PixelFormat format, bool is_first) {
+GLenum TextureMode(PixelFormat format, std::span<SwizzleSource> swizzle) {
```
Comment (Morph1984) [inline src/video_core/renderer_opengl/gl_texture_cache.cpp:115]: Passing this small 4 byte array by copy is likely to be faster than passing a span
```suggestion
GLenum TextureMode(PixelFormat format, std::array<SwizzleSource, 4> swizzle) {
```

Comment (Kelebek1) [reply src/video_core/renderer_opengl/gl_texture_cache.cpp:115]: Should I just pass it by reference?

**Review by liamwhite — APPROVED** [review]
