### PR TITLE
Use safe reads in DMA engine

### LINKED ISSUE #10654: Cassette Beasts with video issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3644

### Description of Issue

The Cassette Beasts game does not start normally, it takes a while and when you go to the main screen it turns completely purple only with the A button on the screen
indicating that it has to be tight

### Expected Behavior

With normal colors without the screen turning completely purple

### Reproduction Steps

Just start the game and on the home screen it already has the problem

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11670864/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11670865/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD RYZEN 5 5600X
GPU/Driver: GEFORCE RTX 3060
RAM:16 GB
OS: WIN 10 PRO 64 BITS

### PR DESCRIPTION
**Pull request by Kelebek1**
Some OpenGL games use blits and then DMA to do the readback. Currently with unsafe reads we're not synchronising the memory and ending with undefined memory in the read. Needs a bit of testing to detemine any perf hits from this, but hopefully won't be noticable.

Closes #10654.

### CODE REVIEW

**Comment by gidoly** [comment]
1% loss at best

**Comment by liamwhite** [comment]
Needs a rebase

**Comment by FernandoS27** [comment]
This makes a lot of sense. We do not have acceleration for this but I don't think it will be necessary for the time being.

**Review by FernandoS27 — APPROVED** [review]

File: src/video_core/engines/maxwell_dma.cpp [hunk 1]
```diff
@@ -140,17 +140,17 @@ void MaxwellDMA::Launch() {
...
                         convert_linear_2_blocklinear_addr(regs.offset_out + offset),
                         tmp_buffer.data(), tmp_buffer.size());
                 }
             } else {
                 if (!accelerate.BufferCopy(regs.offset_in, regs.offset_out, regs.line_length_in)) {
                     std::vector<u8> tmp_buffer(regs.line_length_in);
-                    memory_manager.ReadBlockUnsafe(regs.offset_in, tmp_buffer.data(),
-                                                   regs.line_length_in);
+                    memory_manager.ReadBlock(regs.offset_in, tmp_buffer.data(),
+                                             regs.line_length_in);
```
Comment (FernandoS27) [inline src/video_core/engines/maxwell_dma.cpp:153]: this one should be unnecessary as the accelerate takes care if the memory is dirty
