### PR TITLE
Various heap fixes for libtransistor

### LINKED ISSUE #231: svcSetHeapSize cannot expand heap
**Commit used**: 5750f6f0466c84e0c5b832c00ab8260ea9ba0cd0
svcSetHeapSize is unable to adjust the size of the heap when blocks from the currently existing region have been remapped. Libtransistor's test_sdl encounters this behaviour. I'm not sure if this happens when the entire heap's memory state is clean.

### PR DESCRIPTION
**Pull request by bunnei**
* Fixes svcGetInfo to return the correct reserved heap/mapped region/new mapped region sizes
* Changes main thread stack memory state type from `Heap` to `Mapped`
* Moves stack memory to its own memory region
* Changes mirrored memory to use memory state `Mapped`

Fixes #231

### CODE REVIEW

File: src/core/hle/kernel/vm_manager.h [hunk 1]
```diff
@@ -41,15 +41,24 @@ enum class VMAPermission : u8 {
...
-    Free = 0,
-    IO = 1,
-    Normal = 2,
-    Code = 3,
-    Static = 4,
-    Heap = 5,
-    Shared = 6,
-    Mapped = 6,
-    ThreadLocalStorage = 12,
+    Unmapped = 0x0,
```
Comment (Subv) [inline src/core/hle/kernel/vm_manager.h]: Gotta change the string array in vm_manager.cpp too

Comment (bunnei) [reply src/core/hle/kernel/vm_manager.h]: Addressed

File: src/core/hle/kernel/process.cpp [hunk 2]
```diff
@@ -273,26 +275,36 @@ ResultCode Process::LinearFree(VAddr target, u32 size) {
 }
 
 ResultCode Process::MirrorMemory(VAddr dst_addr, VAddr src_addr, u64 size) {
-    auto vma = vm_manager.FindVMA(src_addr);
+    if (dst_addr == src_addr) {
```
Comment (misson20000) [inline src/core/hle/kernel/process.cpp]: Tested on hardware both when nothing was mapped at my address and when memory had already been remapped there, and svcMapMemory returned `0xd401` in both cases.

File: src/core/hle/kernel/vm_manager.cpp [hunk 3]
```diff
@@ -384,7 +401,8 @@ VAddr VMManager::GetMapRegionBaseAddr() {
 
 VAddr VMManager::GetNewMapRegionBaseAddr() {
     LOG_WARNING(Kernel, "(STUBBED) called");
-    return 0x8000000;
+    const u64 heap_size{Core::CurrentProcess()->heap_end - Core::CurrentProcess()->heap_start};
+    return Memory::HEAP_VADDR + heap_size;
```
Comment (misson20000) [inline src/core/hle/kernel/vm_manager.cpp]: This should not be adjacent to the heap; if the heap expands, the heap will expand over the region this returns, and it is its own distinct region anyways. I launched the browser 10 times and grabbed the address and sizes of the heap, the map region, and the "new" map region using svcGetInfo each time and they never overlapped. I know some of the regions look pretty close on this chart, but I checked and they're not overlapping.
asplot

heap region is red, always sized `0x180000000`

map region is blue, always sized `0x1000000000`

"new" map region is yellow, always sized `0x80000000`

File: src/core/hle/kernel/vm_manager.cpp [hunk 4]
```diff
@@ -18,8 +18,24 @@ namespace Kernel {
...
-        "Free",   "Reserved",   "IO",      "Static", "Code",      "Private",
-        "Shared", "Continuous", "Aliased", "Alias",  "AliasCode", "Locked",
+        "Unmapped ",
+        "Io",
+        "Normal",
+        "CodeStatic",
+        "CodeMutable",
+        "Heap",
+        "Shared",
+        "ModuleCodeStatic",
```
Comment (Subv) [inline src/core/hle/kernel/vm_manager.cpp]: Shared is 6 but ModuleCodeStatic is 8

File: src/core/hle/kernel/vm_manager.cpp [hunk 5]
```diff
@@ -18,8 +18,24 @@ namespace Kernel {
...
+        "ModuleCodeMutable",
+        "IpcBuffer0",
+        "Mapped",
+        "ThreadLocal",
+        "TransferMemoryIsolated",
+        "TransferMemory",
+        "ProcessMemory",
```
Comment (Subv) [inline src/core/hle/kernel/vm_manager.cpp]: ProcessMemory is 0xF but IpcBuffer1 is 0x11

**Comment by misson20000** [comment]
updated test case (build without libtransistor crt0 or anything for simplicity): [yuzu-231-r2.nro](https://xenotoad.net/yuzu-231-r2.nro), source code at [yuzu-231-r2.c](https://xenotoad.net/yuzu-231-r2.c)

File: src/core/hle/kernel/vm_manager.cpp (hunk 5 above)
Comment (bunnei) [reply src/core/hle/kernel/vm_manager.cpp]: Addressed
