### PR TITLE
general: Remove uncaught usages of C++ string number conversions

### LINKED ISSUE #11490: Yuzu crashes after launching it
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early access 3864

### Description of Issue

```bash
$ yuzu
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoll
[1]    47814 IOT instruction (core dumped)  yuzu
```

I tried to open yuzu from desktop but it crashed. Then I tried to launch it from the shell, and got the message above.

### Expected Behavior

Yuzu should start normally and graphical window should be seen.

### Reproduction Steps

Launch Yuzu normally

### Log File

No log files are generated.

### System Configuration

CPU: AMD Ryzen 9 7940H
GPU/Driver: AMD Radeon 780M / NVIDIA RTX 4060 Laptop
RAM: 16GB DDR5
OS: Arch Linux

### PR DESCRIPTION
**Pull request by lat9nq**
Closes #11490 

This began as the title states, but I also took time to forward-port any Settings improvements I've done in my quest to backport the Settings rework to Citra. Fixes occasional issues with the application crashing due to a type of an exception not being caught. Adds some float support to Settings and shared_widget.

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

File: src/common/settings_common.h [hunk 1]
```diff
@@ -225,6 +225,16 @@ class BasicSetting {
      */
     [[nodiscard]] virtual constexpr u32 EnumIndex() const = 0;
 
+    /**
+     * @returns True if the underlying type is a floating point storage
+     */
+    [[nodiscard]] virtual constexpr bool IsFloatingPoint() const = 0;
+
+    /**
+     * @returns True if the underlying type is a integer storage
```
Comment (FearlessTobi) [inline src/common/settings_common.h:234]:
```suggestion
     * @returns True if the underlying type is an integer storage
```

File: src/yuzu/configuration/shared_widget.cpp [hunk 2]
```diff
@@ -255,6 +255,58 @@ QWidget* Widget::CreateLineEdit(std::function<std::string()>& serializer,
     return line_edit;
 }
 
+static void CreateIntSlider(Settings::BasicSetting& setting, bool reversed, float multiplier,
+                            QLabel* feedback, const QString& use_format, QSlider* slider,
+                            std::function<std::string()>& serializer,
+                            std::function<void()>& restore_func) {
+    int max_val = std::strtol(setting.MaxVal().c_str(), nullptr, 0);
```
Comment (FearlessTobi) [inline src/yuzu/configuration/shared_widget.cpp:262]:
```suggestion
    const int max_val = std::strtol(setting.MaxVal().c_str(), nullptr, 0);
```

File: src/yuzu/configuration/shared_widget.cpp [hunk 3]
```diff
@@ -255,6 +255,58 @@ QWidget* Widget::CreateLineEdit(std::function<std::string()>& serializer,
...
+    restore_func = [slider, &setting]() {
+        slider->setValue(std::strtol(RelevantDefault(setting).c_str(), nullptr, 0));
+    };
+}
+
+static void CreateFloatSlider(Settings::BasicSetting& setting, bool reversed, float multiplier,
+                              QLabel* feedback, const QString& use_format, QSlider* slider,
+                              std::function<std::string()>& serializer,
+                              std::function<void()>& restore_func) {
+    float max_val = std::strtof(setting.MaxVal().c_str(), nullptr);
```
Comment (FearlessTobi) [inline src/yuzu/configuration/shared_widget.cpp:286]:
```suggestion
    const float max_val = std::strtof(setting.MaxVal().c_str(), nullptr);
```
dito below

File: src/yuzu/configuration/shared_widget.cpp [hunk 4]
```diff
@@ -344,6 +387,43 @@ QWidget* Widget::CreateSpinBox(const QString& given_suffix,
...
+QWidget* Widget::CreateDoubleSpinBox(const QString& given_suffix,
+                                     std::function<std::string()>& serializer,
+                                     std::function<void()>& restore_func,
+                                     const std::function<void()>& touch) {
+    const auto min_val = std::strtod(setting.MinVal().c_str(), nullptr);
+    const auto max_val = std::strtod(setting.MaxVal().c_str(), nullptr);
+    const auto default_val = std::strtod(setting.ToString().c_str(), nullptr);
+
+    QString suffix =
+        given_suffix == QStringLiteral("") ? DefaultSuffix(this, setting) : given_suffix;
```
Comment (FearlessTobi) [inline src/yuzu/configuration/shared_widget.cpp:399]:
```suggestion
        given_suffix == QStringLiteral{} ? DefaultSuffix(this, setting) : given_suffix;
```
just {} might be possible as well, you need to try

File: src/yuzu/configuration/shared_widget.h [hunk 5]
```diff
@@ -43,6 +44,9 @@ enum class RequestType {
     MaxEnum,
 };
 
+constexpr const float default_multiplier{1.f};
```
Comment (FearlessTobi) [inline src/yuzu/configuration/shared_widget.h:47]: I think constexpr already implies const

File: src/yuzu/configuration/shared_widget.cpp (hunk 4 above)
Comment (lat9nq) [reply src/yuzu/configuration/shared_widget.cpp:399]: Doesn't work, Clang wants to use QStringLiteral as an identifier
