### PR TITLE
 maxwell3d: HLE multi-layer clear macro 

### LINKED ISSUE #9038: Xenoblade Chronicles 3 crashes during the first loading screen after EA 2979 and Mainline 1189
Build: Yuzu EA 2979 - 3007
Game version : 1.1.1
CPU : AMD Ryzen 5 5600X 6-Core Processor
GPU : Rx 5700
API: Vulkan
VRAM : 8GB
RAM : 32GB
OS : Windows 11 Version 22H2 (Build 22621.608)
Driver : 22.10.1

after the EA 2979 and Mainline 1189  the game crashes during the first loading screen.

Logs:

[yuzu_log xc3 2979.txt](https://github.com/yuzu-emu/yuzu/files/9740080/yuzu_log.xc3.2979.txt)

[yuzu_log xc3 3007.txt](https://github.com/yuzu-emu/yuzu/files/9740082/yuzu_log.xc3.3007.txt)

### PR DESCRIPTION
**Pull request by liamwhite**
Adds a HLE multi-layer clear mechanism, since AMD has been dragging their feet on fixing clears of multiple layers per command queue submission in their driver. This allows Xenoblade Chronicles 3 to become playable on AMD Windows again.

Fixes #9038

TODO: is the layer index not implemented for OpenGL? I couldn't see how it was used.

### CODE REVIEW

**Comment by Kelebek1** [comment]
I don't understand why you would want to use the raw there. Isn't it possible that volume is enabled, which means you'd try to clear 0x10000 layers?

**Review by FernandoS27 — APPROVED** [review]

File: src/video_core/renderer_opengl/gl_rasterizer.cpp [hunk 1]
```diff
@@ -136,7 +136,7 @@ void RasterizerOpenGL::LoadDiskResources(u64 title_id, std::stop_token stop_load
     shader_cache.LoadDiskResources(title_id, stop_loading, callback);
 }
 
-void RasterizerOpenGL::Clear() {
+void RasterizerOpenGL::Clear(u32 layer_count) {
```
Comment (vonchenplus) [inline src/video_core/renderer_opengl/gl_rasterizer.cpp:139]: Need attach to a framebuffer, like glFramebufferTextureLayer

Comment (liamwhite) [reply src/video_core/renderer_opengl/gl_rasterizer.cpp:139]: Would you be able to add this in a separate PR?

**Review by bunnei — APPROVED** [review]
