### PR TITLE
qt: continue event loop during game close

### LINKED ISSUE #9472: Stop Emulation Causes YUZU to crash or stop responding
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1273

### Description of Issue

Stop Emulation Causes YUZU to crash or stop responding in Windows 10 Pro x64.

This issue started since Mainline 1273

### Expected Behavior

To stop emulation gracefully

### Reproduction Steps

- Start emulation on any game 
- Click on "Emulation" -> "Stop"
- YUZU stop responding/crashes

### Log File

No Error logs are generated as the whole app hangs up.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10254835/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10254836/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel I7 10700F
GPU/Driver: Nvidia RTX 3060 / 527.56
RAM: 64GB
OS: Windows 10 Pro x64

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #9472 (UI jank from not pumping event loop while waiting for close)

Also puts up an informative overlay while waiting begins
Screenshot from 2022-12-18 23-17-17

### CODE REVIEW

File: src/yuzu/main.cpp [hunk 1]
```diff
@@ -1801,13 +1802,42 @@ void GMainWindow::ShutdownGame() {
...
+void GMainWindow::OnEmulationStopped() {
+    shutdown_timer.stop();
+    emu_thread->disconnect();
+    emu_thread->wait();
     emu_thread = nullptr;
 
+    if (shutdown_dialog) {
+        shutdown_dialog->close();
+        delete shutdown_dialog;
+        shutdown_dialog = nullptr;
```
Comment (Morph1984) [inline src/yuzu/main.cpp:1838]:
```suggestion
        shutdown_dialog->deleteLater();
```

**Review by Morph1984 — APPROVED** [review]

**Comment by Hexaae** [comment]
Just an idea... What about using an icon (and avoid also another localization string) when quitting instead of text?
e.g.
https://www.google.com/search?q=exit+icon&sxsrf=ALiCzsZMH6GRom23Gkp0_tXKwxZbq06gdQ:1671543507633&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjt0_7nqIj8AhU2a_EDHY0CBgwQ_AUoAXoECAIQAw&biw=1551&bih=920&dpr=1#imgrc=d_KPKoGwYeIZiM

**Comment by v1993** [comment]
This does not work properly if you stop game while it's still launching.

**Comment by liamwhite** [comment]
Latest commit fixes #9498
