### PR TITLE
video_core: Implement all vulkan topology

### LINKED ISSUE #9491: Xenoblade games are broken now
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early access 3241

### Description of Issue

The games have glitched graphics now 
320407885_673509750985537_6738097080140881282_n
321036638_714303506869598_8161399110208312741_n
320745168_1340479580109594_3436151908654454153_n

### Expected Behavior

320519085_548955777120503_6480967134779018408_n
320621598_549124843506510_6421339167066794312_n
320748975_1497509900659443_3394580281875086357_n

### Reproduction Steps

1. Run the games
2. Thats it. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10291051/yuzu_log.txt)

### System Configuration

Build: Early access 3241
Game version : Xenoblade chronicles v1.1.2, Xenoblade Chronicles 2 v2.1.0, Xenoblade Chronicles 3 v1.2.0
CPU : AMD Ryzen 5 5600X 6-Core Processor
GPU : Rx 5700
API: Vulkan
VRAM : 8GB
RAM : 32GB
OS : Windows 11 Version 22H2 (Build 22621.963)
Driver : 22.11.2

### PR DESCRIPTION
**Pull request by vonchenplus**
QuadStrip need to use triangles to simulator it, and also need to simulator indexed and non-indexed modes. 
In non-indexed mode  just create a fixed mapping table (because can reuse it).
In indexed mode need to do a dynamic mapping of the original drawing index, and here use a compute shader to implement it.

LineLoop need to use triangle list to simulator it.

Polygon need to use triangle fan to simulator it.

Fix BOTW Hero's Path.
image

Fix Pokemon Scarlet Status summary graphic.
image

Close #9491

### CODE REVIEW

File: src/video_core/renderer_vulkan/vk_buffer_cache.cpp [hunk 1]
```diff
@@ -123,14 +114,200 @@ VkBufferView Buffer::View(u32 offset, u32 size, VideoCore::Surface::PixelFormat
...
+        const size_t sub_first_offset = static_cast<size_t>(first % 4) * GetQuadsNum(num_indices);
+        const size_t offset =
+            (sub_first_offset + GetQuadsNum(first)) * 6ULL * BytesPerIndex(index_type);
+        scheduler.Record([buffer = *buffer, index_type_, offset](vk::CommandBuffer cmdbuf) {
+            cmdbuf.BindIndexBuffer(buffer, offset, index_type_);
+        });
+    }
+
+protected:
+    virtual u32 GetQuadsNum(u32 num_indices) = 0;
```
Comment (lioncash) [inline src/video_core/renderer_vulkan/vk_buffer_cache.cpp:203]:
```suggestion
    virtual u32 GetQuadsNum(u32 num_indices) const = 0;
```

File: src/video_core/renderer_vulkan/vk_buffer_cache.cpp [hunk 2]
```diff
@@ -123,14 +114,200 @@ VkBufferView Buffer::View(u32 offset, u32 size, VideoCore::Surface::PixelFormat
...
+
+    ~QuadArrayIndexBuffer() = default;
+
+private:
+    u32 GetQuadsNum(u32 num_indices_) override {
+        return num_indices_ / 4;
+    }
+
+    template <typename T>
+    std::array<T, 6> MakeIndices(u32 quad, u32 first) {
```
Comment (lioncash) [inline src/video_core/renderer_vulkan/vk_buffer_cache.cpp:232]:
```suggestion
    static std::array<T, 6> MakeIndices(u32 quad, u32 first) {
```

File: src/video_core/renderer_vulkan/vk_buffer_cache.cpp [hunk 3]
```diff
@@ -123,14 +114,200 @@ VkBufferView Buffer::View(u32 offset, u32 size, VideoCore::Surface::PixelFormat
...
+
+    ~QuadStripIndexBuffer() = default;
+
+private:
+    u32 GetQuadsNum(u32 num_indices_) override {
+        return num_indices_ >= 4 ? (num_indices_ - 2) / 2 : 0;
+    }
+
+    template <typename T>
+    std::array<T, 6> MakeIndices(u32 quad, u32 first) {
```
Comment (lioncash) [inline src/video_core/renderer_vulkan/vk_buffer_cache.cpp:272]:
```suggestion
    static std::array<T, 6> MakeIndices(u32 quad, u32 first) {
```

**Review by liamwhite — APPROVED** [review]
