### PR TITLE
k_thread: Use a mutex and cond_var to sync bool

### LINKED ISSUE #10232: MinGW builds cannot run guests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1223 and later

### Description of Issue

Caused by #8858 -- @vonchenplus your input would be valuable here

Trying to boot a game in yuzu compiled via a MinGW toolchain (either Clang or GCC) causes the application to freeze shortly after it starts. The guest fails to run for more than a couple seconds.

Only the null graphics backend can run the game. Both OpenGL and Vulkan are affected by this.

### Expected Behavior

The game should boot and run for an extended period of time.

### Reproduction Steps

- Compile yuzu with a MinGW toolchain, i.e. with our linux-mingw Docker container, used in CI.
- Run a guest program (i.e. es2gears.nro)
- Either yuzu stops at loading the application, or the application loads and runs for a few seconds before 0 fps and freeze

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11454852/yuzu_log.zip)

### System Configuration

CPU: Intel Core i5-11600k
GPU/Driver: NVIDIA RTX A4000 / 528.89
RAM: 16 GB
OS: Windows 10 Pro

### PR DESCRIPTION
**Pull request by lat9nq**
std::atomic\<bool\> is broken on MinGW and causes deadlocks there. Use a normal cond var in its stead.

Fixes #10232

### CODE REVIEW

File: src/core/hle/kernel/k_thread.cpp [hunk 1]
```diff
@@ -1323,16 +1327,21 @@ void KThread::DummyThreadBeginWait() {
...
-    // Wake up the waiting thread.
-    m_dummy_thread_runnable.store(true);
-    m_dummy_thread_runnable.notify_one();
+    {
+        std::scoped_lock lock{m_dummy_thread_mutex};
+
+        // Wake up the waiting thread.
+        m_dummy_thread_runnable = true;
+    }
+    m_dummy_thread_cv.notify_one();
```
Comment (liamwhite) [inline src/core/hle/kernel/k_thread.cpp:1344]:
```suggestion
    // Wake up the waiting thread.
    {
        std::scoped_lock lock{m_dummy_thread_mutex};
        m_dummy_thread_runnable = true;
    }
    m_dummy_thread_cv.notify_one();
```

File: src/core/hle/kernel/k_thread.cpp [hunk 2]
```diff
@@ -1323,16 +1327,21 @@ void KThread::DummyThreadBeginWait() {
     }
 
     // Block until runnable is no longer false.
-    m_dummy_thread_runnable.wait(false);
+    std::unique_lock lock{m_dummy_thread_mutex};
+    m_dummy_thread_cv.wait(lock, [this]() { return m_dummy_thread_runnable; });
```
Comment (liamwhite) [inline src/core/hle/kernel/k_thread.cpp:1331]:
```suggestion
    m_dummy_thread_cv.wait(lock, [this] { return m_dummy_thread_runnable; });
```

**Review by liamwhite — APPROVED** [review]

**Review by Morph1984 — APPROVED** [review]
