### PR TITLE
sink_stream: Resolve heap buffer corruption due to out of bounds write

### LINKED ISSUE #10897: Xenoblade Chronicles 2 latest EA3708 Beeping noise and crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3708

### Description of Issue

3706 fixed the problem but latest 3708 XenoBlade Chronicles 2 Cutscenes Beeping noise and crash happen again 

### 

Example: 
https://youtu.be/YhTsUpFqJ_4

### Reproduction Steps

Play normal Vulkan,
start Torna the golden country DLC 

or 

Event theater > chapter2 > Her flames hide something deeper

XBC2 Gamesave
https://mega.nz/file/JPIFUbTK#3yGQsANf6xf5B9zIxBzp4LyHCvUiXDpcmsIkoC4OwZU

### Log File

yuzu_log.txt
https://mega.nz/file/gHoGnBKD#6tbbDS7f4pzXfSz03kW-3IDtRUcEBQV_WUgyHK9UHiM

### System Configuration

CPU: 13900K
GPU/Driver: 4090 , latest NVIDIA driver
RAM: 32G
OS: Was n11 22h2 latest update

### LINKED ISSUE #10900: Yuzu crashing in audio code in ssbu (smash)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1478

### Description of Issue

In mainline 1477 and 1478, some users have been getting a crash in ssbu while loading. This was not happening in 1476. 

We caught a minidump and it's crashing somewhere in the audio code, from build 1478.

image
[yuzu-crash-20230624155718.zip](https://github.com/yuzu-emu/yuzu/files/11857499/yuzu-crash-20230624155718.zip)

### Expected Behavior

Probably shouldn't crash in the audio code :P

### Reproduction Steps

Launch SSBU. This isn't happening for everyone, other people can't reproduce it, so not sure what the specific differences are.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11857506/yuzu_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

### LINKED ISSUE #10960: Xenoblade Chronicles: Definitie Edition crashes at the Intro Cutscene
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3720

### Description of Issue

Xenoblade Chronicles: Definitie Edition crashes at the Intro Cutscene (CTD). The whole emulator crashes and has to be restarted.

### Expected Behavior

Play the cutscene without CTD.

### Reproduction Steps

Crashes everytime after the loading screen, when the intro cutscene is about to start.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11909511/yuzu_log.txt)

### System Configuration

Mainboard: Gigabyte X670E Aorus Master
CPU: AMD Ryzen 7 7800X3D
GPU/Driver: Gainward GeForce RTX 4090 Phantom GS / WHQL 536.40
RAM: G.Skill Trident Z5 NEO EXPO 32 GB DDR5-6000 CL30-38-38-96
OS: Windows 11

### LINKED ISSUE #10965: Audio rattling.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1481 and before.

### Description of Issue

I've encountered an issue with the audio. It only happens with Yuzu, other games or audio sources in my pc don't mess up the output. Neither does the PS4 when the speakers are extracting audio from the monitor.
My setup includes speakers, which take the audio from my monitor via 3.5mm jack, at the same time this one taking the audio/video from my GPU via displayport.
When connecting the speakers directly to my motherboard there's no issue, but it's more convenient for my setup just to use the monitor audio since I have more devices connected to it.
When using the monitor audio, only the emulator distorts it and adds a whining/rattling to the game it's running, really annoying. The rattling changes as the games opens menus, and the audio feels less vibrant.
Only happens once it boots in the game, not before.
I'm just trying to inform the devs, but I'm sure you got lots of work ahead so don't take this as an urgent bug, just something it could be solved if it doesn't take too much time to figure out why this happens (maybe drivers or some displayport/hdmi standard).
Thank you so much for your patience.

### Expected Behavior

Audio being the same with speakers connected to motherboard and with speakers connected to monitor.

### Reproduction Steps

Changing the 3.5mm jack to the monitor, even with the game already booted, messes up the audio as described before.

### Log File

Happens in every pc I've tried, no log needed.

### System Configuration

CPU: AMD 5600X
GPU/Driver: Nvidia RTX 3060ti
RAM: 32GB DDR4 3200MHz
OS: Windows 10

### PR DESCRIPTION
**Pull request by Morph1984**
Also, remove the use of ScratchBuffer when upmixing, as other channels may not be initialized with zeroed out data.

Note: This may resolve several unexplainable crashes and memory corruption unrelated to audio.

Fixes #10897
Fixes #10900
Fixes #10960
Fixes #10965

### CODE REVIEW

**Comment by EgoBizarro** [comment]
Oooph, nice! 
This seems to also have fixed the farting noise static plus crashing in Theatrhythm and Pikmin 4 demo when using cubeb.

File: src/audio_core/sink/sink_stream.cpp [hunk 1]
```diff
@@ -66,45 +70,47 @@ void SinkStream::AppendBuffer(SinkBuffer& buffer, std::span<s16> samples) {
...
+    }
 
-    } else if (system_channels == 2 && device_channels == 6) {
+    if (system_channels == 2 && device_channels == 6) {
         // We need moar samples! Not all games will provide 6 channel audio.
         // TODO: Implement some upmixing here. Currently just passthrough, with other
         // channels left as silence.
-        auto new_size = samples.size() / system_channels * device_channels;
-        tmp_samples.resize_destructive(new_size);
+        std::vector<s16> new_samples(samples.size() / system_channels * device_channels);
```
Comment (Kelebek1) [inline src/audio_core/sink/sink_stream.cpp:81]: This should take a 0 to 0-init all the other channels. This can be left as the scratchbuffer though and use std::fill to do the same.

**Comment by Angeluz01** [comment]
Thanks

File: src/audio_core/sink/sink_stream.cpp (hunk 1 above)
Comment (Morph1984) [reply src/audio_core/sink/sink_stream.cpp:81]: From cppreference:
> Constructs the container with count default-inserted instances of T. No copies are made.

Comment (Kelebek1) [reply src/audio_core/sink/sink_stream.cpp:81]: > From cppreference:
> 
> > Constructs the container with count default-inserted instances of T. No copies are made.

Why not keep it as a scratchbuffer though?

Comment (Morph1984) [reply src/audio_core/sink/sink_stream.cpp:81]: Because ScratchBuffer, as said earlier, skips this initialization.
If we need to fill it with 0s afterwards, what's the point?

Comment (liamwhite) [reply src/audio_core/sink/sink_stream.cpp:81]: ScratchBuffer also skips allocation. Doing a std::fill or memset on the buffer after resize_destructive would also do the job. That said, it's uglier than this and I can't see it being much of a bottleneck to begin with.

**Review by liamwhite — APPROVED** [review]
