### PR TITLE
fsp_srv: Fix filesystem access logging

### LINKED ISSUE #4712: Xenoblade Chronicles 2: Enabling DLC prevents game boot
I've been trying to get DLC working for Xenoblade Chronicles 2 with mixed results. Sometimes the game doesn't boot (infinite load) with DLC installed, and sometimes I just get a black screen. Unchecking DLC and starting the game then makes the game load properly. The only DLC that seems to work is the "Helpful Items Pack".

Also, the same issue occurs with just the update, but in a lower frequency. Most of the time I can boot the game just fine with the update installed and selected.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5279550/yuzu_log.txt)

### PR DESCRIPTION
**Pull request by Morph1984**
This introduces a new setting Enable FS Access Log which saves the filesystem access log to sdmc:/FsAccessLog.txt

image
image

If this setting is not enabled, this will indicate to FS to not call OutputAccessLogToSdCard.

NOTE: This setting is not enabled by default.
NOTE2: This setting **does not need to be enabled** to fix the loading softlock in XC2, it is only **meant for debugging purposes**

Fixes softlocks during loading in Xenoblade Chronicles 2 when certain DLC is enabled.

Supersedes #6458 

Fixes #4712 

Thanks to @gidoly, @OZtistic and @G-Spawn for testing

### CODE REVIEW

**Comment by gidoly** [comment]
This issue can be close after this change merge to master https://github.com/yuzu-emu/yuzu/issues/4712

File: src/core/reporter.cpp [hunk 1]
```diff
@@ -362,22 +364,12 @@ void Reporter::SaveErrorReport(u64 title_id, ResultCode result,
...
 
-void Reporter::SaveFilesystemAccessReport(Service::FileSystem::LogMode log_mode,
-                                          std::string log_message) const {
-    if (!IsReportingEnabled())
-        return;
-
-    const auto timestamp = GetTimestamp();
-    const auto title_id = system.CurrentProcess()->GetTitleID();
-    json out;
+void Reporter::SaveFSAccessLog(std::string log_message) const {
```
Comment (lioncash) [inline src/core/reporter.cpp:367]: Perhaps this should be a `std::string_view` now

**Review by lioncash — APPROVED** [review]
LGTM aside from one nit
