### PR TITLE
gl_texture_cache: Implement pixel format conversions for copies

### LINKED ISSUE #4220: Broken Cutscene Rendering in Bayonetta 2
Bayonetta 2 cutscene rendering is now broken as of Mainline 292

Mainline 291

Mainline 292

### LINKED ISSUE #6845: [ampere issue] luigi's mansion, weird shadow on open gl glsl, glasm
luigi's mansion have weird shadow issue on ampere gpu
unknown3
unknown2
unknown
log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6951455/yuzu_log.txt)

hardware:
i5 9600k
rtx 3060

thanks to pandorify from discord for reporting issue

### PR DESCRIPTION
**Pull request by ameerj**
Texture copies with "incompatible" formats (i.e. Color <-> Depth) were left unimplemented on OpenGL after TCR. 
This PR aims to implement format conversions by repurposing the existing method used for BGR <-> RGB texture format conversion. 

This is expected to fix a number of issues. For example:

### Luigi's Mansion 3 Shadow Trail

https://user-images.githubusercontent.com/52414509/142131633-fa8aa4e6-5a58-4304-824e-4dc8e1b54aa9.mp4

https://user-images.githubusercontent.com/52414509/142131645-f295dc55-d1a2-4d3b-9f16-19939d19b902.mp4

### Bayonetta 2 Cutscene DOF

https://user-images.githubusercontent.com/52414509/142131213-cd13a780-e962-4f9d-9ce8-0abb3139ae18.mp4

https://user-images.githubusercontent.com/52414509/142131230-7eea0eae-d160-4556-99ba-77967da761e7.mp4

closes #6845 closes #4220

### CODE REVIEW

**Review by FernandoS27 — APPROVED** [review]

File: src/video_core/renderer_opengl/gl_texture_cache.cpp [hunk 1]
```diff
@@ -1286,35 +1292,37 @@ Framebuffer::Framebuffer(TextureCacheRuntime& runtime, std::span<ImageView*, NUM
...
-            bgr_pbo.Create();
-            bgr_pbo_size = copy_size;
-            glNamedBufferData(bgr_pbo.handle, bgr_pbo_size, nullptr, GL_STREAM_COPY);
+        const auto src_origin = MakeCopyOrigin(copy.src_offset, copy.src_subresource, src_target);
+        const auto dst_origin = MakeCopyOrigin(copy.dst_offset, copy.dst_subresource, dst_target);
+        const auto region = MakeCopyRegion(copy.extent, copy.dst_subresource, dst_target);
+        const u32 copy_size = region.width * region.height * region.depth * img_bpp;
+        if (pbo_size < copy_size) {
+            intermediate_pbo.Create();
+            pbo_size = copy_size;
```
Comment (FernandoS27) [inline src/video_core/renderer_opengl/gl_texture_cache.cpp:1307]: get closest ceiling power of 2, this could reduce the creation/destroction.

**Review by bunnei — APPROVED** [review]
