### PR TITLE
[audio] Fix data source version 1 command looping

### LINKED ISSUE #11462: Xenoblade Chronicles 2 environment sounds cutting out during cutscenes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3856

### Description of Issue

During cutscenes, ambient background sounds like wind or others cut out, usually near the start of the scene. The problem happens both when triggering cutscenes in-game or via the event viewer.

https://github.com/yuzu-emu/yuzu/assets/144349241/1303f901-24f9-4203-a287-87fb5219308a

This seems to happen to almost every cutscene where background noise is present. Some sounds like rain or thunder still play.

### Expected Behavior

Background audio should not cut out during cutscenes, as the way the cutscenes play on the Switch.

### Reproduction Steps

Play any cutscene either in-game or via the event viewer that has background noises. "Behold the Maelstrom" from chapter one is a very clear example of the problem.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12549350/yuzu_log.txt)

### System Configuration

CPU: Intel Core i5-6600k
GPU/Driver: Nvidia GeForce GTX 1060 6GB / Driver Version: 536.40
RAM: 16,0GB@3000MHz
OS: Microsoft Windows 10 Pro

### PR DESCRIPTION
**Pull request by Kelebek1**
After a small change I made in #11428 to decode, audio was cutting out in XC2, and causing some issues in other games as well. 

After a bunch of investigation, I found an issue with version 1 of data source commands trying to loop. Version 2 of the data source commands added more looping control, and the decode function was updated to use them. Instead of splitting the decode function into an old and new for both version, instead they just passed the v2 struct, and the v1 commands initialise v2 wavebuffers using the v1 data.

I was not considering this properly, and wasn't correctly considering the new members when creating the v2 struct. This PR properly initialises those members which fixes v1 commands looping.

Closes #11462.

### CODE REVIEW

File: src/audio_core/renderer/command/data_source/adpcm.cpp [hunk 1]
```diff
@@ -20,6 +20,12 @@ void AdpcmDataSourceVersion1Command::Process(const AudioRenderer::CommandListPro
     auto out_buffer{processor.mix_buffers.subspan(output_index * processor.sample_count,
                                                   processor.sample_count)};
 
+    for (auto& wave_buffer : wave_buffers) {
+        wave_buffer.loop_start_offset = wave_buffer.start_offset;
+        wave_buffer.loop_end_offset = wave_buffer.end_offset;
+        wave_buffer.loop_count = -(wave_buffer.loop & 1);
```
Comment (liamwhite) [inline src/audio_core/renderer/command/data_source/adpcm.cpp:26]: wave_buffer.loop_count = wave_buffer.loop ? -1 : 0

**Review by liamwhite — APPROVED** [review]
