### PR TITLE
video_core: fix off by one in anisotropic filtering amount

### LINKED ISSUE #8856: shattered graphics when using ansiotropic filtering settings other than "default"
using a 6900XT with Vulkan on Arch Linux using version 1153.
I wanted to play games at 16x ansiotropic, but whenever ansiotropic filtering is set to anything other than "default", graphics have this effect.

yuzu graphics bug

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9483249/yuzu_log.txt)

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #8856 SMO rendering in RADV at 1x with automatic anisotropy (other scaler resolutions are still affected, this seems to be related to differing behaviors of higher anisotropy levels with sRGB textures) 
Fixes SMS water rendering in LVP at automatic anisotropy (still happens with other anisotropy values, see [here](https://wiki.dolphin-emu.org/index.php?title=Super_Mario_Sunshine#Anisotropic_Filtering))

|Before|After|
|-|-|
|||
|010049900f546002_2022-12-10_19-29-25-455|010049900f546002_2022-12-10_19-27-30-336|

### CODE REVIEW

File: src/video_core/textures/texture.cpp [hunk 1]
```diff
@@ -64,10 +64,11 @@ float TSCEntry::MaxAnisotropy() const noexcept {
         return 1.0f;
     }
     const auto anisotropic_settings = Settings::values.max_anisotropy.GetValue();
-    u32 added_anisotropic{};
+    s32 added_anisotropic{};
```
Comment (lioncash) [inline src/video_core/textures/texture.cpp:67]: Shouldn't the final calc near the bottom require a cast on `max_anisotropy`, since it's currently doing mixed signedness arithmetic?

Comment (liamwhite) [reply src/video_core/textures/texture.cpp:67]: added_anisotropic is otherwise intended to be non-negative, the signedness change is just because subtracting 1 from the scaler value might produce -1. (The sum can't overflow because max_anisotropy is a 3-bit bitfield)

**Review by lioncash — APPROVED** [review]
