### PR TITLE
Controller bugfixes in profile select, closes #8265

### LINKED ISSUE #8265: Bug - Controller does not work when selecting a user profile on game start
Using Mainline Build - 175153303

This issue refers to the dialog that appears after selecting a game, having checked the option to select a user profile upon game start. The Up/Down arrows navigate up/down and A/B starts the game. However, the default profile is used, and not the one selected. 

This issue does not occur when using a mouse.

### PR DESCRIPTION
**Pull request by jonesyUK**
2 fixes for using a controller in profile select dialog.

1) Pressing 'B' cancels the launch of the game
2) Using controller to select a profile now correctly sets the index to use for the launch

### CODE REVIEW

**Comment by Docteh** [comment]
how come you didn't just edit the other PR? (#8713)

Everything except the name of the branch your PR is from can be revised. 

Looks like you've got it with that commit title, but for next time you can just do
image

You can force push branches to github if you've amend the commit

so in  CLI I'll regularly do 

`git commit --amend -a`
`git push --force`

**Comment by jonesyUK** [comment]
Thanks for the guidance @Docteh , it's been a while wrangling git for me, so I went ahead with a new title with the same updates. Appreciate the CLI snippet for the force push, I'll use that.

File: src/yuzu/main.cpp [hunk 1]
```diff
@@ -1632,7 +1633,8 @@ void GMainWindow::BootGame(const QString& filename, u64 program_id, std::size_t
     Settings::LogSettings();
 
     if (UISettings::values.select_user_on_boot) {
-        SelectAndSetCurrentUser();
+        if (SelectAndSetCurrentUser() == false)
+            return;
```
Comment (german77) [inline src/yuzu/main.cpp:1637]:
```suggestion
        if (!SelectAndSetCurrentUser()) {
            return;
        }
```
We always use braces around if statements.

**Review by german77 — COMMENTED** [review]
Looks good, just one minor nit

File: src/yuzu/main.cpp (hunk 1 above)
Comment (german77) [reply src/yuzu/main.cpp:1637]: Maybe do the same with `loadROM` since you are already touching this part of the code.

**Review by german77 — APPROVED** [review]

**Comment by goldenx86** [comment]
Hi, can I mention you and this PR in the next progress report?

**Comment by jonesyUK** [comment]
Sure, no problem, thanks for asking!
