### PR TITLE
Project Mjölnir: Part 1 - Input Rewrite

### LINKED ISSUE #2310: [Request] Remove GUID from controller input config
Right now Yuzu (And Citra) write GUIDs to the config when you set up a controller. This is unnecessary because they already write the controller port to the config, so player one is only ever going to listen to a controller in port 0 for example, there's no concern that it'll accidentally listen to something else because it's only looking for port 0.

The reason I want the GUID removed is because it causes problems whenever a controller is changed in any way. For example, I may be playing a game on an Xbox One controller over bluetooth, the battery dies and I plug it in through USB. Doing this changes the GUID, and now none of the controls work. I have to rebind every single button again even though it's already set up for an Xinput controller on port 0, and when it's done charging, I have to do that again. There are also times where I may just want to use a different controller. Even though my 8bitdo controllers are Xinput, or a DS4 or Switch controller can use Xinput drivers, I have to rebind them all because of GUID.

There shouldn't be any issues removing GUID as long as Yuzu is properly reading controller ports. Most other popular emulators do not require a GUID including Dolphin, PCSX2, RPCS3, Xenia, PPSSPP, CXBX-R, etc.

### LINKED ISSUE #2865: hid: Input from Single Joycons do not register in some games.
As a result of this, some games that exclusively makes use of Single Joycons and do not work with the Pro Controller or Dual Joycons will not work properly due to no input being provided.

Keep in mind that input with single joycons would have them rotated horizontally, with the joysticks on the left.

A notable example would be Pokemon: Let's Go in docked mode, where the only accepted inputs are the left and right joycons, and the Pokeball Plus

### LINKED ISSUE #2905: DisconnectNpad getting called due to AcquireNpadStyleSetUpdateEventHandle
Upon research, hid breaking in many games depending on control styles(Pokemon lets go, links awakening) is caused due to DisconnectNpad being called. The reason why it's being called is unclear however I have reason to believe it's related to the AcquireNpadStyleSetUpdateEventHandle call. This needs to be further investigated.

Few things to note, AcquireNpadStyleSetUpdateEventHandle MUST be signaled at some point for a controller to actually be considered "activated". 
#2904 seems to signal it in a more appropriate location as it allows multiple controllers to show up in Pokemon Lets go instead of a single controller.
Input DOES work if we disable DisconnectNpad for these controllers which rules out the issue of incorrect shared memory sections or items like that. However, an incorrect shared memory could also be the reason why "DisconnectNpad" is being called.

<meta name="titleids"  content="01006BB00C6F0000,0100187003A36000,010003F003A34000">

### LINKED ISSUE #2906: Changing controllers in the UI does not update them accordingly in HID
The configuration UI would need to have an overhaul to the way controllers are updated during gameplay. Controllers are never initialized when they are changed whilst in-game and the styleset changed event will never be called. We'll need to rework how the configuration ui<->hid work together

### LINKED ISSUE #3281: LB and LS are not working on the undocked right controller
Tried to play Snipperclips plus, but LB and LS are not working on the undocked right controller. Tried rebinding the keys to something else, same issue.

### LINKED ISSUE #3457: Input issue with the game GhoulBoy
EA 234
Xinput Controller (Xbox1 Elite 2)
Windows 10

In the game GhoulBoy when you press the L or LT button the character will move the the left. LT will make the player continuously go left, until you remap the controller.

### LINKED ISSUE #3940: L and R keys stay pressed when let go #254
Hi. Every time I press the L or R keys once, they just don't stop. I've tried changing my controller settings, switching them from docked to undocked and experimenting in the Controls tab, I even changed my controller to a PS4 controller, but nothing is working.

This hasn't been a huge problem for me until I got Pokemon Sword for a nuzlocke. Now I can't hold a box still so I can't put any Pokemon in it or take any out.

Please, I need help.

### LINKED ISSUE #4057: Yuzu unable to detect more than 4 controllers (SSBU 8-player smash)
I'm streaming SSBU with some friends and other people over Parsec and it's working fine, I configured all 8 controller ports on qt-config.ini and are working accordingly, they all show up as 'connected' in game, but it seems that only 4 players are able to join in. 
I heard that Xinput only has support for 4 players but I can't find if yuzu uses Xinput or Directinput (which supports 8) anywhere on the web, or how to use Directinput on yuzu instead of whatever they have. Any way to fix this?

### LINKED ISSUE #4062: SR and SL keys are not recognized by games
When playing local coop with two xbox one controller (snipperclips and super mario odyssey) SR and SL keys cannot be recognized by games. 

I set two players one with right joy con and the other with left joy con (the orientation took me a while to make it work) but the SR and SL keys have no effects upon pressing in game no matter which key i assign them to.

### LINKED ISSUE #4268: Yuzu doesn't react to button pressing after disconnecting and connecting DS4 again during gaming
I got DS4 controller connected through micro usb. Sometimes during excessive motions it briefly disconnects from PC. After that Yuzu stops react on it until I remapped the buttons or relaunch the application entirely. It's annoying to say the least.
I'm using it without DS4 Windows wrapper, with it it's fine.

### LINKED ISSUE #4435: Mismatched UI bottom bar's values when using midnight blue and midnight blue colorful qt-themes
Bugs:
1. Selecting Vulkan API changes background color to darker "disabled" - color should be light "enabled" for both vulkan and opengl.
2. ASYNC, MULTICORE and DOCK values are mismatched: enabling them on bottom bar UI disable them in settings.

### PR DESCRIPTION
**Pull request by Morph1984**
# Project Mjölnir: Part 1 - Input Rewrite

### Whosoever holds this hammer, if they be worthy, shall possess the power of Thor.

This is Part 1 of a multipart rewrite to yuzu's HID (Human Interface Device) frontend and backend implementations, spiritual successor to Project Aphrodite by @jroweboy.

By overhauling the Qt frontend with a brand new and more intuitive `Controls` section and improving/fixing the backend to be closer to the Nintendo Switch, this allows users to more easily configure and map their controllers before playing or within a game.

input_main

## Qt Frontend improvements

- Overhauled `Controls` section with a brand new layout and theme specific controller icons.
- Pro Controller is now the default controller instead of Dual Joycons.
- "Use Docked Mode" and "Joycons Docked" are no more, these are replaced by Docked/Undocked radio buttons under "Console Mode" and the Handheld Controller only selectable by Player 1.

handheld

- Input Devices are now selectable, with "Any", "Keyboard", or any controller connected through SDL. GC Controller input is captured under "Any".
- Selecting an SDL connected controller within the input devices combobox **will map buttons and axes automatically, no setup required!**
- Multiple controllers can be differentiated by their name and port number. For example: "XInput Controller 0", "XInput Controller 1", "PS3 Controller 0".

input_devices

- Joystick range spinbox when analog sticks are used, thanks to @ameerj for implementing this in #4330.

- Easily connect multiple players with the "Connected Controllers" checkboxes.

connected_controllers

- Moved Joycon color selection to the Advanced tab.

advanced

The following UI elements are placeholders for any present or future PR:

- Vibration percentage spinbox
- Motion configuration button (in both Player and Advanced)
- Profile selection, addition, and deletion

## HID Backend improvements and fixes

- Fix the LED Pattern for Players 1-4.
- Fix controller detection in homebrew applications, allowing them to properly detect connected controllers.
- Fully implement `DisconnectNpad`.
- Fix a questionable implementation of `SetSupportedNPadIdTypes`.
- Consolidate all usages of `InitNewlyAddedController`.
- Implement styleset changed events and signal them on connecting and disconnecting controllers.
- Synchronize controller settings between the frontend and backend. This allows changes done by either the game (through HID service commands) or user (through the frontend) to be reflected accurately on both ends.

The above changes allow Pokemon Lets Go Pikachu and Eevee to go in game with Single Joycons!

plg

## Special Mentions

- @Its-Rei for creating and designing all the UI and controller icons, and providing feedback every step of the way to ensure the most refined user experience possible!
- @jroweboy for the initial groundwork of this PR, known as Project Aphrodite.

This closes #2310, closes #2865, closes #2905, closes #2906, closes #3281, closes #3457, closes #3940, closes #4057, closes #4062, and closes #4268
This supersedes #4352

Miscellaneous fixes:
- The Midnight Blue theme should now be more consistent with the other 2 themes, fixes #4435

### CODE REVIEW

File: src/input_common/main.cpp [hunk 1]
```diff
@@ -103,6 +102,55 @@ std::string GenerateAnalogParamFromKeys(int key_up, int key_down, int key_left,
...
+    devices.insert(devices.end(), sdl_devices.begin(), sdl_devices.end());
+#endif
+    auto udp_devices = udp->GetInputDevices();
+    devices.insert(devices.end(), udp_devices.begin(), udp_devices.end());
+    return devices;
+}
+
+std::unordered_map<Settings::NativeButton::Values, Common::ParamPackage> GetButtonMappingForDevice(
+    const Common::ParamPackage& params) {
+    std::unordered_map<Settings::NativeButton::Values, Common::ParamPackage> mappings{};
```
Comment (lioncash) [inline src/input_common/main.cpp:121]:
```suggestion
    std::unordered_map<Settings::NativeButton::Values, Common::ParamPackage> mappings;
```

This should likely be converted into return {}; in the cases where it's returned. As the SDL case will need to unnecessarily construct an unordered map that isn't used.

File: src/input_common/main.cpp [hunk 2]
```diff
@@ -103,6 +102,55 @@ std::string GenerateAnalogParamFromKeys(int key_up, int key_down, int key_left,
...
+    if (params.Get("class", "") == "sdl") {
+        return sdl->GetButtonMappingForDevice(params);
+    }
+#endif
+    return mappings;
+}
+
+std::unordered_map<Settings::NativeAnalog::Values, Common::ParamPackage> GetAnalogMappingForDevice(
+    const Common::ParamPackage& params) {
+    std::unordered_map<Settings::NativeAnalog::Values, Common::ParamPackage> mappings{};
```
Comment (lioncash) [inline src/input_common/main.cpp:138]:
```suggestion
    std::unordered_map<Settings::NativeAnalog::Values, Common::ParamPackage> mappings;
```

This should likely be converted into `return {};` in the cases where it's returned. As the SDL case will need to unnecessarily construct an unordered map that isn't used.

File: src/input_common/sdl/sdl_impl.cpp [hunk 3]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
     }
 }
 
-static Common::ParamPackage SDLEventToButtonParamPackage(SDLState& state, const SDL_Event& event) {
+std::vector<Common::ParamPackage> SDLState::GetInputDevices() {
+    std::scoped_lock lock(joystick_map_mutex);
+    std::vector<Common::ParamPackage> devices = {};
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:548]:
```suggestion
    std::vector<Common::ParamPackage> devices;
```

File: src/input_common/sdl/sdl_impl.cpp [hunk 4]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
+    for (const auto& [key, value] : joystick_map) {
+        for (const auto& joystick : value) {
+            auto controller = joystick->GetSDLGameController();
+            auto joy = joystick->GetSDLJoystick();
+            if (controller) {
+                std::string name =
+                    fmt::format("{} {}", SDL_GameControllerName(controller), joystick->GetPort());
+                devices.emplace_back(Common::ParamPackage{
+                    {"class", "sdl"},
+                    {"display", name},
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:558]:
```suggestion
                    {"display", std::move(name)},
```

File: src/input_common/sdl/sdl_impl.cpp [hunk 5]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
 
-static Common::ParamPackage SDLEventToButtonParamPackage(SDLState& state, const SDL_Event& event) {
+std::vector<Common::ParamPackage> SDLState::GetInputDevices() {
+    std::scoped_lock lock(joystick_map_mutex);
+    std::vector<Common::ParamPackage> devices = {};
+    for (const auto& [key, value] : joystick_map) {
+        for (const auto& joystick : value) {
+            auto controller = joystick->GetSDLGameController();
+            auto joy = joystick->GetSDLJoystick();
+            if (controller) {
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:553]:
```suggestion
            if (auto controller = joystick->GetSDLGameController()) {
```

File: src/input_common/sdl/sdl_impl.cpp [hunk 6]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
+                    {"class", "sdl"},
+                    {"display", name},
+                    {"guid", joystick->GetGUID()},
+                    {"port", std::to_string(joystick->GetPort())},
+                });
+            } else if (joy) {
+                std::string name = fmt::format("{} {}", SDL_JoystickName(joy), joystick->GetPort());
+                devices.emplace_back(Common::ParamPackage{
+                    {"class", "sdl"},
+                    {"display", name},
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:566]:
```suggestion
                    {"display", std::move(name)},
```

File: src/input_common/sdl/sdl_impl.cpp [hunk 7]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
+        break;
+    case SDL_CONTROLLER_BINDTYPE_HAT:
+        out = BuildHatParamPackageForButton(port, guid, binding.value.hat.hat,
+                                            binding.value.hat.hat_mask);
+        break;
+    default:
+        break;
+    }
+    return out;
+};
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:670]:
```suggestion
}
```

File: src/input_common/sdl/sdl_impl.cpp [hunk 8]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
     return params;
 }
 
-namespace Polling {
+Common::ParamPackage BuildParamPackageForBinding(int port, const std::string& guid,
+                                                 const SDL_GameControllerButtonBind& binding) {
+    Common::ParamPackage out{};
+    switch (binding.bindType) {
+    case SDL_CONTROLLER_BINDTYPE_AXIS:
+        out = BuildAnalogParamPackageForButton(port, guid, binding.value.axis);
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:657]: These can just be returned instead of being assigned to a temporary

File: src/input_common/sdl/sdl_impl.cpp [hunk 9]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
-        params.Set("guid", joystick->GetGUID());
-        params.Set("axis", event.jaxis.axis);
-        if (event.jaxis.value > 0) {
-            params.Set("direction", "+");
-            params.Set("threshold", "0.5");
-        } else {
-            params.Set("direction", "-");
-            params.Set("threshold", "-0.5");
-        }
+        params = BuildAnalogParamPackageForButton(joystick->GetPort(), joystick->GetGUID(),
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:632]: This can be returned from the function directly, rather than being assigned to a temporary. Ditto for other cases.

File: src/input_common/sdl/sdl_impl.cpp [hunk 10]
```diff
@@ -523,65 +543,233 @@ SDLState::~SDLState() {
...
+        break;
+    default:
+        break;
+    }
+    return out;
+};
+
+Common::ParamPackage BuildParamPackageForAnalog(int port, const std::string& guid, int axis_x,
+                                                int axis_y) {
+    Common::ParamPackage params{};
```
Comment (lioncash) [inline src/input_common/sdl/sdl_impl.cpp:674]:
```suggestion
    Common::ParamPackage params;
```

File: src/input_common/main.h [hunk 11]
```diff
@@ -54,7 +74,9 @@ class DevicePoller {
 public:
     virtual ~DevicePoller() = default;
     /// Setup and start polling for inputs, should be called before GetNextInput
-    virtual void Start() = 0;
+    /// If a device_id is provided, events should be filtered to only include events from this
+    /// device id
+    virtual void Start(std::string device_id = "") = 0;
```
Comment (lioncash) [inline src/input_common/main.h:79]:
```suggestion
    virtual void Start(const std::string& device_id = "") = 0;
```

File: src/input_common/udp/udp.cpp [hunk 12]
```diff
@@ -77,17 +77,24 @@ State::State() {
...
+    Input::RegisterFactory<Input::TouchDevice>("cemuhookudp", touch_factory);
 }
 
 State::~State() {
     Input::UnregisterFactory<Input::TouchDevice>("cemuhookudp");
     Input::UnregisterFactory<Input::MotionDevice>("cemuhookudp");
 }
 
+std::vector<Common::ParamPackage> State::GetInputDevices() {
+    std::vector<Common::ParamPackage> devices = {};
```
Comment (lioncash) [inline src/input_common/udp/udp.cpp:93]:
```suggestion
    // TODO support binding UDP devices
    return {};
```

File: src/input_common/udp/udp.h [hunk 13]
```diff
@@ -5,19 +5,26 @@
...
 class Client;
+class UDPMotionFactory;
+class UDPTouchFactory;
 
 class State {
 public:
     State();
     ~State();
     void ReloadUDPClient();
+    std::vector<Common::ParamPackage> GetInputDevices();
```
Comment (lioncash) [inline src/input_common/udp/udp.h:22]:
```suggestion
    std::vector<Common::ParamPackage> GetInputDevices() const;
```

File: src/yuzu/configuration/configure_debug_controller.cpp [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+// Refer to the license.txt file included.
+
+#include "ui_configure_debug_controller.h"
+#include "yuzu/configuration/configure_debug_controller.h"
+
+ConfigureDebugController::ConfigureDebugController(QWidget* parent)
+    : QDialog(parent), ui(std::make_unique<Ui::ConfigureDebugController>()) {
+    ui->setupUi(this);
+
+    debug_controller = new ConfigureInputPlayer(this, 9, nullptr, true);
```
Comment (lioncash) [inline src/yuzu/configuration/configure_debug_controller.cpp:12]: This can go into the constructor initializer list.

File: src/yuzu/configuration/configure_input.cpp [hunk 15]
```diff
@@ -48,192 +62,157 @@ void OnDockedModeChanged(bool last_state, bool new_state) {
...
-    connect(ui->handheld_configure, &QPushButton::clicked, this,
-            [this] { CallConfigureDialog<ConfigureInputPlayer>(*this, 8, false); });
-
-    connect(ui->debug_configure, &QPushButton::clicked, this,
-            [this] { CallConfigureDialog<ConfigureInputPlayer>(*this, 9, true); });
-
-    connect(ui->mouse_advanced, &QPushButton::clicked, this,
+    // Only the first player can choose handheld mode so connect the signal just to player 1
+    connect(player_controllers[0], &ConfigureInputPlayer::HandheldStateChanged,
+            [&](bool is_handheld) { UpdateDockedState(is_handheld); });
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input.cpp:112]:
```suggestion
            [this](bool is_handheld) { UpdateDockedState(is_handheld); });
```

File: src/yuzu/configuration/configure_input.cpp [hunk 16]
```diff
@@ -48,192 +62,157 @@ void OnDockedModeChanged(bool last_state, bool new_state) {
...
+                    player_connected[index]->setChecked(is_connected);
+                }
+            } else {
+                for (std::size_t index = i; index < player_tabs.size(); ++index) {
+                    player_connected[index]->setChecked(is_connected);
+                }
+            }
+        });
+        connect(player_controllers[i], &ConfigureInputPlayer::RefreshInputDevices,
+                [&] { UpdateAllInputDevices(); });
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input.cpp:106]:
```suggestion
                [this] { UpdateAllInputDevices(); });
```

File: src/yuzu/configuration/configure_input.cpp [hunk 17]
```diff
@@ -48,192 +62,157 @@ void OnDockedModeChanged(bool last_state, bool new_state) {
...
+        connect(player_connected[i], &QCheckBox::stateChanged,
+                [&, i](int state) { player_controllers[i]->ConnectPlayer(state == Qt::Checked); });
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input.cpp:108]:
```suggestion
                [this, i](int state) { player_controllers[i]->ConnectPlayer(state == Qt::Checked); });
```

File: src/yuzu/configuration/configure_input.cpp [hunk 18]
```diff
@@ -48,192 +62,157 @@ void OnDockedModeChanged(bool last_state, bool new_state) {
...
-    ui->handheld_connected->setEnabled(!ui->use_docked_mode->isChecked());
-    ui->handheld_configure->setEnabled(ui->handheld_connected->isChecked() &&
-                                       !ui->use_docked_mode->isChecked());
-    ui->mouse_advanced->setEnabled(ui->mouse_enabled->isChecked());
-    ui->debug_configure->setEnabled(ui->debug_enabled->isChecked());
-    ui->touchscreen_advanced->setEnabled(ui->touchscreen_enabled->isChecked());
+void ConfigureInput::ClearAll() {
+    // We don't have a good way to know what tab is active, but we can find out by getting the
+    // parent of the consoleInputSettings
+    auto player_tab = static_cast<ConfigureInputPlayer*>(ui->consoleInputSettings->parent());
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input.cpp:185]:
```suggestion
    auto* player_tab = static_cast<ConfigureInputPlayer*>(ui->consoleInputSettings->parent());
```

File: src/yuzu/configuration/configure_input.cpp [hunk 19]
```diff
@@ -48,192 +62,157 @@ void OnDockedModeChanged(bool last_state, bool new_state) {
...
-void ConfigureInput::LoadConfiguration() {
-    std::stable_partition(
-        Settings::values.players.begin(),
-        Settings::values.players.begin() +
-            Service::HID::Controller_NPad::NPadIdToIndex(Service::HID::NPAD_HANDHELD),
-        [](const auto& player) { return player.connected; });
+void ConfigureInput::RestoreDefaults() {
+    // We don't have a good way to know what tab is active, but we can find out by getting the
+    // parent of the consoleInputSettings
+    auto player_tab = static_cast<ConfigureInputPlayer*>(ui->consoleInputSettings->parent());
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input.cpp:192]:
```suggestion
    auto* player_tab = static_cast<ConfigureInputPlayer*>(ui->consoleInputSettings->parent());
```

File: src/yuzu/configuration/configure_input.h [hunk 20]
```diff
@@ -10,34 +10,40 @@
...
 
+#include "yuzu/configuration/configure_input_advanced.h"
+#include "yuzu/configuration/configure_input_player.h"
+
 #include "ui_configure_input.h"
 
-class QPushButton;
 class QString;
 class QTimer;
+class QCheckBox;
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input.h:20]: This should be alphabetically organized.

File: src/yuzu/configuration/configure_input_advanced.cpp [hunk 21]
```diff
@@ -0,0 +1,169 @@
...
+// Refer to the license.txt file included.
+
+#include <QColorDialog>
+#include "core/core.h"
+#include "core/settings.h"
+#include "ui_configure_input_advanced.h"
+#include "yuzu/configuration/configure_input_advanced.h"
+
+ConfigureInputAdvanced::ConfigureInputAdvanced(QWidget* parent)
+    : QWidget(parent), ui(new Ui::ConfigureInputAdvanced) {
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_advanced.cpp:12]:
```suggestion
    : QWidget(parent), ui(std::make_unique<Ui::ConfigureInputAdvanced>()) {
```

File: src/yuzu/configuration/configure_input_advanced.h [hunk 22]
```diff
@@ -0,0 +1,44 @@
+// Copyright 2020 yuzu Emulator Project
+// Licensed under GPLv2 or any later version
+// Refer to the license.txt file included.
+
+#pragma once
+
+#include <memory>
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_advanced.h:7]: Missing an `<array>` include

File: src/yuzu/configuration/configure_input_player.cpp [hunk 23]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
-    connect(ui->buttonRestoreDefaults, &QPushButton::clicked, [this] { RestoreDefaults(); });
+    // Player Connected checkbox
+    connect(ui->groupConnectedController, &QGroupBox::toggled,
+            [&](bool checked) { emit Connected(checked); });
+
+    // Set up controller type. Only Player 1 can choose Handheld.
+    ui->comboControllerType->clear();
+
+    QStringList controller_types = {
+        QStringLiteral("Pro Controller"),
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:357]: Shouldn't these be translatable in the UI?

File: src/yuzu/configuration/configure_input_player.cpp [hunk 24]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+                });
+    }
+
+    // The Debug Controller can only choose the Pro Controller.
+    if (debug) {
+        ui->buttonScreenshot->setEnabled(false);
+        ui->buttonHome->setEnabled(false);
+        ui->groupConnectedController->setCheckable(false);
+        QStringList debug_controller_types = {
+            QStringLiteral("Pro Controller"),
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:378]: Ditto

File: src/yuzu/configuration/configure_input_player.cpp [hunk 25]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+
+    UpdateControllerIcon();
+    UpdateControllerAvailableButtons();
+    connect(ui->comboControllerType, qOverload<int>(&QComboBox::currentIndexChanged), [&](int) {
+        UpdateControllerIcon();
+        UpdateControllerAvailableButtons();
+    });
+
+    connect(ui->comboDevices, qOverload<int>(&QComboBox::currentIndexChanged),
+            [&] { UpdateMappingWithDefaults(); });
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:393]:
```suggestion
    connect(ui->comboDevices, qOverload<int>(&QComboBox::currentIndexChanged),
            &ConfigureInputPlayer::UpdateMappingWithDefaults);
```

File: src/yuzu/configuration/configure_input_player.cpp [hunk 26]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+
+    ui->buttonRefreshDevices->setIcon(QIcon::fromTheme(QStringLiteral("view-refresh")));
+    UpdateInputDevices();
+    connect(ui->buttonRefreshDevices, &QPushButton::clicked, [&] { emit RefreshInputDevices(); });
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:397]:
```suggestion
    connect(ui->buttonRefreshDevices, &QPushButton::clicked, [this] { emit RefreshInputDevices(); });
```

File: src/yuzu/configuration/configure_input_player.cpp [hunk 27]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+            QStringLiteral("Pro Controller"),
+        };
+        ui->comboControllerType->addItems(debug_controller_types);
+    } else {
+        ui->comboControllerType->addItems(controller_types);
+    }
+
+    UpdateControllerIcon();
+    UpdateControllerAvailableButtons();
+    connect(ui->comboControllerType, qOverload<int>(&QComboBox::currentIndexChanged), [&](int) {
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:387]:
```suggestion
    connect(ui->comboControllerType, qOverload<int>(&QComboBox::currentIndexChanged), [this](int) {
```

File: src/yuzu/configuration/configure_input_player.cpp [hunk 28]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+        QStringLiteral("Pro Controller"),
+        QStringLiteral("Dual Joycons"),
+        QStringLiteral("Left Joycon"),
+        QStringLiteral("Right Joycon"),
+    };
+
+    if (player_index == 0) {
+        controller_types.append(QStringLiteral("Handheld"));
+        connect(ui->comboControllerType, qOverload<int>(&QComboBox::currentIndexChanged),
+                [&](int index) {
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:366]:
```suggestion
                [this](int index) {
```

File: src/yuzu/configuration/configure_input_player.cpp [hunk 29]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+
+    QStringList controller_types = {
+        QStringLiteral("Pro Controller"),
+        QStringLiteral("Dual Joycons"),
+        QStringLiteral("Left Joycon"),
+        QStringLiteral("Right Joycon"),
+    };
+
+    if (player_index == 0) {
+        controller_types.append(QStringLiteral("Handheld"));
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:364]: Ditto about being translatable.

File: src/yuzu/configuration/configure_input_player.cpp [hunk 30]
```diff
@@ -683,3 +703,114 @@ void ConfigureInputPlayer::keyPressEvent(QKeyEvent* event) {
     }
     SetPollingResult({}, true);
 }
+
+void ConfigureInputPlayer::UpdateControllerIcon() {
+    // We aren't using Qt's built in theme support here since we aren't drawing an icon (and its
+    // "nonstandard" to use an image through the icon support)
+    QString stylesheet{};
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:710]: This can be assigned to directly using a lambda like `theme` is a little further down.

File: src/yuzu/configuration/configure_input_player.cpp [hunk 31]
```diff
@@ -683,3 +703,114 @@ void ConfigureInputPlayer::keyPressEvent(QKeyEvent* event) {
...
+
+void ConfigureInputPlayer::UpdateControllerAvailableButtons() {
+    auto layout = GetControllerTypeFromIndex(ui->comboControllerType->currentIndex());
+    if (debug) {
+        layout = Settings::ControllerType::DualJoyconDetached;
+    }
+
+    // List of all the widgets that will be hidden by any of the following layouts that need
+    // "unhidden" after the controller type changes
+    const std::vector<QWidget*> layout_show = {
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:752]: This can be a std::array instead of a vector.

File: src/yuzu/uisettings.h [hunk 32]
```diff
@@ -13,6 +13,7 @@
 #include <QStringList>
 #include <QVector>
 #include "common/common_types.h"
+#include "core/settings.h"
```
Comment (lioncash) [inline src/yuzu/uisettings.h:16]: What does this file need from this header?

File: src/yuzu/configuration/configure_input_player.cpp [hunk 33]
```diff
@@ -185,208 +242,159 @@ ConfigureInputPlayer::ConfigureInputPlayer(QWidget* parent, std::size_t player_i
...
+                tr("Modifier Range: %1%").arg(slider_value));
+            analogs_param[analog_id].Set("modifier_scale", slider_value / 100.0f);
+        });
     }
 
-    connect(ui->buttonClearAll, &QPushButton::clicked, [this] { ClearAll(); });
-    connect(ui->buttonRestoreDefaults, &QPushButton::clicked, [this] { RestoreDefaults(); });
+    // Player Connected checkbox
+    connect(ui->groupConnectedController, &QGroupBox::toggled,
+            [&](bool checked) { emit Connected(checked); });
```
Comment (lioncash) [inline src/yuzu/configuration/configure_input_player.cpp:351]:
```suggestion
            [this](bool checked) { emit Connected(checked); });
```

**Comment by toccata10** [comment]
Thank you so much  for this improvement !
A bit of testing on Archlinux:
I can't see any picture and the ui is not well rendered on a Hidpi screen (but usable nonetheless).

2nd problem:
If I change the deadzone to 20%, then if I record the up for the left stick (for example): the deadzone goes back to 10%.
I would also suggest a default deadzone of 20% (or even 25%): when I was following this input rewrite on Ryujinx, I remember a lot of users wondering why they character was moving all by itelf on the screen. I'd say: let's take 25% by default, this way it'll work flawlessly for everyone.  More advanced users will be able to adjust to their needs.
