### PR TITLE
code: dodge PAGE_SIZE #define

### LINKED ISSUE #8779: Failure to build on Musl systems due to redefining PAGE_SIZE
I've been trying to build Yuzu for Alpine Linux, which uses the Musl libc rather than glibc. It however fails to build with the following error:

```
ninja: job failed: /usr/lib/ccache/bin/g++ -DARCHITECTURE_x86_64=1 -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DFMT_LOCALE -DFMT_SHARED -DNDEBUG -DXBYAK_NO_OP_NAMES -DYUZU_UNIX=1 -D_FILE_OFFSET_BITS=64 -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/. -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/build/src/video_core/host_shaders/include -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/video_core/sirit -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/video_core/../../externals/Vulkan-Headers/include -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/externals/./microprofile -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/externals/glad/include -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/externals/sirit/src/../include -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/externals/sirit/externals/SPIRV-Headers/include -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/externals/dynarmic/src/dynarmic/.. -I/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/externals/dynarmic/externals/mcl/src/../include -isystem /usr/include/SDL2 -isystem /home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/build/externals/xbyak/include -Os -fomit-frame-pointer -O2 -g -DNDEBUG -Wall -Werror=array-bounds -Werror=implicit-fallthrough -Werror=missing-declarations -Werror=missing-field-initializers -Werror=reorder -Werror=shadow -Werror=sign-compare -Werror=switch -Werror=uninitialized -Werror=unused-function -Werror=unused-result -Werror=unused-variable -Wextra -Wmissing-declarations -Wno-attributes -Wno-invalid-offsetof -Wno-unused-parameter -mcx16 -Werror=conversion -Wno-error=sign-conversion -Werror=pessimizing-move -Werror=redundant-move -Werror=type-limits -Werror=class-memaccess -Werror=unused-but-set-parameter -Werror=unused-but-set-variable -std=gnu++20 -MD -MT src/video_core/CMakeFiles/video_core.dir/shader_cache.cpp.o -MF src/video_core/CMakeFiles/video_core.dir/shader_cache.cpp.o.d -o src/video_core/CMakeFiles/video_core.dir/shader_cache.cpp.o -c /home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/video_core/shader_cache.cpp
In file included from /usr/include/limits.h:40,
                 from /usr/include/fortify/stdlib.h:29,
                 from /usr/include/c++/12.1.1/cstdlib:75,
                 from /usr/include/c++/12.1.1/bits/stl_algo.h:69,
                 from /usr/include/c++/12.1.1/algorithm:61,
                 from /home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/video_core/shader_cache.cpp:4:
/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/./video_core/shader_cache.h:33:26: error: expected unqualified-id before numeric constant
   33 |     static constexpr u64 PAGE_SIZE = u64(1) << PAGE_BITS;
      |                          ^~~~~~~~~
```

It _seems_ this happens because PAGE_SIZE is already defined in Linux's kernel headers, and thus this is overwriting it. A quick look around the internet made me find [this StackOverflow answer](https://stackoverflow.com/a/37897870) which suggests using `sysconf(_SC_PAGESIZE)` to get the system PAGE_SIZE. I'm not much of an experienced CPP coder however and couldn't make it work myself.

The problematic pieces of code are https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/shader_cache.h#L33 and https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/query_cache.h#L263.

### PR DESCRIPTION
**Pull request by Docteh**
Some header files, specifically for OSX and Musl libc define PAGE_SIZE to be a number
This is great except in yuzu we're using PAGE_SIZE as a variable

Specific example
```cpp
static constexpr u64 PAGE_SIZE = u64(1) << PAGE_BITS;
```

PAGE_SIZE PAGE_BITS PAGE_MASK are all similar variables.
Simply deleted the underscores, and then added YUZU_ prefix

Might be worth noting that there are multiple uses in different classes/namespaces
This list may not be exhaustive

Core::Memory   12 bits (4096)
QueryCacheBase 12 bits
ShaderCache    14 bits (16384)
TextureCache   20 bits (1048576, or 1MB)

Fixes #8779

----

~~I had an odd graphical glitch in mario kart earlier, so I'm going to grab the verification build and try a few races just in case, but it seemed to not be related to this PR~~ Was just glitch, hasn't shown since

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

**Comment by PureTryOut** [comment]
This fails to compile for me as is:

```
/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/./video_core/buffer_cache/buffer_cache.h:1602:41: error: no matching function for call to 'DivCeil(const VAddr&, int)'
 1602 |     const u64 page_end = Common::DivCeil(cpu_addr_end, PAGESIZE);
      |                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

Not sure why as CI seems to think it's fine?

**Comment by Docteh** [comment]
image

https://github.com/yuzu-emu/yuzu/blob/2e58491c387cb304c154972814917b9d66630d1f/src/common/div_ceil.h#L11-L16

Looking at the template, and your error, somehow your PAGESIZE is signed (int), and the template doesn't like that (std::is_unsigned_v)

**Comment by PureTryOut** [comment]
Strange, as previously I was just unsetting my system-provided `PAGE_SIZE` and that worked fine even though the variable type (obviously) didn't change compared to this PR.

**Comment by Docteh** [comment]
```cpp
const u64 page_end = Common::DivCeil(cpu_addr_end, static_cast<u64>(PAGESIZE));
```

Try a static cast and see if you can get a more interesting error? Be funny if PAGESIZE is also `#define` to something. To test that, maybe. 
```cpp
const u64 page_end = Common::DivCeil(cpu_addr_end, 65536ULL);
```

Although I guess if PAGESIZE was defined to something, it should have complained back at line 64 of buffer_cache.h

**Comment by PureTryOut** [comment]
Well, it does complain about `PAGESIZE` too.

```
/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/./video_core/shader_cache.h:33:26: error: expected unqualified-id before numeric constant
   33 |     static constexpr u64 PAGESIZE = u64(1) << PAGEBITS;
      |                          ^~~~~~~~
/home/bart/Documents/Git/alpine/aports/testing/yuzu/src/yuzu-6f931d49c74017fb66bf285dd060bc455ae05c85/src/./video_core/query_cache.h:263:37: error: expected unqualified-id before numeric constant
  263 |     static constexpr std::uintptr_t PAGESIZE = 4096;
      |
```

I can't find anything about `PAGESIZE` already being defined though, only PAGE_SIZE is mentioned everywhere. So not sure what's up with that. Static casting helps the error I mentioned earlier, but (obviously) it doesn't resolve this particular one.

File: src/core/memory.h [hunk 1]
```diff
@@ -27,9 +27,9 @@ namespace Core::Memory {
  * Page size used by the ARM architecture. This is the smallest granularity with which memory can
  * be mapped.
  */
-constexpr std::size_t PAGE_BITS = 12;
-constexpr u64 PAGE_SIZE = 1ULL << PAGE_BITS;
-constexpr u64 PAGE_MASK = PAGE_SIZE - 1;
+constexpr std::size_t PAGEBITS = 12;
```
Comment (lioncash) [inline src/core/memory.h:30]: Given how annoying C libraries and other system libraries are with defines, you may want to just prepend `YUZU_` to the beginning of these to prevent any kind of clashing, regardless of spacing or not

Comment (Docteh) [reply src/core/memory.h:30]: Should I try and separate the different PAGESIZE/PAGEBITS definitions? (first comment) Or just YUZU_PAGESIZE, YUZU_PAGEMASK, YUZU_PAGEBITS?

**Comment by PureTryOut** [comment]
Prefixing them with `YUZU_` has done the job, thanks!
