### PR TITLE
android: Input mapping

### LINKED ISSUE #12841: Gamepad vibrations are not working [Android]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All builds

### Description of Issue

I have connected my wired Xbox 360 controller to my phone with an OTG cable but while playing games in the Yuzu V212 the game pad does not vibrate. I have also enabled the vibration on inside the game settings but still not getting any type of vibrations. The games I tried are Assassin's creed 4 black flag, Batman Arkham Asylum & Arkham City. The gamepad is working properly & the gamepad vibrations are also working properly while playing games in Aethersx2 & Dolphin emulator.

### Expected Behavior

The gamepad with vibration motors should vibrate as the original console. This thing will be really useful for people who play the emulator with a gamepad that has vibration motors and connect the gamepad to their phone by OTG cable or wireless dongle. I think the vibration feedback also gives a little bit of immersion in games

### Reproduction Steps

Just connect your wired gamepad with vibration motors to your phone with OTG cable or wireless dongle. Make sure you connect the controller with only wired or wireless dongle the vibration does not work in Bluetooth mode also make sure the controller does have working vibration motors. Try playing the games I mentioned or any other game you own the controller vibrations are not going to work but try the controller in Aethersx2 or dolphin emulator and the vibration works fine.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14081522/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 888
GPU/Driver: Adreno 660
RAM: 12 GB
ROM: 256 GB
Device: Realme GT2
OS: Android 13

### PR DESCRIPTION
**Pull request by t895**
Input mapping is finally here and we have a lot to cover!

Here's what's new
- Connecting and disconnecting each controller
- Changing each controller's type between Pro Controller, Left Joycon, Right Joycon, Handheld (player 1 only), and Gamecube
- Selecting a device from the "Input device" dropdown to auto-map a controller
- If you don't have any controllers mapped, you can still start any game and have the first connected controller ready to play with auto-mapping
- Creating/loading input profiles
- Mapping each control with an axis or button
- Each mapping has options for modifiers like invert, toggle, and turbo
- Each stick has the option to set a deadzone and a range
- Controllers and phones (system vibration motors generally) can vibrate now

Limitations and potential problems
- HD Rumble is not supported yet
- Only gamepads can be mapped so don't expect to hook up a keyboard or play Mario with your volume buttons
- There is no controller visualization page yet
- Per-game input profiles were not included due to a longstanding bug with profile config. This will be addressed in a later PR.
- If there are any inconsistency issues with auto mapping, please report them to me. The expected layout for face buttons should be A - Right button, B - Bottom button, X - Top button, Y - Left button.
- A note for **AYN Odin 2** users: There is a bug affecting the Odin's controller handling where the first controller connected besides the integrated one will share the same ID information as the integrated controller and have broken vibrations/auto-mapping (but controllers connected past that will be fine). This is known to AYN and cannot be fixed on my end so please do not report this.

I'd also like to thank @german77 for laying some of the groundwork in his input engine that I needed to get started.

Closes
#12841
#12197
#12121
#12057
#11593
#11124

<details>
<summary>Media</summary>

I've decided to spare your eyes this time with dark mode

image

image

image

I'm really hoping that everyone gets the message about the input device drop down -_-

anim-single-dir

anim-two-dir

Some pretty animations to enjoy while you're mapping :)

image

Go crazy with the modifiers

image

It's about time that we got a deadzone slider!

image

image

Love you Golden ❤️
</details>

### CODE REVIEW

File: src/input_common/drivers/android.h [hunk 1]
```diff
@@ -43,12 +46,86 @@ class Android final : public InputEngine {
...
+        [[maybe_unused]] const Common::ParamPackage& params) const override;
+
 private:
+    std::unordered_map<PadIdentifier, jobject> input_devices;
+
     /// Returns the correct identifier corresponding to the player index
-    PadIdentifier GetIdentifier(std::size_t controller_number) const;
+    PadIdentifier GetIdentifier(const std::string& guid, size_t port) const;
+
+    const s32 AXIS_X = 0;
```
Comment (german77) [inline src/input_common/drivers/android.h:86]: static constexpr

File: src/input_common/drivers/android.h [hunk 2]
```diff
@@ -43,12 +46,86 @@ class Android final : public InputEngine {
      * @param gyro_x,gyro_y,gyro_z the gyro sensor readings
      * @param accel_x,accel_y,accel_z the accelerometer reading
      */
-    void SetMotionState(std::size_t controller_number, u64 delta_timestamp, float gyro_x,
+    void SetMotionState(std::string guid, size_t port, u64 delta_timestamp, float gyro_x,
                         float gyro_y, float gyro_z, float accel_x, float accel_y, float accel_z);
 
+    Common::Input::DriverResult SetVibration(
+        [[maybe_unused]] const PadIdentifier& identifier,
```
Comment (german77) [inline src/input_common/drivers/android.h:53]: headers don't need the [[maybe_unused]] attribute

File: src/input_common/drivers/android.cpp [hunk 3]
```diff
@@ -37,10 +54,295 @@ void Android::SetMotionState(std::size_t controller_number, u64 delta_timestamp,
...
+                static_cast<float>((vibration.high_amplitude + vibration.low_amplitude) / 2.0);
+            env->CallVoidMethod(device->second, Common::Android::GetYuzuDeviceVibrate(),
+                                average_intensity);
+        });
+        return Common::Input::DriverResult::Success;
+    }
+    return Common::Input::DriverResult::NotSupported;
+}
+
+bool Android::IsVibrationEnabled([[maybe_unused]] const PadIdentifier& identifier) {
```
Comment (german77) [inline src/input_common/drivers/android.cpp:73]: identifier is actually used

File: src/input_common/drivers/android.cpp [hunk 4]
```diff
@@ -37,10 +54,295 @@ void Android::SetMotionState(std::size_t controller_number, u64 delta_timestamp,
     SetMotion(identifier, 0, motion_data);
 }
 
-PadIdentifier Android::GetIdentifier(std::size_t controller_number) const {
+Common::Input::DriverResult Android::SetVibration(
+    [[maybe_unused]] const PadIdentifier& identifier,
```
Comment (german77) [inline src/input_common/drivers/android.cpp:58]: identifier and vibration are used

File: src/hid_core/frontend/emulated_controller.cpp [hunk 5]
```diff
@@ -1277,6 +1283,12 @@ bool EmulatedController::SetVibration(DeviceIndex device_index, const VibrationV
         .high_frequency = vibration.high_frequency,
         .type = type,
     };
+
+    // Send vibrations to Android's input overlay
+    if (npad_id_type == NpadIdType::Handheld || npad_id_type == NpadIdType::Player1) {
+        output_devices[4]->SetVibration(status);
```
Comment (german77) [inline src/hid_core/frontend/emulated_controller.cpp:1289]: Forgot this check handled && player1 isn't needed here since the params are already defined just for handheld and player1. So we can leave this part as just `output_devices[4]->SetVibration(status);`

File: src/common/settings_input.h [hunk 6]
```diff
@@ -395,6 +395,10 @@ struct PlayerInput {
     u32 button_color_left;
     u32 button_color_right;
     std::string profile_name;
+
+#ifdef ANDROID
+    bool use_system_vibrator;
```
Comment (german77) [inline src/common/settings_input.h:400]: Do we need to exclude this from other systems? I would rather just leave a comment saying this is for android support.

File: src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt [hunk 7]
```diff
@@ -137,6 +137,8 @@ class SettingsActivity : AppCompatActivity() {
         super.onStop()
         Log.info("[SettingsActivity] Settings activity stopping. Saving settings to INI...")
         if (isFinishing) {
+            NativeInput.unloadInputProfiles()
```
Comment (german77) [inline src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt:140]: unload isn't required here. You can reload directly.

**Review by german77 — COMMENTED** [review]
I like how it was integrated with the existing input backend

**Comment by t895** [comment]
Reworked the "Input Device" setting
It's now split into two options to make things clearer.
- Auto-map a controller: Select a device from the list to attempt auto mapping with
- Input mapping filter: Select a device or "Any" from the list to use as a filter for the mapping dialogs

**Review by liamwhite — APPROVED** [review]

**Comment by dannygaray60** [comment]
@t895 thanks for yoy work! Very appreciated, just as an advice, the Xbox Series X controller still has the layout inverted when you use the automatic mapping

**Comment by t895** [comment]
Are A and B flipped or A and B + X and Y flipped?

**Comment by dannygaray60** [comment]
@t895 the A/B are fliped and X/Y fliped

**Comment by H0nzik1** [comment]
@t895 could you please verify why it is not working in Rayman Legends Definitive Edition? I have mapped 3 controllers, no luck. I am still using this fork https://github.com/chulinx/yuzu-android/releases to play it. Thanks

**Comment by darix080** [comment]
I am not able to remap my controller, could you help me?

This is my controller
Screenshot_20240207_000724_Gamepad Tester

**Comment by JomPyx** [comment]
Thanks for adding the remapping button. But I hope it will be fixed for generic gamepad usb. Because the button A, B, X, Y, R, L, ZR, ZL cannot be input and only the analog, dpad is working. I hope you will fix it soon. 🙏🙏
