### PR TITLE
aoc: stub purchase info calls

### LINKED ISSUE #11539: The settlers New Alliase
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1562

### Description of Issue

D'ont start The settlers New Alliase

### Expected Behavior

don't start

### Reproduction Steps

hold on

### Log File

[yuzu_log-2.txt](https://github.com/yuzu-emu/yuzu/files/12652404/yuzu_log-2.txt)

### System Configuration

CPU:AMD Ryzen Threadripper 2950X 16-Core Processor  | AVX2 | FMA
GPU/Driver: AMD 5700 RT
RAM: 15GB
OS: Windows 11 Version 22H2 (Build 22621.2283)

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #11539

### CODE REVIEW

File: src/core/hle/service/aoc/aoc_u.cpp [hunk 1]
```diff
@@ -101,6 +103,20 @@ class IPurchaseEventManager final : public ServiceFramework<IPurchaseEventManage
         rb.PushCopyObjects(purchased_event->GetReadableEvent());
     }
 
+    void PopPurchasedProductInfo(HLERequestContext& ctx) {
+        LOG_DEBUG(Service_AOC, "(STUBBED) called");
```
Comment (FearlessTobi) [inline src/core/hle/service/aoc/aoc_u.cpp:107]: is this being spam-called by games?
if not, it should probably be LOG_WARNING

**Review by FearlessTobi — APPROVED** [review]

File: src/core/hle/service/aoc/aoc_u.cpp (hunk 1 above)
Comment (liamwhite) [reply src/core/hle/service/aoc/aoc_u.cpp:107]: it is
